import type { FreeGuide } from './freeGuides';

/** Premium education library — insider topics, client-first voice. Educational only. */
export const EXTENDED_FREE_GUIDES: FreeGuide[] = [
  {
    id: 'primary-tradeline-insider',
    title: 'Primary Tradeline Insider Field Manual',
    desc: 'What 98% of consumers never hear from lenders: how primaries actually post, age, and interact with underwriting — without the myths.',
    sections: [
      { heading: 'Primary vs authorized user (the line that matters)', bullets: ['A primary tradeline is an account where you are the contractual obligor — the name on the agreement.', 'Authorized user (AU) status can help utilization optics but does not carry the same weight as a primary for many underwriters.', 'Insider signal: funders often look for primaries with payment history depth, not just high limits on paper.'] },
      { heading: 'How primaries actually land on your file', bullets: ['Issuers report on their own cadence — typically monthly, often aligned to statement close, not payment due date.', 'Some primaries report to one bureau only; “thick” files require knowing which bureau each issuer feeds.', 'New primaries can suppress scores short-term (inquiry + new account) before they help — plan a 90-day runway.'] },
      { heading: 'Bank-verified primaries (what underwriters whisper)', bullets: ['“Bank verified” usually means the tradeline is tied to a real deposit relationship or internal verification — not a sticker on a reseller site.', 'Underwriters cross-check name, address, and sometimes EIN/SSN consistency before treating a primary as fundable signal.', 'Red flag: primaries that appear with mismatched addresses or impossible open dates relative to your identity timeline.'] },
      { heading: 'Mortgage & auto primaries (different game)', bullets: ['Installment primaries (auto, personal loan) behave differently from revolving — utilization math does not apply the same way.', 'Mortgage primaries are heavy signals but slow to build; auto primaries can help “installment mix” if reported cleanly.', 'Insider tip: a clean auto loan paid on time for 12+ months often beats three new revolving cards for certain auto lenders.'] },
      { heading: 'Combo packages (12 / 18 / 21 / 24 month ladders)', bullets: ['Resellers market “combo” primaries by age bucket — the logic is seasoning, not magic.', 'Underwriting cares about average age of accounts and oldest tradeline — combos target those metrics deliberately.', 'Customer-first rule: never stack combos without checking inquiry load, duplicate tradelines, and bureau consistency first.'] },
      { heading: 'What primaries cannot do', bullets: ['They cannot erase legitimate negative history by themselves.', 'They cannot override fraud alerts, identity mismatches, or unpaid tax liens.', 'They cannot replace income verification, DTI analysis, or business cash-flow proof for real funding.'] },
      { heading: 'Execution checklist (Finely Cred workflow)', bullets: ['Pull tri-bureau reports; map which primaries exist on which file.', 'Screenshot open date, status, limit, payment grid — store in Documents vault.', 'Set a 90-day calendar: inquiry spacing, utilization targets, and re-pull before any funding application.', 'Track in portal Tasks — one primary review task per bureau branch.'] },
      { heading: 'Disclaimer', bullets: ['Educational only; not legal or financial advice. Tradeline strategies carry risk — verify compliance and lender policies before acting.'] },
    ],
  },
  {
    id: 'business-credit-jumpstart',
    title: 'Business Credit Jumpstart (Zero to Fundable)',
    desc: 'The sequence lenders expect before they ever see your application — entity hygiene, bureau alignment, and vendor stacking insiders use.',
    sections: [
      { heading: 'Week 1 — Entity truth on paper', bullets: ['Secretary of State name must match bank account, EIN letter, and every application character-for-character.', 'Get a dedicated business phone (not a personal cell) listed in 411 and Google Business Profile.', 'Business address: commercial or virtual with suite — know which lenders reject home-based filings.'] },
      { heading: 'Week 2 — Bureau footprint', bullets: ['Register D-U-N-S if building Paydex; verify Experian Business and Equifax Business for ghost listings.', 'Fix mismatches before applying — one wrong NAICS code can auto-decline tier-1 vendors.', 'Insider: many “denied” stories are really “never matched” stories — the bureau never linked your EIN to the entity.'] },
      { heading: 'Week 3–4 — Tier-1 vendor stack', bullets: ['Start with net-30 vendors that report predictably (office supply, industrial suppliers).', 'Order small, pay early — reporting often lags 30–45 days; patience is part of the strategy.', 'Do not apply to five vendors same week — inquiry patterns on business files matter too.'] },
      { heading: 'Month 2 — Revolving business credit', bullets: ['First business card usually PG-backed — understand personal guarantee exposure.', 'Choose issuers that report to business bureaus, not personal-only feeds.', 'Keep utilization under 30% on business revolvers before applying for lines of credit.'] },
      { heading: 'Month 3+ — Funding readiness', bullets: ['Bank statements: 3–6 months clean history, no NSF, consistent deposits matching revenue story.', 'Document folder: articles, EIN, lease, vendor statements, bank letters — ready for underwriter requests.', 'Apply for funding in sequence: vendor lines → business cards → term loans / LOC — not all at once.'] },
      { heading: 'Shelf corps (compliance reality check)', bullets: ['Aged entities can help seasoning narratives but cannot fix bad personal credit or missing financials.', 'Underwriters verify beneficial ownership, activity, and bank history — a shelf without activity is a red flag.', 'Never misrepresent entity age or revenue — that crosses from optimization into fraud.'] },
      { heading: 'Disclaimer', bullets: ['Educational only; consult CPAs and attorneys for entity and tax structure decisions.'] },
    ],
  },
  {
    id: 'loan-funding-sequence',
    title: 'Loan Funding Sequence Playbook',
    desc: 'How sophisticated borrowers stage personal and business funding — banking relationships, app timing, and DTI optics insiders watch.',
    sections: [
      { heading: 'The funding stack (personal → business)', bullets: ['Personal file readiness: inquiries controlled, utilization staged, no unresolved disputes mid-application.', 'Business file readiness: 3+ reporting tradelines, consistent entity data, bank history.', 'Insider: funders often pull both — personal PG exposes weak personal files even on “business” loans.'] },
      { heading: 'Banking secrets (relationship, not tricks)', bullets: ['Primary business checking with the lender you will ask for credit — 90+ days before application.', 'Maintain average daily balance; avoid zelle-only “business” activity with no paper trail.', 'Relationship bankers flag files for manual review when they know your deposit story — cold apps get algorithm declines.'] },
      { heading: 'Smart application timing', bullets: ['Space hard pulls 30–45 days minimum when building; 90 days is safer for mortgage-adjacent goals.', 'Apply after statement close when utilization reports low — know each card’s reporting date.', 'Never apply during active dispute rounds on accounts the lender will scrutinize.'] },
      { heading: '500-app myth vs real strategy', bullets: ['Volume app lists circulate online — most are outdated, duplicate pulls, or pre-qual soft checks mislabeled.', 'Real strategy: 5–10 targeted apps matched to your file metrics, income band, and inquiry budget.', 'Track every pull in a spreadsheet: bureau, date, result, next eligible date.'] },
      { heading: 'House / car / 100K paths', bullets: ['House: dispute work completes months before mortgage shopping — mid-dispute files get manual underwriting delays.', 'Auto: score tiers map to APR bands; installment history often matters more than +20 FICO points.', '100K+ unsecured: usually business revenue, collateral, or exceptional personal profile — sequence business credit first.'] },
      { heading: 'After approval discipline', bullets: ['Do not max new lines immediately — lenders re-review for CLI and cross-sell.', 'Set autopay + calendar reminders; one 30-day late on a new tradeline erases months of stacking work.', 'Document approval letters and terms in portal Documents for future refinance leverage.'] },
      { heading: 'Disclaimer', bullets: ['Educational only; lending decisions vary by institution. No guarantee of approval.'] },
    ],
  },
  {
    id: 'ai-dispute-workflows',
    title: 'AI Credit Workflows (What Actually Helps)',
    desc: 'How Finely customers use AI to organize disputes, decode bureau responses, and draft cleaner letters — without replacing human judgment.',
    sections: [
      { heading: 'What AI is good at in credit restore', bullets: ['Spotting Metro2 field contradictions across screenshots faster than manual scan.', 'Drafting first-pass dispute language scoped to one claim — you edit, you send.', 'Summarizing 40-page bureau responses into action items with deadlines.'] },
      { heading: 'What AI cannot do', bullets: ['It cannot guarantee deletions or know private furnisher policies.', 'It cannot replace licensed legal advice on lawsuits, summons, or bankruptcy timing.', 'It should never invent facts, account numbers, or dates not in your evidence pack.'] },
      { heading: 'The Finely AI dispute loop', bullets: ['Upload report + evidence → AI extracts tradeline fields into structured cards.', 'Human selects ONE claim → AI drafts letter tied to exhibits.', 'You review every sentence → mail → log dates → AI parses response for next branch.', 'Repeat per bureau, per item — never merge branches in one prompt.'] },
      { heading: 'Prompt discipline (insider operator rules)', bullets: ['Always attach screenshots; never ask AI to “guess” balances or dates.', 'Request “method of verification” language only when your claim is unverifiable/inaccurate.', 'Ban emotional adjectives — bureaus respond to field-level contradictions.'] },
      { heading: 'AI + tradeline / funding planning', bullets: ['Use AI to model inquiry budget: “If I apply here and here, what’s my 90-day pull count?”', 'Simulate utilization reporting dates against target scores before funding apps.', 'Generate checklists for business vendor sequencing — human approves each step.'] },
      { heading: 'Privacy & compliance', bullets: ['Redact SSN full numbers in prompts; use last-4 only when necessary.', 'Store outputs in portal vault — not random chat histories.', 'Educational use only; you remain responsible for mailed disputes.'] },
      { heading: 'Disclaimer', bullets: ['Educational only; AI outputs require human review before any legal mail.'] },
    ],
  },
  {
    id: 'combo-tradeline-ladder',
    title: 'Combo Tradeline Ladder (Seasoning Decoded)',
    desc: '12 / 18 / 21 / 24-month combo logic explained — what underwriters measure, and how to avoid duplicate-tradeline traps.',
    sections: [
      { heading: 'Why age buckets exist', bullets: ['Credit algorithms weight average age of accounts (AAoA) and oldest tradeline.', 'Combo products target specific age thresholds — 12mo vs 24mo is not marketing fluff, it is metric targeting.', 'Insider: some lenders ignore AU age for AAoA — primaries only for certain mortgage overlays.'] },
      { heading: 'Before you buy anything', bullets: ['Pull reports — know current AAoA and oldest trade.', 'Calculate inquiry cost vs metric gain — will one primary move the needle enough?', 'Verify reseller delivers bureau-specific reporting, not “credit karma age.”'] },
      { heading: 'Stacking rules', bullets: ['Never duplicate the same tradeline type on one bureau — looks synthetic.', 'Space new account reporting 30+ days apart when possible.', 'Pair combo work with utilization control — age without clean utilization still declines.'] },
      { heading: 'Combo + funding timeline', bullets: ['Month 0: baseline pull + document AAoA.', 'Month 1–2: primaries post, expect temporary score volatility.', 'Month 3: re-pull, verify fields, then begin funding apps if metrics hit target.', 'Month 6+: maintain — closing old accounts resets age work.'] },
      { heading: 'Disclaimer', bullets: ['Educational only; tradeline products vary widely in compliance and reporting.'] },
    ],
  },
  {
    id: 'ucc1-business-filing-primer',
    title: 'UCC-1 Filing Primer (Business Context)',
    desc: 'What UCC-1 financing statements actually do for legitimate business credit — separate from internet “debt discharge” myths.',
    sections: [
      { heading: 'Plain-language UCC-1', bullets: ['A UCC-1 is a public notice that a secured party claims an interest in collateral.', 'Common in equipment loans, inventory lines, and some vendor credit programs.', 'It is not a consumer credit bureau dispute tool and not a personal debt eraser.'] },
      { heading: 'When business owners encounter UCC filings', bullets: ['Vendor terms may include blanket liens on business assets.', 'LOC and equipment lenders file to perfect security interest.', 'You can search UCC indexes by state — know what is already filed against your entity.'] },
      { heading: 'UCC vs consumer credit reporting', bullets: ['UCC filings do not appear as tradelines on personal reports the same way accounts do.', 'Confusing UCC redemptions with FCRA disputes wastes months — different legal frameworks.', 'If someone sells “UCC to delete credit cards,” treat it as a compliance red flag.'] },
      { heading: 'Practical steps', bullets: ['Search your entity in state UCC index before applying for collateralized loans.', 'Release filings promptly when loans pay off — stale UCC liens delay new funding.', 'Consult business attorney for filing language — DIY UCC paperwork errors create lien disputes.'] },
      { heading: 'Disclaimer', bullets: ['Educational only; not legal advice. UCC law varies by state.'] },
    ],
  },
  {
    id: 'smart-application-timing',
    title: 'Smart Application Timing Matrix',
    desc: 'Insider calendar for credit cards, business vendors, and loans — reporting dates, inquiry decay, and score volatility windows.',
    sections: [
      { heading: 'The 45-day inquiry window myth', bullets: ['Mortgage/FHA shopping windows exist — not all inquiry dedup rules apply to credit cards.', 'Card issuers often hard-pull one bureau — spread apps to avoid triple hits same day.', 'Business vendors may pull D&B or Experian Business — separate from personal pulls.'] },
      { heading: 'Statement close vs due date', bullets: ['Balances report as of statement close for most issuers — pay before close for low utilization snapshot.', 'Paying on due date helps interest, not necessarily reported balance.', 'Insider: set autopay to $25 minimum + manual paydown 2 days before close on target cards.'] },
      { heading: 'Dispute freeze windows', bullets: ['Do not apply while disputes pending on accounts underwriters will re-pull.', '“Updated” tradelines mid-mortgage process trigger re-underwriting — finish disputes first.', 'Deleted negatives: wait one full reporting cycle before funding apps to avoid score whiplash confusion.'] },
      { heading: 'Seasonal lender behavior', bullets: ['Q4: some issuers tighten; Q1: promotional apps increase — not universal, but pattern-aware customers win.', 'Tax season: business lenders want clean 1099/deposit alignment.', 'Track your own calendar — generic “best month” posts ignore your file state.'] },
      { heading: 'Disclaimer', bullets: ['Educational only; issuer policies change without notice.'] },
    ],
  },
  {
    id: 'funding-ready-underwriting-optics',
    title: 'Funding-Ready Underwriting Optics',
    desc: 'What manual underwriters actually scan in 90 seconds — the signals 98% of applicants never optimize.',
    sections: [
      { heading: 'The 90-second manual review', bullets: ['Oldest tradeline age + AAoA — instant bucket assignment.', 'Recent inquiries count (6mo / 12mo) — appetite for new debt.', 'Utilization on revolvers — especially aggregate and single-card spikes.', 'Public records scan — tax liens, judgments, bankruptcies.'] },
      { heading: 'Identity consistency layer', bullets: ['Name variants (Jr, II, maiden names) must match across bureaus and app.', 'Address history: too many moves in 24mo flags instability for some lenders.', 'Employer / industry consistency on apps vs report — mismatches trigger fraud review.'] },
      { heading: 'Business optics', bullets: ['Website + email domain matching entity name — free Gmail only hurts tier-1 vendor apps.', 'Bank deposit pattern vs stated revenue — underwriters ask for statements when story diverges.', 'Trade line count on D&B — zero trades = startup bucket, not “established business.”'] },
      { heading: 'Optimization without deception', bullets: ['Lower utilization before close — factual, not misrepresentation.', 'Complete dispute work before apps — accurate file, not hidden negatives.', 'Document everything — optics include your ability to produce paper fast.'] },
      { heading: 'Disclaimer', bullets: ['Educational only; underwriting criteria are proprietary and change.'] },
    ],
  },
  {
    id: 'inquiry-removal-advanced',
    title: 'Advanced Inquiry Dispute Playbook',
    desc: 'Permissible purpose, CRA vs furnisher paths, and escalation when inquiries block funding — beyond basic template letters.',
    sections: [
      { heading: 'Permissible purpose in plain English', bullets: ['Hard inquiries require authorized credit pull — contract you signed or explicit consent.', 'Soft inquiries do not affect scores — do not waste dispute energy on promos you authorized.', 'Insider: some “inquiries” are data furnisher updates mislabeled — verify type before disputing.'] },
      { heading: 'CRA dispute path', bullets: ['Dispute with bureau: no recognized permissible purpose + request removal.', 'Attach identity proof; keep claim narrow — one inquiry per letter for clean tracking.', 'Track 30-day CRA clock; escalate to CFPB if boilerplate “verified” without documentation.'] },
      { heading: 'Direct furnisher path', bullets: ['Some inquiries best removed at source — lender deletes pull record.', 'Call retention / underwriting with documentation of unauthorized pull — paper trail in portal.', 'Furnisher path often faster for duplicate pulls same lender same day.'] },
      { heading: 'When inquiries are legitimate', bullets: ['If you applied, inquiry stays until natural decay (~24 months score impact, 12mo heavy).', 'Focus shifts to explanation letters for mortgage — not removal.', 'Do not fabricate fraud claims — creates legal exposure.'] },
      { heading: 'Disclaimer', bullets: ['Educational only; not legal advice.'] },
    ],
  },
  {
    id: 'collections-validation-deep-dive',
    title: 'Collections Validation Deep Dive',
    desc: 'Chain of title, FDCPA validation windows, and Metro2 collection field traps — insider collector tactics decoded.',
    sections: [
      { heading: 'Validation vs verification (different animals)', bullets: ['FDCPA validation: debt collector must prove debt within 30 days of your written request.', 'FCRA verification: bureau reinvestigates reporting accuracy — different timeline and standard.', 'Customers lose cases by mixing letters — use the right statute for the right target.'] },
      { heading: 'Chain of title requests', bullets: ['Ask for assignment history from original creditor → current collector.', 'Missing assignments weaken collection lawsuits and sometimes reporting.', 'Store every response — even “we cannot produce” is evidence for next round.'] },
      { heading: 'Metro2 collection field traps', bullets: ['Collection status codes vs balance fields — contradictions trigger reinvestigation.', 'Date of first delinquency must align across bureaus — classic deletion lever when wrong.', 'Original creditor name vs collector name mismatches — document and dispute.'] },
      { heading: 'When to escalate beyond letters', bullets: ['Summons = attorney immediately — letter strategy alone is insufficient.', 'CFPB complaint after documented bureau non-response.', 'State AG consumer division for pattern collectors — use with clean evidence only.'] },
      {
        heading: 'Validation first — never pay as default',
        bullets: [
          'Finely Cred doctrine: challenge inaccurate reporting and unvalidated debts — do not default to paying charge-offs, collections, or settlements as step one.',
          'Within 30 days of a collector’s first written communication, send a validation request (certified mail).',
          'Collector must cease collection until it validates — demand chain of assignment, signed agreement, itemization.',
          'If validation is insufficient, escalate with affidavit of dispute and CFPB/state AG pattern documentation.',
          'Avoid settling for less as step one, pay-for-delete without written contract, or paying charge-offs without field-level dispute work.',
        ],
      },
      {
        heading: 'Affidavits & court response system',
        bullets: [
          'Affidavit of dispute: sworn statement that you dispute the debt and lack knowledge of a valid contract.',
          'Supports answer/motion when plaintiff cannot produce chain of title or signed agreement.',
          'If a summons arrives before validation mail: calendar the response deadline immediately.',
          'File answer + affidavit; assert FDCPA validation was never provided if applicable.',
          'Challenge proper service — defective service may void judgment. Never ignore court mail — consult licensed attorney same week.',
          'UCC §3-308 — party enforcing instrument bears burden of proof; debt buyers often lack original note and assignment chain.',
        ],
      },
      { heading: 'Disclaimer', bullets: ['Educational only; consult attorney for litigation or summons.'] },
    ],
  },
  {
    id: 'metro2-k-segment-field-guide',
    title: 'Metro2 K-Segment Field Guide',
    desc: 'Special comments, narrative codes, and K-segment traps — the Metro2 layer almost no consumer dispute course teaches.',
    sections: [
      { heading: 'What K-segments carry', bullets: ['Narrative remarks: “closed by consumer,” “dispute resolved,” “natural disaster.”', 'Special comment codes that override or contradict status fields.', 'Compliance condition codes tied to bankruptcy or forbearance programs.'] },
      { heading: 'High-ROI contradiction patterns', bullets: ['“Paid charge-off” remark with non-zero past due balance.', '“Account transferred” without documented sale chain.', '“Dispute resolved — consumer disagrees” while negative data remains unchanged.'] },
      { heading: 'Screenshot discipline', bullets: ['Crop the remark field + conflicting status on one exhibit.', 'Capture the same account on all three bureaus same day — drift is evidence.', 'Label: [BUREAU]_[CREDITOR]_KSEG_[DATE].png in Documents vault.'] },
      { heading: 'One-claim dispute scaffold', bullets: ['Quote remark verbatim (Exhibit A).', 'Quote conflicting status or balance (Exhibit B).', 'Request correction or deletion — do not argue emotion.'] },
      { heading: 'Disclaimer', bullets: ['Educational only; not legal advice.'] },
    ],
  },
  {
    id: 'eoscar-acdv-decoder',
    title: 'e-OSCAR ACDV Response Decoder',
    desc: 'What “verified in 5 days” actually means — ACDV codes, furnisher auto-confirm patterns, and Round 2 method-of-verification asks.',
    sections: [
      { heading: 'ACDV in plain English', bullets: ['Your CRA dispute becomes an Automated Credit Dispute Verification packet.', 'Furnisher typically has ~5 business days to respond via e-OSCAR.', '“Verified” = furnisher affirmed Metro2 — not a field investigation at your house.'] },
      { heading: 'Response outcomes', bullets: ['Verified → Round 2: method of verification + same contradiction, new exhibit.', 'Updated → Re-screenshot all bureaus; new branch from changed fields.', 'Deleted → Archive proof; do not re-dispute the ghost.', 'No match → Fix account selectors or pursue identity/furnisher path.'] },
      { heading: 'Furnisher-direct pivot triggers', bullets: ['Two verified responses with zero field changes.', 'Ownership dispute — account not yours.', 'Duplicate tradeline after debt sale without assignment proof.'] },
      { heading: 'CFPB package contents', bullets: ['Mail log with dates.', 'CRA response copies.', 'Exhibits showing ongoing inaccuracy after “verified.”', 'Narrow ask — not generic rage.'] },
      { heading: 'Disclaimer', bullets: ['Educational only; not legal advice.'] },
    ],
  },
  {
    id: 'dofd-reaging-audit',
    title: 'DOFD & Re-Aging Audit Worksheet',
    desc: 'Date of First Delinquency forensics — 7-year reporting math, illegal date shifts, and multi-bureau mismatch letters.',
    sections: [
      { heading: 'DOFD vs other dates', bullets: ['Date Opened = origination — not DOFD.', 'DOFD anchors most 7-year negative reporting windows.', 'Date of Last Activity updates ≠ DOFD reset (despite collector claims).'] },
      { heading: 'Re-aging red flags', bullets: ['DOFD jumps forward after small collector payments.', 'Collection DOFD newer than original creditor charge-off date.', 'Balance decreases but delinquency dates refresh with no explanation.'] },
      { heading: 'Audit worksheet', bullets: ['Pull DOFD on EXP, EQF, TUC — list all three.', 'Draw timeline: opened → DOFD → charge-off → collection assignment.', 'Circle impossible orderings — those are dispute claims.'] },
      { heading: 'Dispute language (factual)', bullets: ['“Reporting dates are inconsistent across bureaus — Exhibit A/B/C.”', '“DOFD contradicts payment history grid months — Exhibit D.”', 'Request correction — avoid legal conclusions without counsel.'] },
      { heading: 'Disclaimer', bullets: ['Educational only; SOL and reporting law require professional advice for your jurisdiction.'] },
    ],
  },
  {
    id: 'fraud-alert-funding-timing',
    title: 'Fraud Alerts & Funding Timing Matrix',
    desc: 'Extended fraud alerts, credit freezes, and thaw windows — plan applications so security settings do not silently kill approvals.',
    sections: [
      { heading: 'Alert types', bullets: ['Initial fraud alert: 1 year — extra identity verification on pulls.', 'Extended fraud alert: 7 years — stricter lender contact requirements.', 'Active duty alert: 1 year — military protections.'] },
      { heading: 'Freeze vs alert', bullets: ['Freeze blocks new pulls until thawed per bureau.', 'Alert allows pulls but slows underwriting — build extra days into timeline.', 'Thaw all three bureaus 24–48 hours before mortgage or LOC pulls.'] },
      { heading: 'Application calendar', bullets: ['Week -2: Lift freezes if needed; confirm alert status.', 'Week -1: Verify name/address match on all reports.', 'Day 0: Apply with documentation ready for manual review queue.'] },
      { heading: 'OFAC false positives', bullets: ['Common names trigger sanctions screens — declines can be instant.', 'Provide ID clearance docs lender requests; allow 48–72h manual review.'] },
      { heading: 'Disclaimer', bullets: ['Educational only; not legal advice.'] },
    ],
  },
  {
    id: 'student-loan-metro2-playbook',
    title: 'Student Loan Metro2 Playbook (Free)',
    desc: 'Status codes, deferment/forbearance remarks, and servicer transfer traps — field disputes that work when generic student loan letters fail.',
    sections: [
      { heading: 'Why student loans are a different animal', bullets: ['Federal vs private servicer reporting paths differ — one template does not fit both.', 'Status codes include deferment, forbearance, default, rehabilitation — each maps to different dispute angles.', 'Transfer chains (Navient → Aidvantage, etc.) create duplicate tradeline and DOFD drift.'] },
      { heading: 'High-ROI field contradictions', bullets: ['"Current" status with default remark or collection sub-status.', 'Balance $0 with past due amount on rehab account.', 'DOFD after loan origination date without documented default event.', 'Payment grid shows late months during documented deferment period.'] },
      { heading: 'Servicer transfer audit', bullets: ['List every servicer name that ever reported the loan.', 'Request transfer history in writing before disputing deletion.', 'Dispute duplicate tradelines separately — one claim per duplicate per bureau.'] },
      { heading: 'Rehabilitation & consolidation optics', bullets: ['Rehab removes default status but history may remain — know what should change vs what legally can remain.', 'Consolidation creates new loan ID — old tradeline should show paid/ transferred, not double-counted.', 'Screenshot before and after any IDR plan change — servicers batch-update monthly.'] },
      { heading: 'Funding interaction', bullets: ['DTI calculations use reported payment — wrong payment amount blocks mortgage approval.', 'IDR $0 payment may still report a higher "scheduled" amount — verify which field underwriter reads.', 'Finish student loan disputes before mortgage tri-merge if servicer data is wrong.'] },
      { heading: 'Finely workflow', bullets: ['Upload report → tag student loan tradelines → one field conflict per letter.', 'Store servicer correspondence in Documents vault.', 'Track 30-day CRA clock in Tasks — student loan disputes often need Round 2 MOFV.'] },
      { heading: 'Disclaimer', bullets: ['Educational only; not legal or financial advice. For federal loan programs consult official servicer channels.'] },
    ],
  },
  {
    id: 'bankruptcy-rebuild-sequencer',
    title: 'Post-Bankruptcy Rebuild Sequencer',
    desc: 'Month-by-month roadmap after discharge — secured cards, inquiry budget, and dispute rules when bankruptcy remarks still report.',
    sections: [
      { heading: 'Day 1 after discharge', bullets: ['Pull tri-bureau reports — verify discharged accounts show correct status codes.', 'Do not dispute included debts as "not mine" if they were legitimately in the filing — accuracy matters.', 'Flag accounts that report active balance post-discharge — those are errors worth disputing.'] },
      { heading: 'Months 1–3 — stabilization', bullets: ['Secured card or credit-builder loan if cash-flow allows — one tradeline, perfect payment.', 'No funding apps except necessity — inquiry budget is precious post-BK.', 'Build emergency buffer before any credit product — payment history is everything now.'] },
      { heading: 'Months 4–6 — thickening file', bullets: ['Second secured product only if first reports clean.', 'Authorized user only on primaries with perfect history — avoid AU on high utilization accounts.', 'Dispute only clear post-discharge reporting errors — not emotional deletions.'] },
      { heading: 'Months 7–12 — funding prep', bullets: ['Re-pull — track score recovery curve; expect non-linear jumps when negatives age.', 'Mortgage: many overlays require 2–4 years post-discharge — know your lane before applying.', 'Auto: some captive lenders specialize post-BK — research before hard pulls.'] },
      { heading: 'Bankruptcy remark codes', bullets: ['Chapter 7 vs 13 report differently — verify compliance condition codes.', 'Discharged vs dismissed — completely different underwriting treatment.', 'Included vs reaffirmed debts — reaffirmed tradelines continue reporting as obligations.'] },
      { heading: 'Disclaimer', bullets: ['Educational only; bankruptcy law varies — consult your attorney for discharge-specific questions.'] },
    ],
  },
  {
    id: 'certified-mail-evidence-system',
    title: 'Certified Mail & Evidence System',
    desc: 'Tracking numbers, return receipts, and exhibit labeling — the mail discipline that wins disputes and survives escalations.',
    sections: [
      { heading: 'Why certified mail still matters', bullets: ['Creates third-party timestamp for when bureau or furnisher received your dispute.', 'Return receipt (green card) is Exhibit A for CFPB complaints about non-response.', 'Electronic PDF mail services work if they provide USPS tracking — save full receipt PDF.'] },
      { heading: 'Labeling system', bullets: ['Format: [YYYY-MM-DD]_[BUREAU]_R[round]_CM_[tracking#].pdf', 'Store green card scan same day — do not wait for response.', 'Photo mailroom drop-off if sending multiple letters — optional but helpful for disputes about delivery.'] },
      { heading: 'Calendar discipline', bullets: ['Day 0: mail. Day 1: tracking shows accepted.', 'Day 30–45: expect CRA response — set Task reminder day 35.', 'Day 45+: if no response, escalation template ready with tracking proof.'] },
      { heading: 'Exhibit pack for Round 2', bullets: ['Include copy of Round 1 letter + tracking + prior response.', 'Highlight bureau’s exact words: "verified as accurate" next to unchanged contradiction screenshot.', 'One binder per bureau branch — never mix EXP/EQF/TUC in one PDF packet.'] },
      { heading: 'Finely Cred integration', bullets: ['Upload receipts to Documents vault under Disputes folder.', 'Link evidence to dispute case in portal — tasks auto-remind follow-up dates.', 'Letter Studio stores sent PDF hash — compare to bureau response dates.'] },
      { heading: 'Disclaimer', bullets: ['Educational only; not legal advice.'] },
    ],
  },
  {
    id: 'round-2-method-verification',
    title: 'Round 2 Method-of-Verification Playbook',
    desc: 'When Round 1 returns "verified" in five days — the MOFV ask, furnisher pivot, and CFPB package that actually moves files.',
    sections: [
      { heading: 'What "verified" means', bullets: ['Furnisher affirmed existing Metro2 via e-OSCAR — not a field investigation at your home.', 'Five-day turnaround usually means auto-confirm, not manual review.', 'Same contradiction still on file = grounds for Round 2 with new exhibit angle.'] },
      { heading: 'Method of verification letter', bullets: ['Ask: who verified, what documents reviewed, which field deemed authoritative.', 'Quote FCRA reasonable procedure language — factual, not emotional.', 'Attach same contradiction screenshots plus Round 1 response letter.'] },
      { heading: 'When to pivot furnisher-direct', bullets: ['Two CRA "verified" responses with zero field change.', 'Ownership dispute — account not yours.', 'Collector cannot produce chain of title after validation request.'] },
      { heading: 'CFPB escalation contents', bullets: ['Timeline: mail dates, tracking, responses.', 'Side-by-side exhibits: your claim vs unchanged tradeline.', 'Specific relief: correct field X or delete tradeline.', 'Keep complaint narrow — rambling reduces investigator engagement.'] },
      { heading: 'Round 3+ discipline', bullets: ['New contradiction only — repeating Round 1 language gets ignored.', 'Never threaten illegal action — focus on documented inaccuracy.', 'Know when to stop: accurately negative debt may not delete.'] },
      { heading: 'Disclaimer', bullets: ['Educational only; not legal advice.'] },
    ],
  },
  {
    id: 'vendor-tier-matrix-free',
    title: 'Business Vendor Tier Matrix (Starter)',
    desc: 'Free tier-1 net-30 vendor sequencing — who reports where, application spacing, and Paydex-building discipline.',
    sections: [
      { heading: 'Why tiers exist', bullets: ['Tier-1 vendors report to D&B or Experian Business predictably.', 'Tier-2+ may not report — fine for supplies, useless for score building.', 'Applying to five vendors same week triggers decline patterns.'] },
      { heading: 'Entity prerequisites', bullets: ['Secretary of State active status.', 'EIN letter matches legal name.', 'Business phone on 411 / Google Business Profile.', 'Business address — know home-based restrictions.'] },
      { heading: 'Application spacing', bullets: ['Week 1: vendor A — minimum order, pay early.', 'Week 3–4: vendor B after first reports or 30 days.', 'Never stack more than 2 apps per month in starter phase.'] },
      { heading: 'Paydex optics', bullets: ['Pay before due date — 80+ Paydex target.', 'Small recurring orders beat one large spike.', 'Track reporting lag 30–45 days before expecting score movement.'] },
      { heading: 'Upgrade path', bullets: ['After 3+ reporting tradelines: business card with PG awareness.', 'LOC applications after 6+ months clean business banking.', 'See paid volume Corporate Architect + Paydex Gap books for full matrices.'] },
      { heading: 'Disclaimer', bullets: ['Educational only; vendor policies change. No guarantee of approval or reporting.'] },
    ],
  },
  {
    id: 'debt-settlement-tax-traps',
    title: 'Debt Settlement & Tax Traps Primer',
    desc: '1099-C income, settled-for-less remarks, and credit reporting after settlement — what to expect and how to document.',
    sections: [
      { heading: 'Settlement vs pay-for-delete', bullets: ['Settlement updates balance but may leave negative history — different from deletion.', 'Pay-for-delete is negotiation with collector — get terms in writing before paying.', 'Never pay without written agreement on how account will report post-payment.'] },
      { heading: '1099-C basics', bullets: ['Forgiven debt may be taxable income — consult CPA.', 'Insolvency exception may apply — documentation required.', 'Credit report may show $0 balance with charge-off history remaining.'] },
      { heading: 'Credit reporting after settlement', bullets: ['"Settled for less than full balance" remark — know it before you fund.', 'Dispute if status contradicts settlement agreement (e.g., still showing past due).', 'Wait one reporting cycle after settlement before mortgage apps if possible.'] },
      { heading: 'Scam red flags', bullets: ['Upfront fees before any work.', 'Promises to remove all negatives regardless of accuracy.', 'Advice to stop paying secured debts without plan.'] },
      { heading: 'Disclaimer', bullets: ['Educational only; not tax or legal advice.'] },
    ],
  },
  {
    id: 'mortgage-overlay-dispute-prep',
    title: 'Mortgage Overlay Dispute Prep',
    desc: 'Finish disputes before rate shopping — overlay rules, re-pull timing, and tradeline updates that trigger re-underwriting.',
    sections: [
      { heading: 'Why mortgage timing differs', bullets: ['45-day inquiry shopping window for FICO — not unlimited apps.', 'Overlays add rules beyond FICO — collections, dispute flags, AU accounts.', 'Mid-process disputes can delay closing weeks — finish before pre-approval.'] },
      { heading: 'Dispute freeze rule', bullets: ['No open disputes on tradelines that will appear on tri-merge.', 'Deleted items: wait one full cycle for scores to stabilize.', 'Document all dispute resolutions — LO may ask for letters.'] },
      { heading: 'AU and authorized user overlays', bullets: ['Some investors ignore AU for payment history; others count utilization.', 'Remove AU from high-balance cards before app if overlay requires.', 'Primary tradelines matter more — plan seasoning accordingly.'] },
      { heading: 'Checklist before pre-approval', bullets: ['Tri-merge pulled within 30 days.', 'No unexplained inquiries in 6 months.', 'Utilization staged below target on reporting dates.', 'Identity alerts lifted/thawed 48h before pull.'] },
      { heading: 'Disclaimer', bullets: ['Educational only; investor overlays vary by lender and change frequently.'] },
    ],
  },
  {
    id: 'identity-theft-block-unblock',
    title: 'Identity Theft Block & Recovery',
    desc: 'FTC identity theft report, fraud alerts, blocks, and tradeline removal workflow — step-by-step without myth-based shortcuts.',
    sections: [
      { heading: 'Start at IdentityTheft.gov', bullets: ['File FTC report — foundation for extended fraud alert and blocks.', 'Keep report number — bureaus and furnishers request it.', 'Not the same as "strawman" or UCC redemption myths — different legal framework entirely.'] },
      { heading: 'Extended fraud alert', bullets: ['7-year alert with FTC report — lenders must verify identity extra steps.', 'Plan extra days into funding timeline.', 'Renew or remove when recovery complete.'] },
      { heading: 'Block fraudulent tradelines', bullets: ['Block request with FTC report + ID — bureau must stop reporting within 4 business days.', 'Different from dispute — block is for identity theft specifically.', 'Follow up if tradeline reappears — re-block with documentation.'] },
      { heading: 'Police report when needed', bullets: ['Some furnishers require local police report for fraud accounts.', 'Keep copy in evidence vault.', 'Not required for all blocks — follow bureau checklist.'] },
      { heading: 'Disclaimer', bullets: ['Educational only; consult attorney for litigation or complex identity theft cases.'] },
    ],
  },
];
