/**
 * Haitian marketing insight bank — wow facts, myth vs fact, witty line.
 * No prices. Chat hospitality is a different file.
 */
export type HaitianInsightLine = { en: string; ht: string };

export type HaitianInsightPack = {
  id: string;
  wowEn: string;
  wowHt: string;
  mythEn: string;
  mythHt: string;
  factEn: string;
  factHt: string;
  jokeEn: string;
  jokeHt: string;
  unknowns: HaitianInsightLine[];
  nextEn: string;
  nextHt: string;
};

function pack(row: HaitianInsightPack): HaitianInsightPack {
  return row;
}

export const HT_INSIGHTS: Record<string, HaitianInsightPack> = {
  restore: pack({
    id: 'restore',
    wowEn: 'Paying a collection often does not delete it. You can pay the rumor and still live with the headline.',
    wowHt: 'Peye yon koleksyon souvan pa efase l. Ou ka peye, epi tit la rete sou dosye a.',
    mythEn: 'Myth: if I pay it, it falls off.',
    mythHt: 'Manti: si m peye, li disparèt.',
    factEn: 'Fact: paid collections can still report. The clock, the name, and the screenshot matter more than the receipt.',
    factHt: 'Verite: yon koleksyon peye ka toujou rapòte. Relè a, non an, ak foto ekran an pi enpòtan pase resi a.',
    jokeEn: 'Your credit file is a gossip column written by computers that have never met you.',
    jokeHt: 'Dosye kredi w se yon jounal tripotay òdinatè yo ekri, e yo pa janm rankontre w.',
    unknowns: [
      { en: 'The seven-year clock usually starts from the first missed payment — not the day you noticed it.', ht: 'Relè sèt ane a souvan kòmanse nan premye pèyman ou te rate — pa jou ou remake l.' },
      { en: 'A goodwill letter, a dispute, and a validation request are three different English papers.', ht: 'Yon lèt goodwill, yon diskisyon, ak yon demann validasyon se twa papye angle diferan.' },
      { en: 'The bureau is not the creditor. Equifax cannot cash your apology.', ht: 'Biwo a se pa krèdye a. Equifax pa ka kache eskiz ou.' },
      { en: 'Screenshot the bureau screen. The PDF they email you is a cousin, not the twin.', ht: 'Foto ekran biwo a. PDF yo voye nan imèl se yon kouzen, pa marasa a.' },
      { en: 'Wrong person, wrong amount, and too-old-to-stay are findings — not vibes.', ht: 'Move moun, move montan, ak twò granmoun pou rete se jwenn — pa santiman.' },
      { en: 'Opening a new card while you wait can add a plot twist nobody asked for.', ht: 'Ouvri yon nouvo kat pandan w ap tann ka ajoute yon istwa pèsonn pa mande.' },
      { en: 'Late updates can land on one bureau and not the other two. Pull all three.', ht: 'Mizajou ka rive sou yon biwo epi pa sou de lòt yo. Pran twa yo.' },
      { en: 'A closed account that still prints “open” is a finding. Circle it.', ht: 'Yon kont fèmen ki toujou ekri “open” se yon jwenn. Sèk li.' },
    ],
    nextEn: 'Upload the report. Name what is wrong. Mail the English letter.',
    nextHt: 'Voye rapò a. Nonmen sa ki pa kòrèk. Voye lèt angle a.',
  }),
  debt: pack({
    id: 'debt',
    wowEn: 'That collection letter is a clock, not a bill you have to pay before breakfast.',
    wowHt: 'Lèt koleksyon an se yon relè, se pa yon bòdwo ou dwe peye anvan manje maten.',
    mythEn: 'Myth: if I ignore the envelope, it goes away.',
    mythHt: 'Manti: si m inyore anvlòp la, li ale.',
    factEn: 'Fact: many notices start a short validation window. Keep the envelope. Date the day it arrived. Ask for proof.',
    factHt: 'Verite: anpil avi kòmanse yon fenèt validasyon kout. Kenbe anvlòp la. Date jou li rive. Mande prèv.',
    jokeEn: 'A collector letter has the confidence of a wedding invitation and the paperwork of a parking ticket.',
    jokeHt: 'Yon lèt kolektè gen konfyans yon envitasyon maryaj ak papye yon tikè pakin.',
    unknowns: [
      { en: 'You may request validation. That is English for “show me this is mine and the amount is real.”', ht: 'Ou ka mande validasyon. Sa vle di: montre m sa a se pou mwen epi montan an vre.' },
      { en: 'Debt often sells for pennies. The buyer may not have the original contract.', ht: 'Dèt souvan vann pou kèk santim. Achete a ka pa gen kontra orijinal la.' },
      { en: '“Pay to delete” is a negotiation, not a legal right stamped on the letter.', ht: '“Pay to delete” se yon negosyasyon, se pa yon dwa ki tape sou lèt la.' },
      { en: 'The mini-Miranda on the page is a warning label, not your confession.', ht: 'Mini-Miranda sou paj la se yon avètisman, se pa konfesyon ou.' },
      { en: 'A summons is court paper. A collection notice is not automatically a lawsuit.', ht: 'Yon summons se papye tribinal. Yon avi koleksyon se pa otomatikman yon pwosè.' },
      { en: 'Paying from fear the same week you opened the mail is how good people buy silence that does not last.', ht: 'Peye paske w pè nan menm semèn ou ouvri lèt la se jan moun bon achte silans ki pa dire.' },
      { en: 'Licensing, chain of title, and itemized amounts are questions — not attitude.', ht: 'Lisans, chèn tit, ak montan detaye se kesyon — pa move jan.' },
      { en: 'Keep every date. Clocks win more arguments than adjectives.', ht: 'Kenbe tout dat. Relè yo genyen plis diskisyon pase adjektif.' },
    ],
    nextEn: 'Open the collector letter. Request validation. Keep every date.',
    nextHt: 'Ouvri lèt kolektè a. Mande validasyon. Kenbe tout dat.',
  }),
  building: pack({
    id: 'building',
    wowEn: 'How much you use on the card often moves the file faster than a dramatic “I paid it all and closed it.”',
    wowHt: 'Konbyen ou itilize sou kat la souvan deplase dosye a pi vit pase “mwen peye tout epi mwen fèmen l.”',
    mythEn: 'Myth: close every card and the score blooms.',
    mythHt: 'Manti: fèmen tout kat yo epi nòt la fleuri.',
    factEn: 'Fact: closing the oldest card can shrink average age. Utilization is a snapshot, not a personality test.',
    factHt: 'Verite: fèmen pi ansyen kat la ka redwi laj mwayèn. Itilizasyon se yon foto, se pa yon tès pèsonalite.',
    jokeEn: 'Your card is not a personality. It is a percentage that likes to gossip at statement time.',
    jokeHt: 'Kat ou a se pa yon pèsonalite. Se yon pousantaj ki renmen tripotay lè deklarasyon an rive.',
    unknowns: [
      { en: 'FICO and Vantage are different math. Mortgage and auto often look at different versions.', ht: 'FICO ak Vantage se matematik diferan. Ipotèk ak oto souvan gade vèsyon diferan.' },
      { en: 'A zero reported balance is not always the flex people think it is.', ht: 'Yon balans zewo rapòte se pa toujou flèks moun yo panse.' },
      { en: 'Authorized user is someone else’s history sitting in your guest chair.', ht: 'Authorized user se istwa yon lòt moun k ap chita nan chèz envite ou.' },
      { en: 'On-time trade beats a promised score. Nobody can sell you a number like a lottery ticket.', ht: 'Komès alè bat yon nòt yo pwomèt. Pèsonn pa ka vann ou yon nimewo tankou yon tikè lotri.' },
      { en: 'Statement date is the photo. Payday is the outfit. They are not the same morning.', ht: 'Dat deklarasyon an se foto a. Jou pèyman an se rad la. Yo pa menm maten.' },
      { en: 'A thin file is not a moral failure. It is a short story. Add pages on purpose.', ht: 'Yon dosye mens se pa yon peche. Se yon istwa kout. Ajoute paj espre.' },
      { en: 'Hard inquiries cluster. Applying everywhere in one weekend is a group chat the bureaus can see.', ht: 'Hard inquiry yo gwoupe. Aplike tout kote nan yon wikenn se yon gwoup chat biwo yo ka wè.' },
      { en: 'Installment and revolving mix. One loud card can shout over three quiet loans.', ht: 'Melanj installment ak revolving. Yon kat fò ka rele pi wo pase twa prè trankil.' },
    ],
    nextEn: 'Add on-time trade. Watch how much you use. Do not chase a promised score.',
    nextHt: 'Mete yon komès ki peye alè. Gade konbyen ou itilize. Pa kouri dèyè yon nòt yo pwomèt.',
  }),
  business: pack({
    id: 'business',
    wowEn: 'The company file lives on the EIN. Your Social Security number is not a secret business score hiding in a trench coat.',
    wowHt: 'Dosye konpayi an viv sou EIN. Nimewo sosyal ou se pa yon nòt biznis kache nan yon rad.',
    mythEn: 'Myth: if my personal file is messy, the company cannot have a file.',
    mythHt: 'Manti: si dosye pèsonèl mwen sal, konpayi an pa ka gen dosye.',
    factEn: 'Fact: entity, matching listings, and vendors that actually report come before a company ask.',
    factHt: 'Verite: konpayi, lis ki matche, ak machann ki vrèman rapòte vin anvan yon demann konpayi.',
    jokeEn: 'PAYDEX is not FICO in a suit. It is closer to “how many days did you take to pay the vendor.”',
    jokeHt: 'PAYDEX se pa FICO nan kostim. Li pi pre “konbyen jou ou te pran pou peye machann nan.”',
    unknowns: [
      { en: 'A vendor that does not report is a nice invoice, not a tradeline.', ht: 'Yon machann ki pa rapòte se yon bòdwo janti, se pa yon tradeline.' },
      { en: 'Name, address, phone, and SOS listing should tell the same story.', ht: 'Non, adrès, telefòn, ak lis SOS ta dwe rakonte menm istwa a.' },
      { en: 'DUNS and bureau files are not automatic. You open them on purpose.', ht: 'DUNS ak dosye biwo yo pa otomatik. Ou ouvri yo espre.' },
      { en: 'Net-30 is a behavior, not a personality brand.', ht: 'Net-30 se yon konpòtman, se pa yon mak pèsonalite.' },
      { en: 'Funding depends on approval. Charm is not underwriting.', ht: 'Lajan depann si yo apwouve w. Charm se pa apwobasyon.' },
      { en: 'Using the owner SSN as the company file is how two lives get tangled.', ht: 'Sèvi ak nimewo sosyal pwopriyetè a kòm dosye konpayi se jan de lavi mele.' },
      { en: 'A domain email that matches the listing beats a free inbox named after a hobby.', ht: 'Yon imèl domèn ki matche lis la bat yon bwat gratis ki pote non yon pasyon.' },
      { en: 'Tier vendors in a ladder. Do not collect five store cards in one afternoon for sport.', ht: 'Mete machann yo sou yon nechèl. Pa ranmase senk kat magazen nan yon apremidi pou plezi.' },
    ],
    nextEn: 'Entity first. Vendors that report. Then a company ask — not the owner SSN.',
    nextHt: 'Dabò konpayi an. Machann ki rapòte. Apre sa, yon demann sou EIN — pa nimewo sosyal pwopriyetè a.',
  }),
  chex: pack({
    id: 'chex',
    wowEn: 'ChexSystems is not Equifax. It is the banking-report cousin that remembers bounced chapters.',
    wowHt: 'ChexSystems se pa Equifax. Se kouzen rapò bank ki sonje chapit ki tounen.',
    mythEn: 'Myth: if my credit file is clean, I can open any checking account.',
    mythHt: 'Manti: si dosye kredi mwen pwòp, mwen ka ouvri nenpòt kont chèk.',
    factEn: 'Fact: banks may look at a different report. Cleanup there is a different English desk.',
    factHt: 'Verite: bank yo ka gade yon lòt rapò. Netwayaj la se yon lòt biwo angle.',
    jokeEn: 'Your credit score can be dressed for Sunday while ChexSystems still remembers Tuesday.',
    jokeHt: 'Nòt kredi w ka abiye pou dimanch pandan ChexSystems toujou sonje madi.',
    unknowns: [
      { en: 'Overdrafts and unpaid account closures can live here, not on Experian.', ht: 'Overdraft ak kont yo fèmen san peye ka viv isit la, pa sou Experian.' },
      { en: 'Ask which report the bank is using before you argue with the wrong cousin.', ht: 'Mande ki rapò bank la ap itilize anvan w diskite ak move kouzen an.' },
      { en: 'A second-chance checking product is a product, not a moral lecture.', ht: 'Yon kont chèk dezyèm chans se yon pwodui, se pa yon leson moral.' },
      { en: 'IDs and addresses must match the bank’s story too.', ht: 'ID ak adrès dwe matche istwa bank la tou.' },
      { en: 'This is not a FICO. Do not treat it like one.', ht: 'Sa a se pa yon FICO. Pa trete l tankou youn.' },
      { en: 'Keep the denial letter. It names the report.', ht: 'Kenbe lèt refi a. Li nonmen rapò a.' },
    ],
    nextEn: 'Name the banking report. Then clean what it actually shows.',
    nextHt: 'Nonmen rapò bank la. Apre sa, netwaye sa l montre vreman.',
  }),
  privacy: pack({
    id: 'privacy',
    wowEn: 'A credit freeze is a lock on new accounts. It is not a disappearing act for the file you already have.',
    wowHt: 'Yon freeze kredi se yon kadna sou nouvo kont. Se pa yon magi pou fè dosye ou deja genyen disparèt.',
    mythEn: 'Myth: freeze it and the collections vanish.',
    mythHt: 'Manti: freeze li epi koleksyon yo disparèt.',
    factEn: 'Fact: freeze, alerts, and PINs are English bureau words. Unlock only when you are the one applying.',
    factHt: 'Verite: freeze, alèt, ak PIN se mo biwo angle. Debloke sèlman lè se ou k ap aplike.',
    jokeEn: 'A freeze is a deadbolt. It does not repaint the living room.',
    jokeHt: 'Yon freeze se yon sere-bar. Li pa pentire salon an.',
    unknowns: [
      { en: 'You freeze each bureau separately. They do not share a group chat.', ht: 'Ou freeze chak biwo apa. Yo pa gen yon gwoup chat.' },
      { en: 'A fraud alert is not the same as a freeze.', ht: 'Yon alèt fwod se pa menm ak yon freeze.' },
      { en: 'PINs get lost in drawers. Write yours where you can find it on a Tuesday.', ht: 'PIN yo pèdi nan tiwa. Ekri pa w kote w ka jwenn li yon madi.' },
      { en: 'Identity theft and a messy file are cousins. Treat the lock and the findings as two jobs.', ht: 'Vòl idantite ak yon dosye sal se kouzen. Trete kadna a ak jwenn yo kòm de travay.' },
      { en: 'Thaw before you apply. Lenders cannot applaud a locked door.', ht: 'Debloke anvan w aplike. Prete yo pa ka aplodi yon pòt fèmen.' },
      { en: 'AnnualCreditReport.com is the federal door. A score app is a gift shop.', ht: 'AnnualCreditReport.com se pòt federal la. Yon app nòt se yon boutik kado.' },
    ],
    nextEn: 'Freeze, set alerts, keep the PINs. Then come back to the findings.',
    nextHt: 'Freeze, mete alèt, kenbe PIN yo. Apre sa, tounen sou jwenn yo.',
  }),
  tradelines: pack({
    id: 'tradelines',
    wowEn: 'A tradeline is a line on a file. Timing matters. It is not a magic stamp that rewrites your whole plot.',
    wowHt: 'Yon tradeline se yon liy sou yon dosye. Tan an konte. Se pa yon magi ki reekri tout istwa a.',
    mythEn: 'Myth: buy a line, buy a number.',
    mythHt: 'Manti: achte yon liy, achte yon nimewo.',
    factEn: 'Fact: authorized-user lines can help or backfire. Seasoning, utilization, and whose name is primary all move.',
    factHt: 'Verite: liy authorized-user ka ede oswa fè mal. Seasoning, itilizasyon, ak non prensipal la tout deplase.',
    jokeEn: 'Sitting as an authorized user is like being on someone else’s family plan. Read the fine print of the household.',
    jokeHt: 'Chita kòm authorized user se tankou sou plan fanmi yon lòt moun. Li ti lèt kay la.',
    unknowns: [
      { en: 'Primary versus authorized user is not a fashion label. It changes whose history you borrowed.', ht: 'Primary kont authorized user se pa yon etikèt mòd. Li chanje istwa ou prete.' },
      { en: 'A high-limit card with high use can arrive as a loud percentage, not a trophy.', ht: 'Yon kat gwo limit ak gwo itilizasyon ka rive kòm yon pousantaj fò, pa yon twòfe.' },
      { en: 'Lenders can see seasoning. A line that appeared last Tuesday looks like last Tuesday.', ht: 'Prete yo ka wè seasoning. Yon liy ki parèt madi pase a sanble madi pase a.' },
      { en: 'No promised score. If someone sells you a number, they are selling a mood.', ht: 'Pa gen nòt yo pwomèt. Si yon moun vann ou yon nimewo, yo ap vann yon atitid.' },
      { en: 'Your own on-time revolving still has to exist. A guest chair is not a house.', ht: 'Pwòp revolving alè ou a toujou dwe egziste. Yon chèz envite se pa yon kay.' },
      { en: 'Risk includes the primary’s future. Their late payment can visit you.', ht: 'Risk gen ladan lavni moun prensipal la. Retar yo ka vizite w.' },
    ],
    nextEn: 'Understand the line, the timing, and the risk. Then decide with eyes open.',
    nextHt: 'Konprann liy la, tan an, ak risk la. Apre sa, deside ak je ouvè.',
  }),
  court: pack({
    id: 'court',
    wowEn: 'A summons is court paper. It has a clock. It is not a strongly worded collection email in nicer font.',
    wowHt: 'Yon summons se papye tribinal. Li gen yon relè. Se pa yon imèl koleksyon ak yon pi bèl font.',
    mythEn: 'Myth: if I do not answer, they will forget.',
    mythHt: 'Manti: si m pa reponn, yo pral bliye.',
    factEn: 'Fact: unanswered court paper can become a default. Deadlines are the plot.',
    factHt: 'Verite: papye tribinal san repons ka tounen yon default. Delè yo se istwa a.',
    jokeEn: 'Court captions are allergic to vibes. They want dates, names, and a response.',
    jokeHt: 'Caption tribinal yo pa renmen vibes. Yo vle dat, non, ak yon repons.',
    unknowns: [
      { en: 'Read the caption: court, parties, case number. Those English words travel.', ht: 'Li caption nan: tribinal, pati, nimewo dosye. Mo angle sa yo vwayaje.' },
      { en: 'An answer is a filing. A phone call to the collector is not an answer.', ht: 'Yon answer se yon depo. Yon apèl telefòn bay kolektè a se pa yon answer.' },
      { en: 'This desk is educational. It is not a law firm and it is not a promise.', ht: 'Biwo sa a se edikasyon. Se pa yon kabinè avoka epi se pa yon pwomès.' },
      { en: 'Keep the envelope and the stamp date. Service starts clocks.', ht: 'Kenbe anvlòp la ak dat so a. Sèvis kòmanse relè.' },
      { en: 'A collection letter last month and a summons this month are different objects.', ht: 'Yon lèt koleksyon mwa pase a ak yon summons mwa sa a se objè diferan.' },
      { en: 'If you need counsel, say that out loud. We will not pretend we are the court.', ht: 'Si w bezwen avoka, di l byen fò. Nou p ap pretann nou se tribinal la.' },
    ],
    nextEn: 'Read the caption. Keep the dates. Book a session if the paper is court paper.',
    nextHt: 'Li caption nan. Kenbe dat yo. Rezève yon sesyon si papye a se papye tribinal.',
  }),
  foreclosure: pack({
    id: 'foreclosure',
    wowEn: 'A foreclosure notice is a clock on a house. It is not a suggestion to “call when you can.”',
    wowHt: 'Yon avi sezi kay se yon relè sou yon kay. Se pa yon sijesyon pou “rele lè w kapab.”',
    mythEn: 'Myth: if I send a dispute to Equifax, the sale pauses.',
    mythHt: 'Manti: si m voye yon diskisyon bay Equifax, vant lan kanpe.',
    factEn: 'Fact: bureau letters and foreclosure clocks are different desks. Read the notice that arrived.',
    factHt: 'Verite: lèt biwo ak relè sezi kay se biwo diferan. Li avi ki rive a.',
    jokeEn: 'The county does not accept good intentions as certified mail.',
    jokeHt: 'Konte a pa aksepte bon entansyon kòm lèt sètifye.',
    unknowns: [
      { en: 'Notice of default, sale date, and reinstatement are English words with calendars.', ht: 'Notice of default, dat vant, ak reinstatement se mo angle ki gen kalandriye.' },
      { en: 'Mortgage servicer and investor are not always the same shop.', ht: 'Servicer ipotèk ak envestisè a pa toujou menm magazen.' },
      { en: 'Loss-mitigation packets have their own clocks. Incomplete packets stall people, not the sale.', ht: 'Paket loss-mitigation gen pwòp relè yo. Paket enkonplè kanpe moun, pa vant lan.' },
      { en: 'This is not legal advice. If counsel is needed, say so early.', ht: 'Sa a pa konsèy legal. Si w bezwen avoka, di l bonè.' },
      { en: 'Keep every envelope. Sale dates do not care that the letter hid under catalogs.', ht: 'Kenbe tout anvlòp. Dat vant yo pa pran swen lèt la te kache anba katalòg.' },
      { en: 'Credit reporting of the mortgage is a separate story from the foreclosure clock.', ht: 'Rapò kredi ipotèk la se yon lòt istwa pase relè sezi kay la.' },
    ],
    nextEn: 'Read the notice. Name the clock. Book a session the same week.',
    nextHt: 'Li avi a. Nonmen relè a. Rezève yon sesyon nan menm semèn nan.',
  }),
  repo: pack({
    id: 'repo',
    wowEn: 'Auto and insurance items often carry a short window. The VIN does not wait for family meeting night.',
    wowHt: 'Atik oto ak asirans souvan gen yon fenèt kout. VIN nan pa tann nwit reyinyon fanmi.',
    mythEn: 'Myth: if they have not picked up the car, I still have months.',
    mythHt: 'Manti: si yo poko pran machin nan, mwen toujou gen plizyè mwa.',
    factEn: 'Fact: notices, insurance lapses, and deficiency balances have their own English clocks.',
    factHt: 'Verite: avi, asirans ki ekspire, ak balans deficiency gen pwòp relè angle yo.',
    jokeEn: 'A car notice is not shy. It just assumes you check the mailbox more than the group chat.',
    jokeHt: 'Yon avi oto pa timid. Li jis sipoze ou tcheke bwat la plis pase gwoup chat la.',
    unknowns: [
      { en: 'Right to cure and redemption are English phrases with calendars, not moods.', ht: 'Right to cure ak redemption se fraz angle ki gen kalandriye, pa atitid.' },
      { en: 'A deficiency after sale can still hunt the file.', ht: 'Yon deficiency apre vant ka toujou chase dosye a.' },
      { en: 'Insurance lapses can trigger force-placed policies and new numbers.', ht: 'Asirans ki ekspire ka deklanche polis force-placed ak nouvo nimewo.' },
      { en: 'Photograph every page. “I think it said Friday” is not a date.', ht: 'Foto chak paj. “Mwen panse li te di vandredi” se pa yon dat.' },
      { en: 'Keep the envelope. Service and postmark start arguments.', ht: 'Kenbe anvlòp la. Sèvis ak so lapòs kòmanse diskisyon.' },
      { en: 'This is educational. Not legal advice. Results vary.', ht: 'Sa a se edikasyon. Pa konsèy legal. Rezilta yo varye.' },
    ],
    nextEn: 'Photograph the notice. Name the VIN clock. Pale Kreyòl if you need the English line read.',
    nextHt: 'Foto avi a. Nonmen relè VIN nan. Pale Kreyòl si w bezwen nou li liy angle a.',
  }),
  bankruptcy: pack({
    id: 'bankruptcy',
    wowEn: 'Bankruptcy is a court chapter, not a bureau button. The file and the case are two rooms.',
    wowHt: 'Bankruptcy se yon chapit tribinal, se pa yon bouton biwo. Dosye a ak ka a se de chanm.',
    mythEn: 'Myth: filing deletes the gossip overnight.',
    mythHt: 'Manti: depo a efase tripotay la lannwit.',
    factEn: 'Fact: reporting after a case follows its own English rules. Dates and case numbers matter.',
    factHt: 'Verite: rapò apre yon ka swiv pwòp règ angle li. Dat ak nimewo ka konte.',
    jokeEn: 'Chapter numbers are not hotel floors. Read which one you are actually in.',
    jokeHt: 'Nimewo chapit yo se pa etaj otèl. Li kiyès ou ye vreman.',
    unknowns: [
      { en: '7 and 13 are different plots. Do not mix the homework.', ht: '7 ak 13 se istwa diferan. Pa melanje devwa a.' },
      { en: 'A discharged debt can still print until the bureaus catch the chapter.', ht: 'Yon dèt discharged ka toujou ekri jiskaske biwo yo pran chapit la.' },
      { en: 'This desk teaches the English on the page. It is not counsel.', ht: 'Biwo sa a anseye angle ki sou paj la. Se pa konsèy legal.' },
      { en: 'Keep the discharge and the docket. Screenshots of a score app are not the case.', ht: 'Kenbe discharge a ak docket la. Foto yon app nòt se pa ka a.' },
      { en: 'Rebuilding after a chapter is a new story. Do not chase a promised score.', ht: 'Rebati apre yon chapit se yon nouvo istwa. Pa kouri dèyè yon nòt yo pwomèt.' },
      { en: 'If you need an attorney, say that. We will not role-play the trustee.', ht: 'Si w bezwen avoka, di l. Nou p ap jwe wòl trustee a.' },
    ],
    nextEn: 'Keep the case papers. Read what the file still prints. Book a session if the two rooms disagree.',
    nextHt: 'Kenbe papye ka a. Li sa dosye a toujou ekri. Rezève yon sesyon si de chanm yo pa dakò.',
  }),
  helper: pack({
    id: 'helper',
    wowEn: 'You’re allowed to sit there. Don’t take the phone. She has to understand the English sentence — not watch you tap.',
    wowHt: 'Ou gen dwa chita la. Pa pran telefòn nan. Se li ki dwe konprann fraz angle a — se pa gade ou peze.',
    mythEn: 'Myth: I should take the phone and finish it for them.',
    mythHt: 'Manti: mwen ta dwe pran telefòn nan epi fini l pou yo.',
    factEn: 'Fact: she holds her phone. You point at one English sentence. One letter or one screen. Then you both stop for the day.',
    factHt: 'Verite: se li ki kenbe telefòn li. Ou montre yon fraz angle. Yon lèt oswa yon ekran. Apre sa nou de kanpe.',
    jokeEn: 'Helping is not hijacking. Grandparents can smell a stolen phone from the kitchen.',
    jokeHt: 'Ede se pa vòlè. Granmoun yo ka pran sant yon telefòn yo vòlè depi nan kwizin nan.',
    unknowns: [
      { en: 'Read the English artifact out loud. Then the Kreyòl meaning. Then the English words again.', ht: 'Li atifak angle a byen fò. Apre sa siyifikasyon kreyòl. Apre sa mo angle yo ankò.' },
      { en: 'Do not promise a score. Love is not a FICO.', ht: 'Pa pwomèt yon nòt. Lanmou se pa yon FICO.' },
      { en: 'One letter, one desk, one day. A six-tab browser is how weekends go missing.', ht: 'Yon lèt, yon biwo, yon jou. Yon navigatè sis ongèl se jan wikenn yo disparèt.' },
      { en: 'Pale Kreyòl is an invitation, not an order to sit down.', ht: 'Pale Kreyòl se yon envitasyon, se pa yon lòd pou chita.' },
      { en: 'Keep their envelope. Your notes app is not the legal file.', ht: 'Kenbe anvlòp yo. App nòt ou a se pa dosye legal la.' },
      { en: 'If court paper arrived, stop DIY bravado. Book a session.', ht: 'Si papye tribinal rive, kanpe kouraj DIY. Rezève yon sesyon.' },
    ],
    nextEn: 'Sit with them. Let them hold the phone. Point at one English sentence. Then stop for the day.',
    nextHt: 'Rete bò kote yo. Li liy la. Yon pwochen etap. Apre sa, kanpe.',
  }),
  church: pack({
    id: 'church',
    wowEn: 'Most people never learn that a credit file is a written story — and the story can be wrong without anyone meaning harm.',
    wowHt: 'Pifò moun pa janm aprann dosye kredi se yon istwa ekri — epi istwa a ka mal san pèsonn pa vle fè mal.',
    mythEn: 'Myth: credit is a secret score only banks understand.',
    mythHt: 'Manti: kredi se yon nòt sekrè sèlman bank yo konprann.',
    factEn: 'Fact: it is lines on a page. Names, dates, amounts. You can sit and read them in two voices.',
    factHt: 'Verite: se liy sou yon paj. Non, dat, montan. Ou ka chita li yo nan de vwa.',
    jokeEn: 'We will not sell you a miracle in the parking lot. We will read the English line.',
    jokeHt: 'Nou p ap vann ou yon mirak nan pakin nan. Nou pral li liy angle a.',
    unknowns: [
      { en: 'A collection is a rumor with a phone number.', ht: 'Yon koleksyon se yon tripotay ki gen yon nimewo telefòn.' },
      { en: 'Bureaus speak English. That is why the letter stays English.', ht: 'Biwo yo pale angle. Se poutèt sa lèt la rete angle.' },
      { en: 'Kreyòl makes the meaning clear. It does not replace the artifact.', ht: 'Kreyòl fè siyifikasyon an klè. Li pa ranplase atifak la.' },
      { en: 'Miami, Brooklyn, Boston, Houston, Atlanta, DC, Chicago, Philly, Jacksonville, New Jersey.', ht: 'Miami, Brooklyn, Boston, Houston, Atlanta, DC, Chicago, Philly, Jacksonville, New Jersey.' },
      { en: 'Scan when you are ready. Nobody is grading your accent.', ht: 'Skan lè w pare. Pèsonn pa ba w nòt sou aksan ou.' },
      { en: 'Results vary. Not legal advice. If you need funding, that depends on approval.', ht: 'Rezilta yo varye. Sa a pa konsèy legal. Si w bezwen lajen, sa depann si yo apwouve w.' },
    ],
    nextEn: 'Pale Kreyòl when you are ready. Bring the letter that arrived.',
    nextHt: 'Pale Kreyòl lè w pare. Pote lèt ki rive a.',
  }),
  welcome: pack({
    id: 'welcome',
    wowEn: 'You do not need a finance degree to sit with a bureau page. You need the English line and someone who will not rush you.',
    wowHt: 'Ou pa bezwen yon diplòm finans pou chita ak yon paj biwo. Ou bezwen liy angle a ak yon moun ki p ap prese w.',
    mythEn: 'Myth: this is only for people who already know the words.',
    mythHt: 'Manti: sa a se sèlman pou moun ki deja konnen mo yo.',
    factEn: 'Fact: we name the English, say what it means in Kreyòl, then you see those words again.',
    factHt: 'Verite: nou nonmen angle a, di sa l vle di an kreyòl, epi ou wè mo sa yo ankò.',
    jokeEn: 'Credit English is a dialect. Nobody is born fluent in “30-day validation.”',
    jokeHt: 'Angle kredi se yon dyalèk. Pèsonn pa fèt pale “30-day validation” flwans.',
    unknowns: [
      { en: 'Four desks: restore, debt, building, business. Pick one for the day.', ht: 'Kat biwo: restore, dèt, building, biznis. Chwazi youn pou jounen an.' },
      { en: 'A score app is entertainment. The bureau screen is the document.', ht: 'Yon app nòt se amizman. Ekran biwo a se dokiman an.' },
      { en: 'Partners are people in the portal. Guests are people in chat until they join.', ht: 'Patnè se moun nan pòtal la. Envite se moun nan chat jiskaske yo rantre.' },
      { en: 'We do not post prices on the flyer. If you ask, we will talk.', ht: 'Nou pa afiche pri sou feyè a. Si w mande, n ap pale.' },
      { en: 'Pale Kreyòl is the door. Book a session if the stack is thick.', ht: 'Pale Kreyòl se pòt la. Rezève yon sesyon si pil la epè.' },
      { en: 'Results vary. Not legal advice.', ht: 'Rezilta yo varye. Sa a pa konsèy legal.' },
    ],
    nextEn: 'Open Haitian community. Pale Kreyòl when you are ready.',
    nextHt: 'Ouvri Haitian community. Pale Kreyòl lè w pare.',
  }),
  file: pack({
    id: 'file',
    wowEn: 'There is no single “the credit report.” There are three bureaus that gossip at different speeds.',
    wowHt: 'Pa gen yon sèl “rapò kredi a.” Gen twa biwo ki fè tripotay nan vitès diferan.',
    mythEn: 'Myth: one app screenshot is the whole truth.',
    mythHt: 'Manti: yon foto app se tout verite a.',
    factEn: 'Fact: Equifax, Experian, and TransUnion can disagree on the same Tuesday.',
    factHt: 'Verite: Equifax, Experian, ak TransUnion ka pa dakò menm madi a.',
    jokeEn: 'Think of them as three cousins who do not share a group chat.',
    jokeHt: 'Panse yo tankou twa kouzen ki pa gen menm gwoup chat.',
    unknowns: [
      { en: 'Pull all three before you write a letter to one.', ht: 'Pran twa yo anvan w ekri yon lèt bay youn.' },
      { en: 'Personal information errors (name, address, employer) are findings too.', ht: 'Erè enfòmasyon pèsonèl (non, adrès, patwon) se jwenn tou.' },
      { en: 'Inquiries, collections, and revolving are different rooms on the same floor.', ht: 'Inquiry, koleksyon, ak revolving se chanm diferan sou menm etaj la.' },
      { en: 'A “deleted” item can reappear if a furnisher sends it again.', ht: 'Yon atik “efase” ka tounen si yon furnisher voye l ankò.' },
      { en: 'Hold the gain. Do not celebrate by opening three cards.', ht: 'Kenbe sa ki klè. Pa selebre lè w ouvri twa kat.' },
      { en: 'The English line stays English. We will sit with the meaning.', ht: 'Liy angle a rete angle. Nou pral chita ak siyifikasyon an.' },
    ],
    nextEn: 'Photograph every bureau screen. Then name what is wrong.',
    nextHt: 'Foto chak ekran biwo. Apre sa, nonmen sa ki pa kòrèk.',
  }),
  visit: pack({
    id: 'visit',
    wowEn: 'A good visit is one English line, one meaning, one next step. Then you stop. That is not laziness. That is how files get less messy.',
    wowHt: 'Yon bon vizit se yon liy angle, yon siyifikasyon, yon pwochen etap. Apre sa ou kanpe. Se pa parese. Se konsa dosye yo vin mwens sal.',
    mythEn: 'Myth: we should finish the whole file this Saturday.',
    mythHt: 'Manti: nou ta dwe fini tout dosye a samdi sa a.',
    factEn: 'Fact: rushed weekends create the wrong letter to the wrong cousin.',
    factHt: 'Verite: wikenn prese kreye move lèt bay move kouzen.',
    jokeEn: 'Credit is not a binge show. It is a series. Stop after episode one.',
    jokeHt: 'Kredi se pa yon seri w gade tout lannwit. Se yon seri. Kanpe apre premye epizòd.',
    unknowns: [
      { en: '1 Read the artifact. 2 Pick one desk. 3 Stop for the day.', ht: '1 Li atifak la. 2 Chwazi yon biwo. 3 Kanpe pou jounen an.' },
      { en: 'We never promise a score. We never pretend to be the court.', ht: 'Nou pa janm pwomèt yon nòt. Nou pa janm pretann nou se tribinal la.' },
      { en: 'Bring the envelope. Screenshots without dates are modern folklore.', ht: 'Pote anvlòp la. Foto san dat se folklò modèn.' },
      { en: 'If the paper is a summons, the visit changes shape.', ht: 'Si papye a se yon summons, vizit la chanje fòm.' },
      { en: 'Pale Kreyòl when you want the meaning. English stays on the page.', ht: 'Pale Kreyòl lè w vle siyifikasyon an. Angle rete sou paj la.' },
      { en: 'Results vary. Not legal advice.', ht: 'Rezilta yo varye. Sa a pa konsèy legal.' },
    ],
    nextEn: 'Read. Pick. Stop. Come back next week if you need another episode.',
    nextHt: 'Li. Chwazi. Kanpe. Tounen semèn pwochèn si w bezwen yon lòt epizòd.',
  }),
  bundles: pack({
    id: 'bundles',
    wowEn: 'Restore plus debt is two rooms with a door between them — not a smoothie.',
    wowHt: 'Restore plis dèt se de chanm ak yon pòt nan mitan — se pa yon smoothie.',
    mythEn: 'Myth: one letter fixes the file and the collector.',
    mythHt: 'Manti: yon sèl lèt ranje dosye a ak kolektè a.',
    factEn: 'Fact: bureau findings and collector clocks can run in the same month. They still need different English papers.',
    factHt: 'Verite: jwenn biwo ak relè kolektè ka kouri nan menm mwa. Yo toujou bezwen papye angle diferan.',
    jokeEn: 'A bundle is a playlist, not a blender. Keep the songs in order.',
    jokeHt: 'Yon bundle se yon playlist, se pa yon blender. Kenbe chante yo nan lòd.',
    unknowns: [
      { en: 'Name the finding on the bureau first if the screen is wrong.', ht: 'Nonmen jwenn nan sou biwo a anvan si ekran an mal.' },
      { en: 'Ask the collector for proof if the envelope is a demand.', ht: 'Mande kolektè a prèv si anvlòp la se yon demann.' },
      { en: 'Do not pay from panic on day one of both jobs.', ht: 'Pa peye nan panik jou youn nan tou de travay yo.' },
      { en: 'One next step per sitting. Two rooms, still one chair.', ht: 'Yon pwochen etap pou chak chita. De chanm, toujou yon chèz.' },
      { en: 'No promised score. No legal advice.', ht: 'Pa gen nòt yo pwomèt. Pa gen konsèy legal.' },
      { en: 'If court paper is in the stack, that room goes first.', ht: 'Si papye tribinal nan pil la, chanm sa a ale anvan.' },
    ],
    nextEn: 'Open both rooms. Walk through one door today.',
    nextHt: 'Ouvri tou de chanm yo. Pase yon pòt jodi a.',
  }),
  maintenance: pack({
    id: 'maintenance',
    wowEn: 'After a round of letters, the file can drift. Holding the gain is a calendar, not a victory lap.',
    wowHt: 'Apre yon wonn lèt, dosye a ka derive. Kenbe sa ki klè se yon kalandriye, se pa yon tour viktwa.',
    mythEn: 'Myth: once it is clean, it stays clean forever.',
    mythHt: 'Manti: le li pwòp, li rete pwòp pou tout tan.',
    factEn: 'Fact: furnishers can re-report. New cards can shout. Utilization can wander.',
    factHt: 'Verite: furnisher yo ka rapòte ankò. Nouvo kat ka rele. Itilizasyon ka pèdi wout.',
    jokeEn: 'A credit file is a garden. Nobody applauds you for watering it, until they do.',
    jokeHt: 'Yon dosye kredi se yon jaden. Pèsonn pa aplodi w paske w wouze l, jiskaske yo fè l.',
    unknowns: [
      { en: 'Re-pull on a schedule. Do not wait for a denial letter to be your alarm.', ht: 'Re-pran sou yon orè. Pa tann yon lèt refi kòm alam ou.' },
      { en: 'Watch card use after the win. Quiet percentages stay quiet on purpose.', ht: 'Gade itilizasyon kat apre viktwa a. Pousantaj trankil rete trankil espre.' },
      { en: 'Do not open a stack of cards to celebrate.', ht: 'Pa ouvri yon pil kat pou selebre.' },
      { en: 'Keep the screenshots from the round that worked.', ht: 'Kenbe foto ekran wonn ki te mache a.' },
      { en: 'Alerts exist. Use them like smoke detectors, not like jewelry.', ht: 'Alèt egziste. Sèvi ak yo tankou detektè lafimen, pa tankou bijou.' },
      { en: 'Results vary. The calendar is the product.', ht: 'Rezilta yo varye. Kalandriye a se pwodui a.' },
    ],
    nextEn: 'Put the next pull on the calendar. Hold the gain.',
    nextHt: 'Mete pwochèn pran an sou kalandriye a. Kenbe sa ki klè.',
  }),
  session: pack({
    id: 'session',
    wowEn: 'A session is a sitting, not a TED talk. Bring the paper. Leave with one next step.',
    wowHt: 'Yon sesyon se yon chita, se pa yon konferans. Pote papye a. Ale ak yon pwochen etap.',
    mythEn: 'Myth: I should wait until I understand everything.',
    mythHt: 'Manti: mwen ta dwe tann jiskaske mwen konprann tout bagay.',
    factEn: 'Fact: you understand enough when you can point at the English line that arrived.',
    factHt: 'Verite: ou konprann ase lè ou ka montre liy angle ki rive a.',
    jokeEn: 'We do not need your whole life story. We need the envelope.',
    jokeHt: 'Nou pa bezwen tout istwa lavi w. Nou bezwen anvlòp la.',
    unknowns: [
      { en: 'Bring screenshots with dates, or the paper itself.', ht: 'Pote foto ekran ak dat, oswa papye a li menm.' },
      { en: 'Say whether it is a bureau page, a collector letter, or court paper.', ht: 'Di si se yon paj biwo, yon lèt kolektè, oswa papye tribinal.' },
      { en: 'One desk per sitting unless the stack is court-first.', ht: 'Yon biwo pou chak chita sof si pil la se tribinal anvan.' },
      { en: 'Ask questions. We will not mock the words you are learning.', ht: 'Poze kesyon. Nou p ap rizye mo w ap aprann yo.' },
      { en: 'If you need a number, ask. We do not print it on the flyer.', ht: 'Si w bezwen yon nimewo, mande. Nou pa enprime l sou feyè a.' },
      { en: 'Results vary. Not legal advice.', ht: 'Rezilta yo varye. Sa a pa konsèy legal.' },
    ],
    nextEn: 'Book a session. Bring the letter that arrived.',
    nextHt: 'Rezève yon sesyon. Pote lèt ki rive a.',
  }),
  specialist: pack({
    id: 'specialist',
    wowEn: 'A Credit Specialist sends one piece to one person. A blast to thirty inboxes is not hospitality. It is litter.',
    wowHt: 'Yon Credit Specialist voye yon feyè bay yon moun. Yon blast nan trant bwat se pa ospitalite. Se fatra.',
    mythEn: 'Myth: more flyers equal more care.',
    mythHt: 'Manti: plis feyè egal plis swen.',
    factEn: 'Fact: one page, one email, one next step. Tell them the fact they did not know. Do not post a price.',
    factHt: 'Verite: yon atifak, yon imèl, yon pwochen etap. Anseye wow la. Pa afiche yon pri.',
    jokeEn: 'If the PDF is only a header, you sent a hat without a person.',
    jokeHt: 'Si PDF la se sèlman yon tit, ou voye yon chapo san moun.',
    unknowns: [
      { en: 'Pick restore, debt, building, or a metro. Not all four.', ht: 'Chwazi restore, dèt, building, oswa yon vil. Pa tout kat.' },
      { en: 'Captions teach. They do not list rungs.', ht: 'Caption yo anseye. Yo pa lis pri.' },
      { en: 'Sit with the family helper rules: they hold the phone.', ht: 'Chita ak règ moun k ap ede: se yo ki kenbe telefòn nan.' },
      { en: 'If they ask the cost, answer in conversation or send /pricing.', ht: 'Si yo mande pri a, reponn nan konvèsasyon oswa voye /pricing.' },
      { en: 'Witty is allowed. Cruel is not.', ht: 'Esprit pèmèt. mechanste pa pèmèt.' },
      { en: 'Compliance stays on every piece.', ht: 'Konfòmite rete sou chak feyè.' },
    ],
    nextEn: 'Send one piece. Teach one wow. Invite Pale Kreyòl.',
    nextHt: 'Voye yon feyè. Anseye yon wow. Envite Pale Kreyòl.',
  }),
  affiliate: pack({
    id: 'affiliate',
    wowEn: 'Share the insight, not a coupon. People forward the fact they did not know.',
    wowHt: 'Pataje insight la, se pa yon koupon. Moun yo voye verite yo pa t konnen.',
    mythEn: 'Myth: the loudest price wins the church parking lot.',
    mythHt: 'Manti: pri ki pi fò genyen pakin legliz la.',
    factEn: 'Fact: a wow about clocks, files, or letters travels. A dollar amount starts an argument.',
    factHt: 'Verite: yon wow sou relè, dosye, oswa lèt vwayaje. Yon montan kòmanse yon diskisyon.',
    jokeEn: 'You are not a walking cash register. You are the person who knew the letter was a clock.',
    jokeHt: 'Ou se pa yon kès k ap mache. Ou se moun ki te konnen lèt la se yon relè.',
    unknowns: [
      { en: 'One piece per share. Caption in two voices if they need Kreyòl.', ht: 'Yon feyè pou chak pataj. Caption nan de vwa si yo bezwen kreyòl.' },
      { en: 'Do not invent staff names. Use the Haitian faces that exist.', ht: 'Pa envante non anplwaye. Sèvi ak visay ayisyen ki egziste.' },
      { en: 'No flags, food, or carnival as costume.', ht: 'Pa drapo, manje, oswa kanaval kòm kostim.' },
      { en: 'Point at /haitian or a metro desk — never a black English city stub.', ht: 'Montre /haitian oswa yon biwo vil — pa yon paj SEO nwa angle.' },
      { en: 'If they ask price, they asked. Then you may answer.', ht: 'Si yo mande pri, yo mande. Lè sa a ou ka reponn.' },
      { en: 'Results vary. Not legal advice.', ht: 'Rezilta yo varye. Sa a pa konsèy legal.' },
    ],
    nextEn: 'Share one insight. Invite Pale Kreyòl.',
    nextHt: 'Pataje yon insight. Envite Pale Kreyòl.',
  }),
  admin: pack({
    id: 'admin',
    wowEn: 'The closet is a closet. Send the piece that matches the paper on the table — not the first tile in the grid.',
    wowHt: 'Plakad la se yon plakad. Voye feyè ki matche papye sou tab la — pa premye kaye nan kadriyaj la.',
    mythEn: 'Myth: one generic kit covers restore, debt, and Houston.',
    mythHt: 'Manti: yon kit jenèrik kouvri restore, dèt, ak Houston.',
    factEn: 'Fact: unique object, unique wow, no price on the page. Email the artifact.',
    factHt: 'Verite: objè inik, wow inik, pa gen pri sou paj la. Voye atifak la nan imèl.',
    jokeEn: 'If two PDFs look like twins with different hats, neither is dressed.',
    jokeHt: 'Si de PDF sanble marasa ak chapo diferan, okenn pa abiye.',
    unknowns: [
      { en: 'Rooms: services, debt, outreach, roles, metros.', ht: 'Chanm: sèvis, dèt, outreach, wòl, vil.' },
      { en: 'Fill the letter-size page. Header-only is a failed download.', ht: 'Ranpli paj lèt la. Tit sèlman se yon telechajman ki echwe.' },
      { en: 'Even grids. No leftover chip row.', ht: 'Kadiyaj menm. Pa yon ranje kaye ki rete.' },
      { en: 'Never volunteer a from-price in captions.', ht: 'Pa janm ofri yon pri “from” nan caption.' },
      { en: 'Metro chips go to /haitian/:metro.', ht: 'Kaye vil yo ale sou /haitian/:metro.' },
      { en: 'Hospitality in chat. Insight in marketing.', ht: 'Ospitalite nan chat. Insight nan maketing.' },
    ],
    nextEn: 'Pick the matching piece. Download. Send. Do not post a price.',
    nextHt: 'Chwazi feyè ki matche. Telechaje. Voye. Pa afiche yon pri.',
  }),
  'metro-miami': pack({
    id: 'metro-miami',
    wowEn: 'South Florida files mix condo, HOA, and overseas addresses until a furnisher thinks you live in three zip codes at once.',
    wowHt: 'Dosye Florid Sid melanje condo, HOA, ak adrès lòt peyi jiskaske yon furnisher panse ou viv nan twa zip anmenmtan.',
    mythEn: 'Myth: one current address is enough.',
    mythHt: 'Manti: yon sèl adrès kounye a ase.',
    factEn: 'Fact: list every address year — condo, HOA, and overseas — before the first letter.',
    factHt: 'Verite: lis chak ane adrès — condo, HOA, ak lòt peyi — anvan premye lèt la.',
    jokeEn: 'Miami files collect addresses the way balconies collect chairs.',
    jokeHt: 'Dosye Miami ranmase adrès menm jan balkon yo ranmase chèz.',
    unknowns: [
      { en: 'International addresses confuse furnishers that only know USPS habits.', ht: 'Adrès entènasyonal konfonn furnisher ki konnen sèlman abitid USPS.' },
      { en: 'HOA and condo names are not nicknames. Write them as the statement prints.', ht: 'Non HOA ak condo se pa ti non. Ekri yo jan deklarasyon an ekri.' },
      { en: 'Broward and Palm Beach are not “close enough” to Miami on a bureau page.', ht: 'Broward ak Palm Beach se pa “pre ase” Miami sou yon paj biwo.' },
      { en: 'Pull all three bureaus. One cousin may still have the overseas line.', ht: 'Pran twa biwo yo. Yon kouzen ka toujou gen liy lòt peyi a.' },
      { en: 'Do not dispute from memory of last year’s lease.', ht: 'Pa diskite sou memwa kontra lwe ane pase a.' },
      { en: 'Pale Kreyòl with the stack in hand.', ht: 'Pale Kreyòl ak pil la nan men.' },
    ],
    nextEn: 'Bring the address stack. We read the English line in Miami.',
    nextHt: 'Pote pil adrès yo. Nou li liy angle a nan Miami.',
  }),
  'metro-brooklyn': pack({
    id: 'metro-brooklyn',
    wowEn: 'Brooklyn mailboxes still win arguments. The envelope date is evidence. A screenshot of a text is a rumor.',
    wowHt: 'Bwat Brooklyn toujou genyen diskisyon. Dat anvlòp la se prèv. Yon foto tèks se tripotay.',
    mythEn: 'Myth: if I paid in cash at the bodega, the collector knows.',
    mythHt: 'Manti: si m peye cash nan bodega, kolektè a konnen.',
    factEn: 'Fact: keep the envelope. Date the day it arrived. Do not pay from fear that same week.',
    factHt: 'Verite: kenbe anvlòp la. Date jou li rive. Pa peye paske w pè nan menm semèn nan.',
    jokeEn: 'Kings County collectors do not accept “I meant to open it after church.”',
    jokeHt: 'Kolektè Kings County pa aksepte “mwen te vle ouvri l apre legliz.”',
    unknowns: [
      { en: 'Old addresses across boroughs still furnish. List them.', ht: 'Ansyen adrès nan borough yo toujou rapòte. Lis yo.' },
      { en: 'A 30-day validation window can start when the letter lands, not when you felt ready.', ht: 'Yon fenèt validasyon 30 jou ka kòmanse lè lèt la rive, pa lè ou te santi w pare.' },
      { en: 'NYC files mix medical, cards, and old phones. Separate the rooms.', ht: 'Dosye NYC melanje medikal, kat, ak ansyen telefòn. Separe chanm yo.' },
      { en: 'Certified receipts beat memory.', ht: 'Resi sètifye bat memwa.' },
      { en: 'Do not argue with a portal chat. Argue with the paper.', ht: 'Pa diskite ak yon chat pòtal. Diskite ak papye a.' },
      { en: 'Pale Kreyòl with the envelope on the table.', ht: 'Pale Kreyòl ak anvlòp la sou tab la.' },
    ],
    nextEn: 'Keep the Brooklyn envelope. Read the letter that arrived.',
    nextHt: 'Kenbe anvlòp Brooklyn. Li lèt ki rive a.',
  }),
  'metro-boston': pack({
    id: 'metro-boston',
    wowEn: 'Campus accounts and hospital billing are different English. Sitting them in one dispute letter is how both cousins get confused.',
    wowHt: 'Kont lekòl ak bòdwo lopital se angle diferan. Mete yo nan yon sèl lèt diskisyon se jan tou de kouzen yo konfonn.',
    mythEn: 'Myth: if it is Massachusetts, it is all “medical.”',
    mythHt: 'Manti: si se Massachusetts, tout se “medikal.”',
    factEn: 'Fact: separate student from hospital before the first round.',
    factHt: 'Verite: separe lekòl ak lopital anvan premye wonn nan.',
    jokeEn: 'Boston files can hold a tuition line and an ER line like they went to the same party.',
    jokeHt: 'Dosye Boston ka kenbe yon liy lekòl ak yon liy irjans tankou yo te ale menm fèt.',
    unknowns: [
      { en: 'Student loans and campus cards are not the same tradeline family.', ht: 'Prè etidyan ak kat lekòl se pa menm fanmi tradeline.' },
      { en: 'Hospital billing may have its own collector. Ask who owns the debt.', ht: 'Bòdwo lopital ka gen pwòp kolektè. Mande kiyès ki posede dèt la.' },
      { en: 'Brockton and Randolph are not a rounding error on the address.', ht: 'Brockton ak Randolph se pa yon erè awondi sou adrès la.' },
      { en: 'Pull all three. Medical furnishing is uneven.', ht: 'Pran twa yo. Rapò medikal pa menm sou tout.' },
      { en: 'Do not promise a score after one tuition payment.', ht: 'Pa pwomèt yon nòt apre yon pèyman lekòl.' },
      { en: 'Pale Kreyòl with both statements in hand.', ht: 'Pale Kreyòl ak tou de deklarasyon nan men.' },
    ],
    nextEn: 'Separate student from medical. Then pick one next step.',
    nextHt: 'Separe lekòl ak medikal. Apre sa, chwazi yon pwochen etap.',
  }),
  'metro-houston': pack({
    id: 'metro-houston',
    wowEn: 'Energy-cycle paydays move utilization. The bureau photographs the card on statement day, not on the day you got paid.',
    wowHt: 'Pèyman sik enèji deplase itilizasyon. Biwo a foto kat la jou deklarasyon, pa jou ou resevwa lajan.',
    mythEn: 'Myth: I paid it, so the percentage is already kind.',
    mythHt: 'Manti: mwen peye l, kidonk pousantaj la gentan janti.',
    factEn: 'Fact: map statement dates before anyone disputes a “high use” line that was just timing.',
    factHt: 'Verite: make dat deklarasyon anvan nenpòt moun diskite yon liy “gwo itilizasyon” ki te jis tan.',
    jokeEn: 'Houston math: payday Friday, snapshot Wednesday, panic Thursday.',
    jokeHt: 'Matematik Houston: pèyman vandredi, foto mèkredi, panik Jedi.',
    unknowns: [
      { en: 'Ask the issuer when they report. It is a date, not a vibe.', ht: 'Mande emete a kilè yo rapòte. Se yon dat, se pa yon vibes.' },
      { en: 'Disputing utilization that is accurate wastes a round.', ht: 'Diskite itilizasyon ki kòrèk gaspiye yon wonn.' },
      { en: 'On-time still matters when the percentage is loud.', ht: 'Peye alè toujou konte lè pousantaj la fò.' },
      { en: 'Do not close the card to hide a snapshot.', ht: 'Pa fèmen kat la pou kache yon foto.' },
      { en: 'Texas files still pull three bureaus.', ht: 'Dosye Texas toujou pran twa biwo.' },
      { en: 'Pale Kreyòl with the statement calendar.', ht: 'Pale Kreyòl ak kalandriye deklarasyon an.' },
    ],
    nextEn: 'Map statement dates. Then decide what is actually wrong.',
    nextHt: 'Make dat deklarasyon yo. Apre sa, deside sa ki mal vreman.',
  }),
  'metro-atlanta': pack({
    id: 'metro-atlanta',
    wowEn: 'Collections follow moves. The original creditor is the name that matters — not the fourth buyer with a new logo.',
    wowHt: 'Koleksyon yo swiv demenajman. Premye krèdye a se non ki konte — pa katriyèm achtè ak yon nouvo logo.',
    mythEn: 'Myth: if I moved, the old collection died.',
    mythHt: 'Manti: si mwen demenaje, ansyen koleksyon an mouri.',
    factEn: 'Fact: match every collection to the original creditor before you write.',
    factHt: 'Verite: matche chak koleksyon ak premye krèdye a anvan w ekri.',
    jokeEn: 'Atlanta files keep souvenirs. Some of them are legally still talking.',
    jokeHt: 'Dosye Atlanta kenbe souvni. Kèk nan yo toujou ap pale legalman.',
    unknowns: [
      { en: 'Buyer names change. Original creditor often does not.', ht: 'Non achtè yo chanje. Premye krèdye a souvan pa chanje.' },
      { en: 'Address history across Georgia can look like three people.', ht: 'Istwa adrès atravè Georgia ka sanble twa moun.' },
      { en: 'Do not pay four collectors for one original account.', ht: 'Pa peye kat kolektè pou yon sèl kont orijinal.' },
      { en: 'Screenshots of each collection line, dated.', ht: 'Foto chak liy koleksyon, ak dat.' },
      { en: 'A move is not a legal eraser.', ht: 'Yon demenajman se pa yon gòm legal.' },
      { en: 'Pale Kreyòl with the move stack.', ht: 'Pale Kreyòl ak pil demenajman an.' },
    ],
    nextEn: 'Match each collection to the original creditor.',
    nextHt: 'Matche chak koleksyon ak premye krèdye a.',
  }),
  'metro-washington': pack({
    id: 'metro-washington',
    wowEn: 'DC, Maryland, and Virginia can all print on one person. Three-state stacks look like identity theft even when it is just commuting.',
    wowHt: 'DC, Maryland, ak Virginia ka tout ekri sou yon sèl moun. Pil twa eta sanble vòl idantite menm lè se jis trajè.',
    mythEn: 'Myth: pick one state and the others vanish.',
    mythHt: 'Manti: chwazi yon eta epi lòt yo disparèt.',
    factEn: 'Fact: audit addresses and names before the first dispute round.',
    factHt: 'Verite: tcheke adrès ak non yo anvan premye wonn nan.',
    jokeEn: 'The Beltway is not a bureau. Stop letting it file your addresses for you.',
    jokeHt: 'Beltway a se pa yon biwo. Sispann kite l ranpli adrès ou pou ou.',
    unknowns: [
      { en: 'Jr / II / hyphenated names duplicate files.', ht: 'Jr / II / non ak tirè kopi dosye.' },
      { en: 'MD and VA spellings of the same street still count as two lines.', ht: 'Òtograf MD ak VA menm ri a toujou konte kòm de liy.' },
      { en: 'Freeze if the stack looks like a stranger. Then sit with findings.', ht: 'Freeze si pil la sanble yon etranje. Apre sa chita ak jwenn yo.' },
      { en: 'Pull all three. One cousin loves old Virginia.', ht: 'Pran twa yo. Yon kouzen renmen ansyen Virginia.' },
      { en: 'Do not dispute accurate old addresses you actually used.', ht: 'Pa diskite ansyen adrès kòrèk ou te vrèman itilize.' },
      { en: 'Pale Kreyòl with the three-state list.', ht: 'Pale Kreyòl ak lis twa eta a.' },
    ],
    nextEn: 'Audit the address fan. Then write.',
    nextHt: 'Tcheke evantay adrès la. Apre sa, ekri.',
  }),
  'metro-chicago': pack({
    id: 'metro-chicago',
    wowEn: 'City, utility, and medical items sit next to bank cards. They are not one “Chicago debt.”',
    wowHt: 'Atik vil, sèvis piblik, ak medikal chita bò kote kat bank. Yo pa yon sèl “dèt Chicago.”',
    mythEn: 'Myth: if ComEd and a Visa are both past due, one letter covers them.',
    mythHt: 'Manti: si ComEd ak yon Visa tou de an reta, yon lèt kouvri yo.',
    factEn: 'Fact: mark what you still recognize. Separate utility from revolving.',
    factHt: 'Verite: make sa w toujou rekonèt. Separe sèvis piblik ak revolving.',
    jokeEn: 'Cook County files keep a winter coat of utilities. Unzip them one zipper at a time.',
    jokeHt: 'Dosye Cook County kenbe yon palto sèvis piblik. Ouvri yo yon zip nan yon moman.',
    unknowns: [
      { en: 'Municipal and utility furnishers use different English than banks.', ht: 'Furnisher vil ak sèvis piblik sèvi ak angle diferan pase bank.' },
      { en: 'Medical in Illinois can look quiet until a collector buys it.', ht: 'Medikal nan Illinois ka trankil jiskaske yon kolektè achte l.' },
      { en: 'Do not mix a city ticket with a Mastercard dispute.', ht: 'Pa melanje yon tikè vil ak yon diskisyon Mastercard.' },
      { en: 'Pull all three. City items are uneven.', ht: 'Pran twa yo. Atik vil yo pa menm.' },
      { en: 'Keep the city notices. Portals forget. Paper remembers.', ht: 'Kenbe avi vil yo. Pòtal yo bliye. Papye sonje.' },
      { en: 'Pale Kreyòl with the docket split.', ht: 'Pale Kreyòl ak docket separe a.' },
    ],
    nextEn: 'Mark what you recognize. Split utility from cards.',
    nextHt: 'Make sa w rekonèt. Separe sèvis piblik ak kat.',
  }),
  'metro-philadelphia': pack({
    id: 'metro-philadelphia',
    wowEn: 'Age on good lines is an asset. Challenging a clean, old account because you are bored is how people shrink their own garden.',
    wowHt: 'Laj sou bon liy se yon byen. Diskite yon kont pwòp, ansyen, paske ou anwiye se jan moun redwi pwòp jaden yo.',
    mythEn: 'Myth: dispute everything older than five years.',
    mythHt: 'Manti: diskite tout sa ki gen plis pase senk ane.',
    factEn: 'Fact: challenge only what the screenshots show is wrong. Let good age work.',
    factHt: 'Verite: diskite sèlman sa foto ekran yo montre ki mal. Kite bon laj travay.',
    jokeEn: 'Philly files can be a museum. Do not throw out the paintings because the gift shop is messy.',
    jokeHt: 'Dosye Philly ka yon mize. Pa jete tablo yo paske boutik kado a sal.',
    unknowns: [
      { en: 'Average age of accounts cares about the oldest revolving.', ht: 'Laj mwayèn kont yo pran swen pi ansyen revolving la.' },
      { en: 'Too-old-to-stay is a finding. Healthy-old is a feature.', ht: 'Twò granmoun pou rete se yon jwenn. Ansyen-an-sante se yon avantaj.' },
      { en: 'Pennsylvania clutter is often old collections plus good cards. Split them.', ht: 'Dezòd Pennsylvania souvan se ansyen koleksyon plis bon kat. Separe yo.' },
      { en: 'Screenshot before you write. Memory is not a museum label.', ht: 'Foto anvan w ekri. Memwa se pa yon etikèt mize.' },
      { en: 'Do not close the oldest good card for sport.', ht: 'Pa fèmen pi ansyen bon kat la pou plezi.' },
      { en: 'Pale Kreyòl with the age map.', ht: 'Pale Kreyòl ak kat laj la.' },
    ],
    nextEn: 'Age the good lines. Challenge only what screenshots show.',
    nextHt: 'Kite bon liy yo pran laj. Diskite sèlman sa foto yo montre.',
  }),
  'metro-jacksonville': pack({
    id: 'metro-jacksonville',
    wowEn: 'Insurance and auto items often carry a short clock. The VIN does not RSVP to your weekend.',
    wowHt: 'Asirans ak oto souvan gen yon relè kout. VIN nan pa konfime pou wikenn ou.',
    mythEn: 'Myth: Florida time is slower for notices too.',
    mythHt: 'Manti: tan Florid pi dousman pou avi yo tou.',
    factEn: 'Fact: photograph every bureau screen and every notice before you write.',
    factHt: 'Verite: foto chak ekran biwo ak chak avi anvan w ekri.',
    jokeEn: 'Northeast Florida mail is not on island time. It is on statute time.',
    jokeHt: 'Lapòs Florid Nòdès pa sou tan zile. Li sou tan lwa.',
    unknowns: [
      { en: 'Force-placed insurance can invent a new number overnight.', ht: 'Asirans force-placed ka envante yon nouvo nimewo lannwit.' },
      { en: 'Repo clocks and bureau reporting are different rooms.', ht: 'Relè repo ak rapò biwo se chanm diferan.' },
      { en: 'Keep the insurance cancellation page.', ht: 'Kenbe paj anilasyon asirans lan.' },
      { en: 'Pull all three. Auto furnishers are uneven.', ht: 'Pran twa yo. Furnisher oto yo pa menm.' },
      { en: 'Do not wait for the next paycheck to read a sale notice.', ht: 'Pa tann pwochèn pèyman pou li yon avi vant.' },
      { en: 'Pale Kreyòl with the VIN paper.', ht: 'Pale Kreyòl ak papye VIN nan.' },
    ],
    nextEn: 'Photograph the auto clock. Then talk.',
    nextHt: 'Foto relè oto a. Apre sa, pale.',
  }),
  'metro-new-jersey': pack({
    id: 'metro-new-jersey',
    wowEn: 'There is no English city SEO stub for this corridor. Newark, Elizabeth, and Jersey City sit at this Haitian desk on purpose.',
    wowHt: 'Pa gen paj SEO angle pou koridò sa a. Newark, Elizabeth, ak Jersey City chita sou biwo ayisyen sa a espre.',
    mythEn: 'Myth: New Jersey is “just New York.”',
    mythHt: 'Manti: New Jersey se “jis Nouyòk.”',
    factEn: 'Fact: say which city the envelope came to. Collectors and bureaus print the city.',
    factHt: 'Verite: di nan ki vil anvlòp la rive. Kolektè ak biwo yo ekri vil la.',
    jokeEn: 'The Turnpike is not a credit bureau. Stop letting it file your life as “NYC-ish.”',
    jokeHt: 'Turnpike la se pa yon biwo kredi. Sispann kite l ranpli lavi w kòm “NYC-ish.”',
    unknowns: [
      { en: 'Three cities, one corridor, one desk — /haitian/new-jersey.', ht: 'Twa vil, yon koridò, yon biwo — /haitian/new-jersey.' },
      { en: 'Port and warehouse pay cycles can move utilization like Houston energy weeks.', ht: 'Sik pèyman pò ak depo ka deplase itilizasyon tankou semèn enèji Houston.' },
      { en: 'Old NY addresses plus NJ addresses look like two people.', ht: 'Ansyen adrès NY plis adrès NJ sanble de moun.' },
      { en: 'Keep the envelope. Name the city on it.', ht: 'Kenbe anvlòp la. Nonmen vil ki sou li.' },
      { en: 'Do not send guests to a black /credit/:city page.', ht: 'Pa voye envite yo sou yon paj /credit/:city nwa.' },
      { en: 'Pale Kreyòl on this corridor.', ht: 'Pale Kreyòl sou koridò sa a.' },
    ],
    nextEn: 'Say Newark, Elizabeth, or Jersey City. Then read the letter.',
    nextHt: 'Di Newark, Elizabeth, oswa Jersey City. Apre sa, li lèt la.',
  }),
};

const PIECE_TO_PACK: Record<string, string> = {
  restore: 'restore',
  'restore-diy': 'restore',
  'what-is-credit': 'file',
  'letter-meaning': 'debt',
  'debt-diy': 'debt',
  'debt-dfy': 'debt',
  litigation: 'court',
  foreclosure: 'foreclosure',
  repossession: 'repo',
  bankruptcy: 'bankruptcy',
  building: 'building',
  business: 'business',
  'business-ladder': 'business',
  chexsystems: 'chex',
  privacy: 'privacy',
  tradelines: 'tradelines',
  bundles: 'bundles',
  maintenance: 'maintenance',
  helper: 'helper',
  'community-flyer': 'church',
  'community-intro': 'welcome',
  'how-it-works': 'visit',
  'book-session': 'session',
  'specialist-recruit': 'specialist',
  'specialist-field-pack': 'specialist',
  'affiliate-share': 'affiliate',
  'admin-playbook': 'admin',
  'metro-miami': 'metro-miami',
  'metro-brooklyn': 'metro-brooklyn',
  'metro-boston': 'metro-boston',
  'metro-houston': 'metro-houston',
  'metro-atlanta': 'metro-atlanta',
  'metro-washington': 'metro-washington',
  'metro-chicago': 'metro-chicago',
  'metro-philadelphia': 'metro-philadelphia',
  'metro-jacksonville': 'metro-jacksonville',
  'metro-new-jersey': 'metro-new-jersey',
};

export function insightForPiece(pieceId: string | undefined): HaitianInsightPack {
  const key = PIECE_TO_PACK[pieceId ?? ''] ?? 'welcome';
  return HT_INSIGHTS[key] ?? HT_INSIGHTS.welcome;
}

export function insightForMetroSlug(slug: string | undefined): HaitianInsightPack {
  return insightForPiece(slug ? `metro-${slug}` : undefined);
}
