import type { GeoCluster, StaffDepartment, StaffDepartmentId, StaffMember, StaffMissionType } from './types';

const shift = (label: string, startLocal: string, endLocal: string, days = 'Mon-Sun') => ({
  label,
  days,
  startLocal,
  endLocal,
  timezone: 'America/New_York',
});

const portrait = (initials: string, emoji: string, gradient: string, glow: string, titleTag: string, visualHint: string) => ({ initials, emoji, gradient, glow, titleTag, visualHint });

export const STAFF_DEPARTMENTS: StaffDepartment[] = [
  {
    id: 'executive_suite',
    name: 'Executive Suite',
    shortName: 'Executives',
    description: 'The decision layer. Sets strategy, assigns departments, and explains what the system is doing in plain English.',
    primaryOwnerId: 'professor_apex',
    colorHint: 'amber',
    missionTypes: ['overnight_run', 'analytics_diagnosis', 'compliance_review'],
    defaultRoute: '/admin/staff?department=executive_suite',
    workProducts: ['daily orders', 'mission approval ladder', 'department ownership map'],
  },
  {
    id: 'marketing_cmo',
    name: 'CMO + Growth Strategy',
    shortName: 'CMO',
    description: 'Campaign strategy, offer positioning, channel mix, hooks, lead magnet angles, and promotion calendar.',
    primaryOwnerId: 'cmo_prime',
    colorHint: 'gold',
    missionTypes: ['content_pack', 'city_growth_sprint', 'overnight_run'],
    defaultRoute: '/admin/cmo',
    workProducts: ['campaign brief', 'offers', 'content calendar', 'daily growth orders'],
  },
  {
    id: 'lead_intel',
    name: 'Lead Intel Swarm',
    shortName: 'Intel',
    description: 'Continuous discovery, query expansion, source scanning, scoring, dedupe, and Action Center recommendations.',
    primaryOwnerId: 'scout_supreme',
    colorHint: 'emerald',
    missionTypes: ['deep_swarm', 'lead_action_review', 'overnight_run'],
    defaultRoute: '/admin/lead-intel',
    workProducts: ['discovered leads', 'hot candidates', 'source reports', 'best next action'],
  },
  {
    id: 'geo_growth',
    name: 'Geo Growth War Room',
    shortName: 'Geo',
    description: 'City-by-city domination: local offers, short links, source mix, city pages, attribution, and saturation warnings.',
    primaryOwnerId: 'geo_commander',
    colorHint: 'cyan',
    missionTypes: ['city_growth_sprint', 'geo_page_push', 'overnight_run'],
    defaultRoute: '/admin/staff?view=geo',
    workProducts: ['city plan', 'zip focus', 'geo offer routing', 'city source balance'],
  },
  {
    id: 'appointment_setting',
    name: 'Appointment Setting',
    shortName: 'Appointments',
    description: 'Turns interested prospects into booked calls with reminder plans and human-safe follow-up sequences.',
    primaryOwnerId: 'appointment_architect',
    colorHint: 'violet',
    missionTypes: ['appointment_blitz', 'lead_action_review', 'nurture_fix'],
    defaultRoute: '/admin/calendar',
    workProducts: ['booking plan', 'reminder sequence', 'no-show rescue'],
  },
  {
    id: 'sales',
    name: 'Sales + Revenue Desk',
    shortName: 'Sales',
    description: 'Owns consultation follow-up, high-intent leads, offer fit, quote readiness, and close-stage task routing.',
    primaryOwnerId: 'revenue_captain',
    colorHint: 'green',
    missionTypes: ['sales_follow_up', 'lead_action_review', 'appointment_blitz'],
    defaultRoute: '/admin/crm',
    workProducts: ['sales task', 'call priority', 'objection plan', 'pipeline status'],
  },
  {
    id: 'recruiting',
    name: 'Recruiting + Careers',
    shortName: 'Recruiting',
    description: 'Credit specialists, agency partners, affiliates, AU sellers, and future real human staff recruiting.',
    primaryOwnerId: 'partner_recruiter',
    colorHint: 'orange',
    missionTypes: ['recruiting_drive', 'partner_outreach', 'city_growth_sprint'],
    defaultRoute: '/agents',
    workProducts: ['candidate funnel', 'recruiting message', 'partner pitch', 'application review'],
  },
  {
    id: 'pr_authority',
    name: 'PR + Authority',
    shortName: 'PR',
    description: 'Press angles, podcast/interview outreach, local news hooks, authority campaigns, and credibility assets.',
    primaryOwnerId: 'pr_sentinel',
    colorHint: 'blue',
    missionTypes: ['pr_pitch', 'content_pack', 'city_growth_sprint'],
    defaultRoute: '/admin/media-studio',
    workProducts: ['pitch list', 'authority hook', 'press brief', 'post-interview repurpose plan'],
  },
  {
    id: 'nurture_comms',
    name: 'Nurture + Comms',
    shortName: 'Nurture',
    description: 'Email/SMS/portal follow-up, sequence ownership, consent gates, reply routing, and conversion recovery.',
    primaryOwnerId: 'liora_lifecycle',
    colorHint: 'rose',
    missionTypes: ['nurture_fix', 'lead_action_review', 'sales_follow_up'],
    defaultRoute: '/admin/comms',
    workProducts: ['sequence', 'message draft', 'reply path', 'consent check'],
  },
  {
    id: 'content_media',
    name: 'Content + Media Factory',
    shortName: 'Media',
    description: 'Shorts scripts, thumbnails, hooks, creative briefs, local post packs, and content-to-funnel handoff.',
    primaryOwnerId: 'content_director',
    colorHint: 'pink',
    missionTypes: ['content_pack', 'pr_pitch', 'geo_page_push'],
    defaultRoute: '/admin/media-studio',
    workProducts: ['script pack', 'thumbnail brief', 'caption matrix', 'local content queue'],
  },
  {
    id: 'automation_ops',
    name: 'Automation Ops',
    shortName: 'Automation',
    description: 'Schedulers, queues, workers, internal automations, blocked items, and operational reliability.',
    primaryOwnerId: 'switchboard',
    colorHint: 'slate',
    missionTypes: ['overnight_run', 'deep_swarm', 'analytics_diagnosis'],
    defaultRoute: '/admin/automations',
    workProducts: ['queue state', 'worker tick', 'blocker report', 'automation recipe'],
  },
  {
    id: 'compliance',
    name: 'Compliance + Safety',
    shortName: 'Compliance',
    description: 'Claims review, approval gates, TCPA/CAN-SPAM checks, high-risk copy blocks, and outbound guardrails.',
    primaryOwnerId: 'velvet_hammer',
    colorHint: 'red',
    missionTypes: ['compliance_review', 'lead_action_review', 'nurture_fix'],
    defaultRoute: '/admin/settings',
    workProducts: ['risk verdict', 'copy rewrite', 'approval requirement', 'blocked reason'],
  },
  {
    id: 'analytics',
    name: 'Analytics + Intelligence',
    shortName: 'Analytics',
    description: 'Performance tracking, attribution, city health, conversion bottlenecks, and channel model feedback.',
    primaryOwnerId: 'analytics_beast',
    colorHint: 'indigo',
    missionTypes: ['analytics_diagnosis', 'city_growth_sprint', 'overnight_run'],
    defaultRoute: '/admin/analytics',
    workProducts: ['scorecard', 'bottlenecks', 'channel model update', 'city forecast'],
  },
  {
    id: 'partner_growth',
    name: 'Partner + Affiliate Growth',
    shortName: 'Partners',
    description: 'Affiliate wrangling, partner referrals, agency activation, bounties, and source expansion.',
    primaryOwnerId: 'affiliate_wrangler',
    colorHint: 'lime',
    missionTypes: ['partner_outreach', 'recruiting_drive', 'city_growth_sprint'],
    defaultRoute: '/affiliate',
    workProducts: ['partner list', 'bounty campaign', 'activation task', 'referral loop'],
  },
];

export const STAFF_MEMBERS: StaffMember[] = [
  {
    id: 'professor_apex',
    name: 'Professor Apex',
    title: 'Chief Agent Architect',
    kind: 'ai_staff',
    departmentId: 'executive_suite',
    seniority: 'chief',
    status: 'working',
    workMode: 'advises',
    portrait: portrait('PA', '🧠', 'from-amber-300 via-orange-400 to-yellow-600', 'shadow-amber-500/30', 'Boss of Agents', 'gold command glasses'),
    shift: shift('Executive oversight', '00:00', '23:59'),
    missionTypes: ['overnight_run', 'analytics_diagnosis', 'compliance_review', 'city_growth_sprint'],
    canBeSelected: true,
    defaultPairings: ['cmo_prime', 'switchboard', 'velvet_hammer'],
    tagline: 'Decides who owns what and turns chaos into a chain of command.',
    responsibilities: ['Translate big goals into staff assignments', 'Approve department structure', 'Explain what the system is doing', 'Spot missing owners and blockers'],
    runbook: ['Read the mission type', 'Pick the owning department', 'Assign one lead owner and two support owners', 'Define the first three operational steps'],
    tools: ['staff command matrix', 'mission planner', 'approval ladder', 'daily order engine'],
    kpis: [{ label: 'unowned work', target: '0', unit: 'items' }, { label: 'mission clarity', target: '95', unit: '%' }],
    blockers: ['Missing route owner', 'conflicting department ownership'],
    complianceBoundaries: ['Never bypass compliance owner on credit/financial claims', 'Never represent AI staff as human employees to customers'],
    lastActivity: 'Mapped Lead Intel into staff-owned missions.',
  },
  {
    id: 'cmo_prime', name: 'CMO Prime', title: 'Chief Marketing Officer', kind: 'ai_staff', departmentId: 'marketing_cmo', seniority: 'chief', status: 'working', workMode: 'drafts',
    portrait: portrait('CM', '📣', 'from-yellow-300 via-amber-500 to-orange-700', 'shadow-yellow-500/25', 'Growth Strategy', 'gold blazer and campaign wall'), shift: shift('Strategy desk', '08:00', '18:00'),
    missionTypes: ['content_pack', 'city_growth_sprint', 'overnight_run', 'geo_page_push'], canBeSelected: true, defaultPairings: ['geo_commander', 'content_director', 'analytics_beast'], reportsTo: 'professor_apex',
    tagline: 'Owns the offer, the angle, the audience, and the campaign plan.', responsibilities: ['Design campaign themes', 'Pick offers per city', 'Prioritize lead magnets', 'Create daily marketing orders'],
    runbook: ['Choose target funnel', 'Select city angle', 'Define hook family', 'Send assets to content/comms/geo teams'], tools: ['campaign briefs', 'content calendar', 'lead magnet matrix', 'budget math'],
    kpis: [{ label: 'campaigns shipped', target: '5', unit: 'daily' }, { label: 'lead magnet CTR', target: '8', unit: '%' }], blockers: ['No offer selected', 'no city focus'], complianceBoundaries: ['No guaranteed credit/funding promises'], lastActivity: 'Prepared geo campaign angles.',
  },
  {
    id: 'pipeline_titan', name: 'Pipeline Titan', title: 'Chief Lead Officer', kind: 'ai_staff', departmentId: 'lead_intel', seniority: 'chief', status: 'working', workMode: 'queues',
    portrait: portrait('PT', '⚡', 'from-emerald-300 via-teal-500 to-cyan-700', 'shadow-emerald-500/25', 'Lead Flow', 'green command armor'), shift: shift('Lead command', '07:00', '20:00'),
    missionTypes: ['deep_swarm', 'lead_action_review', 'overnight_run'], canBeSelected: true, defaultPairings: ['scout_supreme', 'appointment_architect', 'revenue_captain'], reportsTo: 'professor_apex',
    tagline: 'Makes sure lead discovery becomes pipeline, not just data.', responsibilities: ['Own lead targets', 'Review source mix', 'Route hot candidates', 'Escalate bottlenecks'],
    runbook: ['Check daily lead target', 'Compare source supply', 'Push hot leads to Action Center', 'Assign follow-up owner'], tools: ['lead score model', 'CRM handoff', 'swarm queue', 'bottleneck report'],
    kpis: [{ label: 'hot candidates', target: '60', unit: 'daily' }, { label: 'booked calls', target: '20', unit: 'daily target' }], blockers: ['No active cities', 'no short link routing'], complianceBoundaries: ['No outbound without consent/legal basis'], lastActivity: 'Reviewed hot candidate backlog.',
  },
  {
    id: 'switchboard', name: 'Switchboard', title: 'Automation Architect', kind: 'ai_staff', departmentId: 'automation_ops', seniority: 'chief', status: 'needs_approval', workMode: 'executes_internal',
    portrait: portrait('SW', '🕹️', 'from-slate-200 via-slate-500 to-zinc-800', 'shadow-slate-500/25', 'Automation Ops', 'dark control room headset'), shift: shift('Automation watch', '00:00', '23:59'),
    missionTypes: ['deep_swarm', 'overnight_run', 'analytics_diagnosis'], canBeSelected: true, defaultPairings: ['professor_apex', 'analytics_beast', 'velvet_hammer'], reportsTo: 'professor_apex',
    tagline: 'Turns staff missions into queues, ticks, jobs, and blockers you can understand.', responsibilities: ['Own background workers', 'Track scheduler health', 'Report blocked automations', 'Keep actions idempotent'],
    runbook: ['Check integration health', 'Start internal queue', 'Run a tick', 'Log result and blocker'], tools: ['automation rules', 'Supabase functions', 'publish queue', 'job queue'],
    kpis: [{ label: 'failed jobs', target: '0', unit: 'critical' }, { label: 'blocked with reason', target: '100', unit: '%' }], blockers: ['Missing Supabase functions', 'missing provider key'], complianceBoundaries: ['Never execute external action unless approval mode allows it'], lastActivity: 'Blocked external publish until credentials are connected.',
  },
  {
    id: 'velvet_hammer', name: 'The Velvet Hammer', title: 'Compliance Guardian', kind: 'ai_staff', departmentId: 'compliance', seniority: 'chief', status: 'working', workMode: 'advises',
    portrait: portrait('VH', '🛡️', 'from-rose-300 via-red-500 to-stone-900', 'shadow-red-500/25', 'Compliance', 'red velvet shield'), shift: shift('24/7 guardrail', '00:00', '23:59'),
    missionTypes: ['compliance_review', 'lead_action_review', 'nurture_fix'], canBeSelected: true, defaultPairings: ['liora_lifecycle', 'revenue_captain', 'cmo_prime'], reportsTo: 'professor_apex',
    tagline: 'Keeps the engine aggressive without becoming reckless.', responsibilities: ['Block risky claims', 'Review outbound copy', 'Flag TCPA/CAN-SPAM issues', 'Rewrite unsafe messaging'],
    runbook: ['Scan the copy', 'Identify claim risk', 'Check consent and destination', 'Approve, rewrite, or block'], tools: ['blocked phrase list', 'risk score', 'consent status', 'approval gate'],
    kpis: [{ label: 'unsafe sends', target: '0', unit: 'ever' }, { label: 'review time', target: '<15', unit: 'min' }], blockers: ['missing consent', 'guaranteed outcome claim'], complianceBoundaries: ['Cannot be overridden by growth staff'], lastActivity: 'Blocked a fake guarantee phrase.',
  },
  {
    id: 'scout_supreme', name: 'Scout Supreme', title: 'Lead Intel Director', kind: 'ai_staff', departmentId: 'lead_intel', seniority: 'director', status: 'working', workMode: 'queues',
    portrait: portrait('SS', '🔎', 'from-emerald-200 via-lime-500 to-teal-800', 'shadow-emerald-500/25', 'Intel Director', 'night vision search visor'), shift: shift('Intel day shift', '08:00', '20:00'),
    missionTypes: ['deep_swarm', 'lead_action_review', 'city_growth_sprint'], canBeSelected: true, defaultPairings: ['night_owl_intel', 'geo_commander', 'pipeline_titan'], reportsTo: 'pipeline_titan',
    tagline: 'Runs the swarm and brings back the best opportunities.', responsibilities: ['Build query pools', 'Pick source adapters', 'Score candidates', 'Send hot leads to Action Center'],
    runbook: ['Choose city cluster', 'Choose source set', 'Queue jobs', 'Review score/risk/source quality'], tools: ['Lead Intel Swarm', 'query expander', 'source vault', 'candidate scoring'],
    kpis: [{ label: 'sources active', target: '12', unit: 'per city' }, { label: 'hot ratio', target: '20', unit: '%' }], blockers: ['source disabled', 'API key missing'], complianceBoundaries: ['Respect robots.txt and official APIs'], preferredCities: ['dallas_tx', 'houston_tx'], lastActivity: 'Queued searches for Dallas and Houston.',
  },
  {
    id: 'night_owl_intel', name: 'Night Owl Intel', title: 'Overnight Discovery Operator', kind: 'ai_staff', departmentId: 'lead_intel', seniority: 'operator', status: 'idle', workMode: 'queues',
    portrait: portrait('NO', '🦉', 'from-indigo-300 via-purple-600 to-black', 'shadow-indigo-500/25', 'Overnight Intel', 'owl avatar over city map'), shift: shift('Overnight swarm', '22:00', '06:00'),
    missionTypes: ['deep_swarm', 'overnight_run'], canBeSelected: true, defaultPairings: ['scout_supreme', 'switchboard', 'morning_hawk'], reportsTo: 'scout_supreme',
    tagline: 'Works the overnight queue so the morning has a real ledger.', responsibilities: ['Rotate overnight query jobs', 'Enrich slow sources', 'Log live feed progress', 'Prepare morning candidate list'],
    runbook: ['Start swarm', 'Run controlled ticks', 'Mark blocked adapters', 'Summarize overnight findings'], tools: ['overnight jobs', 'cache', 'live feed', 'swarm tick'],
    kpis: [{ label: 'overnight jobs', target: '500', unit: 'queued' }, { label: 'enriched', target: '200', unit: 'records' }], blockers: ['worker not deployed', 'source caps hit'], complianceBoundaries: ['No 1am cold SMS sends without consent and local window rules'], lastActivity: 'Waiting for overnight window.',
  },
  {
    id: 'geo_commander', name: 'Geo Commander', title: 'City Domination Director', kind: 'ai_staff', departmentId: 'geo_growth', seniority: 'director', status: 'working', workMode: 'drafts',
    portrait: portrait('GC', '🗺️', 'from-cyan-200 via-sky-500 to-blue-900', 'shadow-cyan-500/25', 'Geo Commander', 'holographic city map'), shift: shift('Geo rotation', '07:00', '17:00'),
    missionTypes: ['city_growth_sprint', 'geo_page_push', 'overnight_run'], canBeSelected: true, defaultPairings: ['cmo_prime', 'scout_supreme', 'seo_sentinel'], reportsTo: 'cmo_prime',
    tagline: 'Makes Dallas, Houston, Atlanta, Phoenix, and Charlotte feel like separate campaigns.', responsibilities: ['Prioritize cities', 'Assign zip focus', 'Balance source mix', 'Recommend local landing pages'],
    runbook: ['Pick 1-3 city clusters', 'Check source mix health', 'Assign staff to city lanes', 'Recommend next geo asset'], tools: ['geo clusters', 'city leaderboard', 'zip focus', 'local page queue'],
    kpis: [{ label: 'active cities', target: '5', unit: 'clusters' }, { label: 'geo source balance', target: '4+', unit: 'sources/city' }], blockers: ['no city page', 'source mix too thin'], preferredCities: ['dallas_tx', 'atlanta_ga', 'charlotte_nc'], complianceBoundaries: ['Do not fabricate local testimonials or false locations'], lastActivity: 'Flagged Phoenix as needing more content.',
  },
  {
    id: 'appointment_architect', name: 'Appointment Architect', title: 'Appointment Setting Director', kind: 'ai_staff', departmentId: 'appointment_setting', seniority: 'director', status: 'working', workMode: 'queues',
    portrait: portrait('AA', '📅', 'from-violet-200 via-fuchsia-500 to-purple-900', 'shadow-violet-500/25', 'Appointments', 'calendar command glasses'), shift: shift('Booking desk', '09:00', '19:00'),
    missionTypes: ['appointment_blitz', 'lead_action_review', 'nurture_fix'], canBeSelected: true, defaultPairings: ['revenue_captain', 'liora_lifecycle', 'velvet_hammer'], reportsTo: 'pipeline_titan',
    tagline: 'Turns interested leads into booked calls and makes the next step obvious.', responsibilities: ['Own booking CTAs', 'Create reminder path', 'Prioritize hot lead call tasks', 'Recover no-shows'],
    runbook: ['Check hot candidates', 'Match booking funnel', 'Draft message with short link', 'Queue reminders'], tools: ['calendar', 'booking links', 'no-show recovery', 'Action Center'],
    kpis: [{ label: 'booking conversion', target: '15', unit: '%' }, { label: 'no-show rescue', target: '25', unit: '%' }], blockers: ['no calendar link', 'missing phone/email'], complianceBoundaries: ['No misleading urgency'], lastActivity: 'Drafted booking path for business credit leads.',
  },
  {
    id: 'revenue_captain', name: 'Revenue Captain', title: 'Sales Lead', kind: 'future_hire', departmentId: 'sales', seniority: 'manager', status: 'needs_approval', workMode: 'drafts',
    portrait: portrait('RC', '💼', 'from-emerald-300 via-green-600 to-zinc-900', 'shadow-green-500/25', 'Sales', 'sharp suit pipeline board'), shift: shift('Sales desk', '10:00', '18:00'),
    missionTypes: ['sales_follow_up', 'appointment_blitz', 'lead_action_review'], canBeSelected: true, defaultPairings: ['appointment_architect', 'liora_lifecycle', 'velvet_hammer'], reportsTo: 'pipeline_titan',
    tagline: 'Owns the close-stage handoff from interest to revenue.', responsibilities: ['Review high-intent opportunities', 'Recommend offer fit', 'Create sales tasks', 'Flag objections'],
    runbook: ['Check candidate score and fit reasons', 'Pick offer path', 'Draft consult prep', 'Assign sales follow-up'], tools: ['CRM', 'offer matrix', 'call task', 'objection library'],
    kpis: [{ label: 'qualified calls', target: '20', unit: 'daily' }, { label: 'follow-up SLA', target: '<30', unit: 'min' }], blockers: ['no sales owner assigned'], complianceBoundaries: ['No income/funding guarantees'], lastActivity: 'Needs owner assignment before live calling.',
  },
  {
    id: 'partner_recruiter', name: 'Partner Recruiter', title: 'Recruiting Director', kind: 'ai_staff', departmentId: 'recruiting', seniority: 'director', status: 'working', workMode: 'drafts',
    portrait: portrait('PR', '🤝', 'from-orange-200 via-amber-600 to-red-800', 'shadow-orange-500/25', 'Recruiting', 'handshake with gold badge'), shift: shift('Recruiting desk', '09:00', '17:00', 'Tue/Thu focus'),
    missionTypes: ['recruiting_drive', 'partner_outreach', 'city_growth_sprint'], canBeSelected: true, defaultPairings: ['affiliate_wrangler', 'cmo_prime', 'appointment_architect'], reportsTo: 'cmo_prime',
    tagline: 'Builds the people supply: specialists, agents, affiliates, sellers, and partners.', responsibilities: ['Run career funnels', 'Draft recruiting pages', 'Build partner lists', 'Assign interview next steps'],
    runbook: ['Select role funnel', 'Choose city overflow angle', 'Draft outreach', 'Route to application/booking'], tools: ['agents page', 'affiliate page', 'agency signup', 'AU seller page'],
    kpis: [{ label: 'applications', target: '25', unit: 'weekly' }, { label: 'partner activations', target: '10', unit: 'weekly' }], blockers: ['unclear role pitch', 'application form not linked'], complianceBoundaries: ['No unrealistic earnings promises'], lastActivity: 'Prepared agency partner recruiting angle.',
  },
  {
    id: 'affiliate_wrangler', name: 'Affiliate Wrangler', title: 'Affiliate Growth Lead', kind: 'future_hire', departmentId: 'partner_growth', seniority: 'manager', status: 'idle', workMode: 'drafts',
    portrait: portrait('AW', '🪢', 'from-lime-200 via-green-500 to-emerald-900', 'shadow-lime-500/25', 'Affiliate Growth', 'neon rope network'), shift: shift('Partner activation', '10:00', '16:00', 'Wednesday focus'),
    missionTypes: ['partner_outreach', 'recruiting_drive', 'city_growth_sprint'], canBeSelected: true, defaultPairings: ['partner_recruiter', 'liora_lifecycle', 'analytics_beast'], reportsTo: 'cmo_prime',
    tagline: 'Turns warm networks into referral loops.', responsibilities: ['Build bounty campaigns', 'Activate affiliates', 'Track referral source health', 'Draft affiliate nurture'],
    runbook: ['Pick partner segment', 'Create referral hook', 'Generate tracked link', 'Assign activation follow-up'], tools: ['affiliate funnel', 'short links', 'partner CRM', 'referral reports'],
    kpis: [{ label: 'referral partners', target: '50', unit: 'active' }], blockers: ['no partner incentive set'], complianceBoundaries: ['No deceptive referral claims'], lastActivity: 'Waiting for partner incentive decision.',
  },
  {
    id: 'liora_lifecycle', name: 'Liora Lifecycle', title: 'Chief Lifecycle + Nurture Officer', kind: 'ai_staff', departmentId: 'nurture_comms', seniority: 'chief', status: 'working', workMode: 'drafts',
    portrait: portrait('LL', '💌', 'from-rose-200 via-pink-500 to-red-900', 'shadow-pink-500/25', 'Nurture', 'pink message control wall'), shift: shift('Nurture coverage', '09:00', '21:00'),
    missionTypes: ['nurture_fix', 'lead_action_review', 'sales_follow_up', 'appointment_blitz'], canBeSelected: true, defaultPairings: ['appointment_architect', 'velvet_hammer', 'revenue_captain'], reportsTo: 'cmo_prime',
    tagline: 'Makes sure every lead knows the next step without feeling spammed.', responsibilities: ['Own sequences', 'Create first message drafts', 'Route replies', 'Repair nurture gaps'],
    runbook: ['Identify funnel', 'Check consent status', 'Draft safe message', 'Queue or block based on autonomy'], tools: ['Comms Studio', 'sequence vault', 'reply routing', 'consent gate'],
    kpis: [{ label: 'sequence coverage', target: '100', unit: '%' }, { label: 'reply rate', target: '8', unit: '%' }], blockers: ['no consent', 'missing template'], complianceBoundaries: ['SMS only with consent proof'], lastActivity: 'Built nurture handoff for hot leads.',
  },
  {
    id: 'content_director', name: 'Content Director', title: 'Content + Media Lead', kind: 'ai_staff', departmentId: 'content_media', seniority: 'director', status: 'working', workMode: 'drafts',
    portrait: portrait('CD', '🎬', 'from-fuchsia-200 via-pink-500 to-purple-900', 'shadow-fuchsia-500/25', 'Content', 'director chair and gold lights'), shift: shift('Content desk', '10:00', '18:00'),
    missionTypes: ['content_pack', 'pr_pitch', 'geo_page_push'], canBeSelected: true, defaultPairings: ['hook_mutator', 'local_news_radar', 'cmo_prime'], reportsTo: 'cmo_prime',
    tagline: 'Turns strategy into scripts, hooks, captions, and creative briefs.', responsibilities: ['Create short-form scripts', 'Write local captions', 'Build thumbnail briefs', 'Repurpose authority moments'],
    runbook: ['Read campaign brief', 'Pick city/funnel angle', 'Generate 3 hook families', 'Hand off to Media Studio'], tools: ['Media Studio', 'hook library', 'thumbnail brief', 'content calendar'],
    kpis: [{ label: 'short scripts', target: '20', unit: 'weekly' }], blockers: ['no campaign angle'], complianceBoundaries: ['No fake proof or false testimonials'], lastActivity: 'Drafted local short-form pack.',
  },
  {
    id: 'hook_mutator', name: 'Hook Mutator', title: 'Hook Testing Specialist', kind: 'ai_staff', departmentId: 'content_media', seniority: 'specialist', status: 'idle', workMode: 'drafts',
    portrait: portrait('HM', '🧬', 'from-purple-200 via-indigo-500 to-black', 'shadow-indigo-500/25', 'Hook Lab', 'genetic hook board'), shift: shift('Night hook lab', '21:00', '02:00'),
    missionTypes: ['content_pack', 'analytics_diagnosis'], canBeSelected: true, defaultPairings: ['content_director', 'analytics_beast', 'cmo_prime'], reportsTo: 'content_director',
    tagline: 'Mutates weak hooks into testable angles.', responsibilities: ['Create hook variants', 'Tag emotional drivers', 'Connect winners to future content', 'Flag low clarity hooks'],
    runbook: ['Pick winning topic', 'Generate variations', 'Score clarity', 'Send best hooks to queue'], tools: ['hook performance', 'content library', 'caption matrix'],
    kpis: [{ label: 'hook variants', target: '100', unit: 'weekly' }], blockers: ['no performance data'], complianceBoundaries: ['No fearmongering or guaranteed outcomes'], lastActivity: 'Waiting for performance data.',
  },
  {
    id: 'seo_sentinel', name: 'SEO Sentinel', title: 'Geo SEO Operator', kind: 'ai_staff', departmentId: 'geo_growth', seniority: 'operator', status: 'needs_approval', workMode: 'queues',
    portrait: portrait('SEO', '🛰️', 'from-sky-200 via-blue-500 to-zinc-900', 'shadow-sky-500/25', 'Geo SEO', 'satellite over city pages'), shift: shift('SEO drop', '00:00', '08:00'),
    missionTypes: ['geo_page_push', 'city_growth_sprint', 'overnight_run'], canBeSelected: true, defaultPairings: ['geo_commander', 'content_director', 'analytics_beast'], reportsTo: 'geo_commander',
    tagline: 'Turns city focus into local pages and trackable inbound routes.', responsibilities: ['Queue city pages', 'Check content uniqueness', 'Recommend sitemap updates', 'Watch geo inbound'],
    runbook: ['Select city/funnel pair', 'Generate page brief', 'Check duplication risk', 'Queue for approval'], tools: ['SEO queue', 'city page generator', 'sitemap', 'geo attribution'],
    kpis: [{ label: 'city pages', target: '10', unit: 'weekly' }], blockers: ['page not approved'], complianceBoundaries: ['No doorway spam or fake local offices'], lastActivity: 'Needs approval before publishing geo pages.',
  },
  {
    id: 'pr_sentinel', name: 'PR Sentinel', title: 'PR + Authority Lead', kind: 'ai_staff', departmentId: 'pr_authority', seniority: 'director', status: 'idle', workMode: 'drafts',
    portrait: portrait('PS', '📰', 'from-blue-200 via-cyan-500 to-slate-900', 'shadow-blue-500/25', 'PR', 'newsroom alert desk'), shift: shift('Authority desk', '08:00', '16:00'),
    missionTypes: ['pr_pitch', 'content_pack', 'city_growth_sprint'], canBeSelected: true, defaultPairings: ['local_news_radar', 'content_director', 'cmo_prime'], reportsTo: 'cmo_prime',
    tagline: 'Finds angles that make Finely Cred look bigger, local, and credible.', responsibilities: ['Draft press pitches', 'Identify local stories', 'Prepare interview hooks', 'Repurpose press into content'],
    runbook: ['Pick timely angle', 'Match it to service/funnel', 'Draft pitch', 'Queue follow-up'], tools: ['media list', 'press brief', 'events page', 'content repurpose'],
    kpis: [{ label: 'pitch batches', target: '2', unit: 'weekly' }], blockers: ['no authority asset'], complianceBoundaries: ['No false credentials or outcomes'], lastActivity: 'Waiting for local story angle.',
  },
  {
    id: 'local_news_radar', name: 'Local News Radar', title: 'City Angle Researcher', kind: 'ai_staff', departmentId: 'pr_authority', seniority: 'specialist', status: 'working', workMode: 'drafts',
    portrait: portrait('LN', '📡', 'from-cyan-200 via-teal-500 to-slate-900', 'shadow-cyan-500/25', 'Local Angles', 'radar over skyline'), shift: shift('Morning radar', '06:00', '10:00'),
    missionTypes: ['pr_pitch', 'content_pack', 'city_growth_sprint'], canBeSelected: true, defaultPairings: ['pr_sentinel', 'geo_commander', 'content_director'], reportsTo: 'pr_sentinel',
    tagline: 'Finds local hooks without pretending to be local where we are not.', responsibilities: ['Watch local events/news', 'Identify safe finance angles', 'Feed Content Director', 'Suggest city posts'],
    runbook: ['Scan city headlines', 'Match to service angle', 'Write safe local note', 'Send to PR/content'], tools: ['news feeds', 'event calendars', 'geo clusters'],
    kpis: [{ label: 'city angles', target: '5', unit: 'daily' }], blockers: ['no active cities'], complianceBoundaries: ['No fake local presence'], lastActivity: 'Found Dallas event angle.',
  },
  {
    id: 'analytics_beast', name: 'Analytics Beast', title: 'Performance Intelligence Lead', kind: 'ai_staff', departmentId: 'analytics', seniority: 'director', status: 'working', workMode: 'advises',
    portrait: portrait('AB', '📊', 'from-indigo-200 via-blue-600 to-black', 'shadow-indigo-500/25', 'Analytics', 'chart beast hologram'), shift: shift('Continuous analytics', '00:00', '23:59'),
    missionTypes: ['analytics_diagnosis', 'city_growth_sprint', 'overnight_run'], canBeSelected: true, defaultPairings: ['morning_hawk', 'geo_commander', 'cmo_prime'], reportsTo: 'professor_apex',
    tagline: 'Tells you what actually moved leads and what is just noise.', responsibilities: ['Build scorecards', 'Identify bottlenecks', 'Compare city health', 'Recommend next moves'],
    runbook: ['Read events', 'Compute source mix', 'Find bottleneck', 'Recommend one action per department'], tools: ['reports', 'channel model', 'city leaderboard', 'lead attribution'],
    kpis: [{ label: 'unattributed leads', target: '<10', unit: '%' }], blockers: ['tracking missing'], complianceBoundaries: ['No fake attribution'], lastActivity: 'Flagged source mix gap.',
  },
  {
    id: 'morning_hawk', name: 'Morning Hawk', title: 'Morning Brief Operator', kind: 'ai_staff', departmentId: 'analytics', seniority: 'operator', status: 'idle', workMode: 'advises',
    portrait: portrait('MH', '🦅', 'from-yellow-100 via-orange-400 to-stone-900', 'shadow-yellow-500/25', 'Morning Brief', 'hawk over dashboard'), shift: shift('Morning brief', '06:00', '07:00'),
    missionTypes: ['overnight_run', 'analytics_diagnosis'], canBeSelected: true, defaultPairings: ['night_owl_intel', 'analytics_beast', 'professor_apex'], reportsTo: 'analytics_beast',
    tagline: 'Turns overnight chaos into a readable command brief.', responsibilities: ['Summarize overnight run', 'Highlight blockers', 'Pick today’s first action', 'Make the system understandable'],
    runbook: ['Pull overnight ledger', 'Group by source/city', 'Flag blockers', 'Write top 5 actions'], tools: ['overnight report', 'lead ledger', 'staff events'],
    kpis: [{ label: 'brief by', target: '06:05', unit: 'local' }], blockers: ['no overnight run data'], complianceBoundaries: ['Do not claim lead volume not actually tracked'], lastActivity: 'Waiting for tomorrow morning ledger.',
  },
  {
    id: 'retarget_architect', name: 'Retarget Architect', title: 'Retargeting + Audience Lead', kind: 'ai_staff', departmentId: 'marketing_cmo', seniority: 'manager', status: 'blocked', workMode: 'drafts',
    portrait: portrait('RA', '🎯', 'from-red-200 via-rose-500 to-black', 'shadow-rose-500/25', 'Retargeting', 'target board with city rings'), shift: shift('Paid cell check', '16:00', '17:00'),
    missionTypes: ['city_growth_sprint', 'analytics_diagnosis'], canBeSelected: true, defaultPairings: ['paid_micro_operator', 'analytics_beast', 'cmo_prime'], reportsTo: 'cmo_prime',
    tagline: 'Only works when ad pixels, audiences, and budget cells are connected.', responsibilities: ['Recommend retargeting cells', 'Pause poor performers', 'Rotate creatives', 'Protect budget'],
    runbook: ['Check pixel health', 'Review audience pools', 'Set tiny budget cell', 'Pause losers'], tools: ['ad audiences', 'budget cells', 'creative rotation'],
    kpis: [{ label: 'paid CPL', target: '$5-25', unit: 'honest range' }], blockers: ['Meta/Google credentials missing'], complianceBoundaries: ['No discriminatory targeting or misleading financial claims'], lastActivity: 'Blocked until ad integrations are connected.',
  },
  {
    id: 'paid_micro_operator', name: 'Paid Micro Operator', title: '$25/day Budget Operator', kind: 'future_hire', departmentId: 'marketing_cmo', seniority: 'operator', status: 'blocked', workMode: 'queues',
    portrait: portrait('PM', '💸', 'from-green-200 via-lime-500 to-black', 'shadow-lime-500/25', 'Budget Cells', 'tiny budget control desk'), shift: shift('Budget check', '06:00', '07:00'),
    missionTypes: ['city_growth_sprint', 'analytics_diagnosis'], canBeSelected: true, defaultPairings: ['retarget_architect', 'analytics_beast', 'geo_commander'], reportsTo: 'cmo_prime',
    tagline: 'Keeps paid spend honest: it helps, but it does not magically carry the whole lead target.', responsibilities: ['Split $25/day', 'Estimate paid lead range', 'Recommend pause/boost', 'Report honest CPL'],
    runbook: ['Read budget cap', 'Check paid source health', 'Allocate cells', 'Send recommendations'], tools: ['micro budget brain', 'paid source report'],
    kpis: [{ label: 'budget honesty', target: '100', unit: '%' }], blockers: ['ad account missing'], complianceBoundaries: ['No fake paid lead forecasts'], lastActivity: 'Waiting for ad account keys.',
  },
  {
    id: 'inbox_triage', name: 'Inbox Triage', title: 'Reply Classification Operator', kind: 'ai_staff', departmentId: 'nurture_comms', seniority: 'operator', status: 'idle', workMode: 'queues',
    portrait: portrait('IT', '📥', 'from-pink-200 via-rose-500 to-slate-900', 'shadow-rose-500/25', 'Inbox', 'message sorting desk'), shift: shift('Every 15 minutes', '09:00', '21:00'),
    missionTypes: ['nurture_fix', 'lead_action_review', 'appointment_blitz'], canBeSelected: true, defaultPairings: ['liora_lifecycle', 'appointment_architect', 'velvet_hammer'], reportsTo: 'liora_lifecycle',
    tagline: 'Makes sure replies turn into tasks instead of sitting unseen.', responsibilities: ['Classify replies', 'Route hot replies to appointment/sales', 'Flag unsubscribe/stop', 'Create tasks'],
    runbook: ['Read reply', 'Classify intent', 'Check compliance stop words', 'Route to owner'], tools: ['email replies', 'SMS replies', 'CRM notes'],
    kpis: [{ label: 'reply SLA', target: '<15', unit: 'min' }], blockers: ['email/SMS webhook missing'], complianceBoundaries: ['Honor STOP/unsubscribe immediately'], lastActivity: 'Needs webhook connection.',
  },
  {
    id: 'fun_captain', name: 'Fun Captain', title: 'Internal Morale + Recap Host', kind: 'ai_staff', departmentId: 'executive_suite', seniority: 'assistant', status: 'idle', workMode: 'advises',
    portrait: portrait('FC', '🎉', 'from-amber-200 via-pink-500 to-purple-800', 'shadow-pink-500/25', 'Recap', 'confetti on command floor'), shift: shift('Evening recap', '17:00', '18:00'),
    missionTypes: ['analytics_diagnosis', 'overnight_run'], canBeSelected: true, defaultPairings: ['morning_hawk', 'professor_apex', 'analytics_beast'], reportsTo: 'professor_apex',
    tagline: 'Makes the internal staff floor feel alive without pretending to customers.', responsibilities: ['Write internal recaps', 'Celebrate wins', 'Explain blockers in plain English', 'Keep tone energetic'],
    runbook: ['Pull events', 'Write staff recap', 'Highlight 3 wins', 'Call out 1 blocker'], tools: ['staff events', 'daily brief'],
    kpis: [{ label: 'clarity', target: 'high', unit: 'operator feel' }], blockers: ['no event data'], complianceBoundaries: ['Internal tone only; public content remains professional'], lastActivity: 'Ready for end-of-day recap.',
  },
];

export const GEO_CLUSTERS: GeoCluster[] = [
  {
    id: 'dallas_tx', city: 'Dallas', state: 'TX', timezone: 'America/Chicago', priority: 1, status: 'active', zipFocus: ['75201', '75204', '75206', '75219', '75230'],
    activeFunnels: ['business_credit_eguide', 'personal_credit_repair_guide', 'credit_specialist_recruiting'], assignedStaffIds: ['geo_commander', 'scout_supreme', 'appointment_architect'], overnightTarget: 12, dailyTarget: 40,
    sourceMix: [
      { source: 'Lead Intel', targetPct: 30, currentPct: 22, health: 'thin' },
      { source: 'SEO / Lead Magnets', targetPct: 25, currentPct: 28, health: 'good' },
      { source: 'Revival', targetPct: 20, currentPct: 18, health: 'good' },
      { source: 'Partners', targetPct: 15, currentPct: 9, health: 'thin' },
      { source: 'Paid retargeting', targetPct: 10, currentPct: 0, health: 'blocked' },
    ],
    nextMoves: ['Add partner recruiting sprint', 'Queue Dallas business credit page', 'Connect paid retargeting before budget cell'],
  },
  {
    id: 'houston_tx', city: 'Houston', state: 'TX', timezone: 'America/Chicago', priority: 2, status: 'active', zipFocus: ['77002', '77005', '77006', '77019', '77056'],
    activeFunnels: ['funding_readiness_guide', 'business_credit_eguide', 'agency_partner_recruiting'], assignedStaffIds: ['geo_commander', 'night_owl_intel', 'liora_lifecycle'], overnightTarget: 11, dailyTarget: 35,
    sourceMix: [
      { source: 'Lead Intel', targetPct: 35, currentPct: 31, health: 'good' },
      { source: 'SEO / Lead Magnets', targetPct: 25, currentPct: 14, health: 'thin' },
      { source: 'Revival', targetPct: 20, currentPct: 21, health: 'good' },
      { source: 'Partners', targetPct: 10, currentPct: 5, health: 'thin' },
      { source: 'Paid retargeting', targetPct: 10, currentPct: 0, health: 'blocked' },
    ],
    nextMoves: ['Launch Houston funding readiness guide', 'Assign affiliate wrangler to partner source', 'Add local news angle for funding'],
  },
  {
    id: 'atlanta_ga', city: 'Atlanta', state: 'GA', timezone: 'America/New_York', priority: 3, status: 'needs_content', zipFocus: ['30303', '30305', '30308', '30309', '30318'],
    activeFunnels: ['credit_specialist_recruiting', 'affiliate_partner_recruiting', 'personal_credit_repair_guide'], assignedStaffIds: ['geo_commander', 'partner_recruiter', 'content_director'], overnightTarget: 9, dailyTarget: 30,
    sourceMix: [
      { source: 'Lead Intel', targetPct: 30, currentPct: 25, health: 'good' },
      { source: 'SEO / Lead Magnets', targetPct: 25, currentPct: 8, health: 'thin' },
      { source: 'Revival', targetPct: 20, currentPct: 13, health: 'thin' },
      { source: 'Partners', targetPct: 15, currentPct: 14, health: 'good' },
      { source: 'Paid retargeting', targetPct: 10, currentPct: 0, health: 'blocked' },
    ],
    nextMoves: ['Create Atlanta career guide page', 'Run recruiting drive', 'Add local content pack'],
  },
  {
    id: 'phoenix_az', city: 'Phoenix', state: 'AZ', timezone: 'America/Phoenix', priority: 4, status: 'warmup', zipFocus: ['85004', '85012', '85016', '85018', '85032'],
    activeFunnels: ['business_credit_eguide', 'tradeline_guide', 'consultation_booking'], assignedStaffIds: ['geo_commander', 'seo_sentinel', 'scout_supreme'], overnightTarget: 8, dailyTarget: 25,
    sourceMix: [
      { source: 'Lead Intel', targetPct: 35, currentPct: 17, health: 'thin' },
      { source: 'SEO / Lead Magnets', targetPct: 25, currentPct: 7, health: 'thin' },
      { source: 'Revival', targetPct: 20, currentPct: 6, health: 'thin' },
      { source: 'Partners', targetPct: 10, currentPct: 3, health: 'thin' },
      { source: 'Paid retargeting', targetPct: 10, currentPct: 0, health: 'blocked' },
    ],
    nextMoves: ['Warm up with 3 city pages', 'Run source expansion', 'Avoid paid spend until tracking works'],
  },
  {
    id: 'charlotte_nc', city: 'Charlotte', state: 'NC', timezone: 'America/New_York', priority: 5, status: 'active', zipFocus: ['28202', '28203', '28205', '28209', '28277'],
    activeFunnels: ['funding_readiness_guide', 'agency_partner_recruiting', 'affiliate_partner_recruiting'], assignedStaffIds: ['geo_commander', 'partner_recruiter', 'pr_sentinel'], overnightTarget: 10, dailyTarget: 30,
    sourceMix: [
      { source: 'Lead Intel', targetPct: 30, currentPct: 21, health: 'thin' },
      { source: 'SEO / Lead Magnets', targetPct: 25, currentPct: 20, health: 'good' },
      { source: 'Revival', targetPct: 20, currentPct: 15, health: 'thin' },
      { source: 'Partners', targetPct: 15, currentPct: 11, health: 'good' },
      { source: 'Paid retargeting', targetPct: 10, currentPct: 0, health: 'blocked' },
    ],
    nextMoves: ['Build local PR angle', 'Recruit agency partners', 'Add funding readiness short link'],
  },
  {
    id: 'miami_fl', city: 'Miami', state: 'FL', timezone: 'America/New_York', priority: 6, status: 'warmup', zipFocus: ['33127', '33130', '33131', '33132', '33137'],
    activeFunnels: ['personal_credit_repair_guide', 'business_credit_eguide', 'au_seller_recruiting'], assignedStaffIds: ['geo_commander', 'content_director', 'scout_supreme'], overnightTarget: 7, dailyTarget: 25,
    sourceMix: [
      { source: 'Lead Intel', targetPct: 35, currentPct: 0, health: 'thin' },
      { source: 'SEO / Lead Magnets', targetPct: 25, currentPct: 0, health: 'thin' },
      { source: 'Revival', targetPct: 20, currentPct: 0, health: 'thin' },
      { source: 'Partners', targetPct: 10, currentPct: 0, health: 'thin' },
      { source: 'Paid retargeting', targetPct: 10, currentPct: 0, health: 'blocked' },
    ],
    nextMoves: ['Add Miami to swarm city list', 'Create Spanish-friendly content option later', 'Map AU seller route'],
  },
  {
    id: 'tampa_fl', city: 'Tampa', state: 'FL', timezone: 'America/New_York', priority: 7, status: 'warmup', zipFocus: ['33602', '33606', '33607', '33609', '33629'],
    activeFunnels: ['business_credit_eguide', 'funding_readiness_guide', 'credit_specialist_recruiting'], assignedStaffIds: ['geo_commander', 'seo_sentinel', 'partner_recruiter'], overnightTarget: 6, dailyTarget: 22,
    sourceMix: [
      { source: 'Lead Intel', targetPct: 35, currentPct: 0, health: 'thin' },
      { source: 'SEO / Lead Magnets', targetPct: 25, currentPct: 0, health: 'thin' },
      { source: 'Revival', targetPct: 20, currentPct: 0, health: 'thin' },
      { source: 'Partners', targetPct: 10, currentPct: 0, health: 'thin' },
      { source: 'Paid retargeting', targetPct: 10, currentPct: 0, health: 'blocked' },
    ],
    nextMoves: ['Create business funding page', 'Run partner source scan', 'Add local event calendars'],
  },
  {
    id: 'orlando_fl', city: 'Orlando', state: 'FL', timezone: 'America/New_York', priority: 8, status: 'needs_content', zipFocus: ['32801', '32803', '32804', '32819', '32835'],
    activeFunnels: ['affiliate_partner_recruiting', 'credit_specialist_recruiting', 'consultation_booking'], assignedStaffIds: ['geo_commander', 'affiliate_wrangler', 'content_director'], overnightTarget: 6, dailyTarget: 20,
    sourceMix: [
      { source: 'Lead Intel', targetPct: 35, currentPct: 0, health: 'thin' },
      { source: 'SEO / Lead Magnets', targetPct: 25, currentPct: 0, health: 'thin' },
      { source: 'Revival', targetPct: 20, currentPct: 0, health: 'thin' },
      { source: 'Partners', targetPct: 10, currentPct: 0, health: 'thin' },
      { source: 'Paid retargeting', targetPct: 10, currentPct: 0, health: 'blocked' },
    ],
    nextMoves: ['Create affiliate partner page', 'Build career-focused content pack', 'Start low-risk community queue'],
  },
];

export function findStaff(id: string): StaffMember | null {
  return STAFF_MEMBERS.find((x) => x.id === id) ?? null;
}

export function listDepartmentStaff(departmentId: StaffDepartmentId) {
  return STAFF_MEMBERS.filter((x) => x.departmentId === departmentId);
}

export function listSelectableStaff() {
  return STAFF_MEMBERS.filter((x) => x.canBeSelected);
}

export function staffForMission(missionType: StaffMissionType) {
  return STAFF_MEMBERS.filter((x) => x.canBeSelected && x.missionTypes.includes(missionType));
}

export function departmentForMission(missionType: StaffMissionType): StaffDepartment {
  return STAFF_DEPARTMENTS.find((d) => d.missionTypes.includes(missionType)) ?? STAFF_DEPARTMENTS[0];
}
