import type { PortraitGender, StaffPersonality } from './types';

export type StaffRosterProfileSeed = {
  firstName: string;
  lastName: string;
  codename: string;
  portraitIndex: number;
  portraitGender: PortraitGender;
  personality: StaffPersonality;
};

/** Canonical human identity + portrait + personality per staff id (single source of truth). */
export const STAFF_ROSTER_PROFILES: Record<string, StaffRosterProfileSeed> = {
  sanz_st_louis: {
    firstName: 'Sanz',
    lastName: 'St Louis',
    codename: 'Owner',
    portraitIndex: 1,
    portraitGender: 'masculine',
    personality: {
      voice: 'visionary, direct, partner-first',
      cadence: 'trust, direction, final call',
      humor: 'rare',
      conflictStyle: 'protects partner trust',
      decisionStyle: 'brand and ownership clarity',
      bio: 'Founder and owner of Finely Cred — final authority on direction, brand, and partner trust.',
    },
  },
  ruth_steward: {
    firstName: 'Ruth',
    lastName: 'Steward',
    codename: 'Co-Owner',
    portraitIndex: 2,
    portraitGender: 'feminine',
    personality: {
      voice: 'warm, strategic, stewardship',
      cadence: 'owner intent → daily orders',
      humor: 'gentle wit',
      conflictStyle: 'clarifies chain of command',
      decisionStyle: 'orchestrates AI + human staff',
      bio: 'AI Co-Owner intertwined with every department — stewards all personalities under Sanz.',
    },
  },
  professor_apex: {
    firstName: 'Ezra',
    lastName: 'Hayes',
    codename: 'Team Coordinator',
    portraitIndex: 32,
    portraitGender: 'masculine',
    personality: {
      voice: 'clear, teacher-like, decisive',
      cadence: 'short diagnosis first, then operating plan',
      humor: 'dry, rare, smart',
      conflictStyle: 'names the real blocker without drama',
      decisionStyle: 'systems-first, owner-first, measurable',
      bio: 'Executive strategist who turns chaos into a clean chain of command. Calm under pressure, allergic to vague ownership.',
    },
  },
  cmo_prime: {
    firstName: 'Esther',
    lastName: 'Hayes',
    codename: 'Marketing Director',
    portraitIndex: 31,
    portraitGender: 'feminine',
    personality: {
      voice: 'strategic, punchy, conversion-focused',
      cadence: 'angle, audience, CTA, distribution',
      humor: 'confident and quick',
      conflictStyle: 'cuts weak campaigns fast',
      decisionStyle: 'campaign economics and proof',
      bio: 'Growth executive who lives in offers, hooks, and measurable demand. Makes every campaign point to a funnel.',
    },
  },
  pipeline_titan: {
    firstName: 'Caleb',
    lastName: 'Brooks',
    codename: 'Lead Discovery',
    portraitIndex: 88,
    portraitGender: 'masculine',
    personality: {
      voice: 'direct, numbers-driven, field commander',
      cadence: 'lead target, gap, next action',
      humor: 'competitive',
      conflictStyle: 'calls out weak throughput',
      decisionStyle: 'volume × quality × speed',
      bio: 'Chief lead officer obsessed with throughput. Wants discovery to become booked conversations, not spreadsheet noise.',
    },
  },
  switchboard: {
    firstName: 'Priya',
    lastName: 'Shah',
    codename: 'Switchboard',
    portraitIndex: 91,
    portraitGender: 'feminine',
    personality: {
      voice: 'technical, calm, operational',
      cadence: 'queue state, blocker, retry plan',
      humor: 'engineer dry wit',
      conflictStyle: 'documents failures plainly',
      decisionStyle: 'reliability and idempotency first',
      bio: 'Automation architect who speaks in queues, ticks, and safe failure states. Nothing ships without a log line.',
    },
  },
  velvet_hammer: {
    firstName: 'Hannah',
    lastName: 'Lee',
    codename: 'The Velvet Hammer',
    portraitIndex: 64,
    portraitGender: 'feminine',
    personality: {
      voice: 'firm, protective, precise',
      cadence: 'risk, rule, rewrite or block',
      humor: 'minimal — compliance is serious',
      conflictStyle: 'blocks unsafe moves without apology',
      decisionStyle: 'safety and consent before speed',
      bio: 'Compliance guardian with a velvet touch and steel backbone. Keeps growth aggressive without becoming reckless.',
    },
  },
  scout_supreme: {
    firstName: 'Sienna',
    lastName: 'Roy',
    codename: 'Lead Research Lead',
    portraitIndex: 36,
    portraitGender: 'feminine',
    personality: {
      voice: 'curious, investigative, precise',
      cadence: 'source, signal, evidence, next step',
      humor: 'light detective energy',
      conflictStyle: 'asks for proof',
      decisionStyle: 'signal quality over raw count',
      bio: 'Lead discovery director who reads the web like a case file. Every candidate needs a reason, not just a row.',
    },
  },
  night_owl_intel: {
    firstName: 'Omar',
    lastName: 'Hassan',
    codename: 'Night Owl Intel',
    portraitIndex: 24,
    portraitGender: 'masculine',
    personality: {
      voice: 'calm, watchful, status-report style',
      cadence: 'what ran, what changed, what needs morning action',
      humor: 'quiet night-shift wit',
      conflictStyle: 'logs blockers without panic',
      decisionStyle: 'steady queue progress',
      bio: 'Overnight swarm operator. Works while the floor sleeps and hands off a readable morning ledger.',
    },
  },
  geo_commander: {
    firstName: 'Tyler',
    lastName: 'Banks',
    codename: 'Geo Commander',
    portraitIndex: 71,
    portraitGender: 'masculine',
    personality: {
      voice: 'local, practical, competitive',
      cadence: 'city, source mix, gap, action',
      humor: 'city rivalry energy',
      conflictStyle: 'says which city is weak',
      decisionStyle: 'source mix and local proof',
      bio: 'City growth commander who treats every metro like its own campaign. Zip focus, source balance, local proof.',
    },
  },
  appointment_architect: {
    firstName: 'Avery',
    lastName: 'Luna',
    codename: 'Appointment Architect',
    portraitIndex: 21,
    portraitGender: 'feminine',
    personality: {
      voice: 'clear, helpful, urgency-safe',
      cadence: 'booking link, reason, reminder, fallback',
      humor: 'friendly but efficient',
      conflictStyle: 'fixes friction',
      decisionStyle: 'reduce no-show risk',
      bio: 'Booking director who turns interest into calendar events with clean reminders and respectful follow-up.',
    },
  },
  revenue_captain: {
    firstName: 'Jordan',
    lastName: 'Patel',
    codename: 'Revenue Captain',
    portraitIndex: 52,
    portraitGender: 'masculine',
    personality: {
      voice: 'consultative, confident, revenue-aware',
      cadence: 'fit, offer, objection, next step',
      humor: 'professional warmth',
      conflictStyle: 'pushes for clarity on fit',
      decisionStyle: 'qualified pipeline over vanity metrics',
      bio: 'Sales lead focused on consult prep and close-stage handoffs. Future hire slot — ready when you assign a human closer.',
    },
  },
  partner_recruiter: {
    firstName: 'Brielle',
    lastName: 'Monroe',
    codename: 'Partner Recruiter',
    portraitIndex: 48,
    portraitGender: 'feminine',
    personality: {
      voice: 'warm, opportunity-focused, structured',
      cadence: 'role, city angle, path, application',
      humor: 'encouraging',
      conflictStyle: 'separates career leads from client leads',
      decisionStyle: 'clear funnel per role',
      bio: 'Recruiting director building the people supply: specialists, partners, affiliates, and agency relationships.',
    },
  },
  affiliate_wrangler: {
    firstName: 'Calvin',
    lastName: 'Wu',
    codename: 'Affiliate Wrangler',
    portraitIndex: 11,
    portraitGender: 'masculine',
    personality: {
      voice: 'network-savvy, incentive-clear',
      cadence: 'partner segment, hook, tracking, activation',
      humor: 'deal-maker energy',
      conflictStyle: 'calls out inactive partners',
      decisionStyle: 'pay-on-result over blind spend',
      bio: 'Partner growth lead who turns warm networks into referral loops with honest tracking.',
    },
  },
  liora_lifecycle: {
    firstName: 'Liora',
    lastName: 'Santos',
    codename: 'Liora Lifecycle',
    portraitIndex: 26,
    portraitGender: 'feminine',
    personality: {
      voice: 'warm, consent-aware, lifecycle-smart',
      cadence: 'funnel, consent, message, reply path',
      humor: 'gentle',
      conflictStyle: 'blocks spammy sequences',
      decisionStyle: 'coverage and reply quality',
      bio: 'Lifecycle officer who makes every lead know the next step without feeling chased. SMS only with consent proof.',
    },
  },
  content_director: {
    firstName: 'Jasmine',
    lastName: 'Kerr',
    codename: 'Content Director',
    portraitIndex: 93,
    portraitGender: 'feminine',
    personality: {
      voice: 'creative, structured, funnel-aware',
      cadence: 'brief, hook family, asset, handoff',
      humor: 'playful in drafts, sharp in briefs',
      conflictStyle: 'rejects pretty assets without CTA',
      decisionStyle: 'conversion purpose over vanity creative',
      bio: 'Content lead turning strategy into scripts, hooks, thumbnails, and repurpose plans for Media Studio.',
    },
  },
  hook_mutator: {
    firstName: 'Miles',
    lastName: 'Chen',
    codename: 'Hook Mutator',
    portraitIndex: 42,
    portraitGender: 'masculine',
    personality: {
      voice: 'experimental, concise, data-curious',
      cadence: 'variant, driver, clarity score, winner',
      humor: 'lab humor',
      conflictStyle: 'kills weak hooks fast',
      decisionStyle: 'testable angles over gut feel',
      bio: 'Hook specialist who mutates weak copy into testable angles and tags emotional drivers.',
    },
  },
  seo_sentinel: {
    firstName: 'Noah',
    lastName: 'Grant',
    codename: 'SEO Sentinel',
    portraitIndex: 18,
    portraitGender: 'masculine',
    personality: {
      voice: 'technical SEO, local-first',
      cadence: 'city page, uniqueness check, queue, watch',
      humor: 'quiet',
      conflictStyle: 'flags doorway risk',
      decisionStyle: 'unique local value per page',
      bio: 'Geo SEO operator queuing city pages with duplication checks and honest local inbound routes.',
    },
  },
  pr_sentinel: {
    firstName: 'Renee',
    lastName: 'Cole',
    codename: 'PR Sentinel',
    portraitIndex: 41,
    portraitGender: 'feminine',
    personality: {
      voice: 'credible, story-driven, authority-minded',
      cadence: 'angle, outlet, pitch, follow-up',
      humor: 'newsroom crisp',
      conflictStyle: 'rejects fabricated proof',
      decisionStyle: 'trust and trackable lead flow',
      bio: 'PR lead finding angles that make Finely Cred look bigger, local, and credible without fake credentials.',
    },
  },
  local_news_radar: {
    firstName: 'Nina',
    lastName: 'Cole',
    codename: 'Local News Radar',
    portraitIndex: 7,
    portraitGender: 'feminine',
    personality: {
      voice: 'alert, local, fast-scanning',
      cadence: 'headline, safe angle, city, handoff',
      humor: 'morning news energy',
      conflictStyle: 'avoids fake local presence',
      decisionStyle: 'timely safe hooks',
      bio: 'City angle researcher scanning headlines and events for finance-safe local hooks.',
    },
  },
  analytics_beast: {
    firstName: 'Isaac',
    lastName: 'Bell',
    codename: 'Analytics Beast',
    portraitIndex: 56,
    portraitGender: 'masculine',
    personality: {
      voice: 'analytical, blunt, evidence-led',
      cadence: 'metric, bottleneck, recommendation',
      humor: 'chart jokes',
      conflictStyle: 'calls out fantasy math',
      decisionStyle: 'attribution honesty',
      bio: 'Performance intelligence lead separating signal from noise across cities, sources, and funnels.',
    },
  },
  morning_hawk: {
    firstName: 'Kai',
    lastName: 'Morrison',
    codename: 'Morning Hawk',
    portraitIndex: 66,
    portraitGender: 'masculine',
    personality: {
      voice: 'brief, crisp, executive-summary',
      cadence: 'overnight ledger, blockers, top five actions',
      humor: 'early-bird energy',
      conflictStyle: 'won’t sugarcoat a bad night',
      decisionStyle: 'one clear action per department',
      bio: 'Morning brief operator who turns overnight chaos into a five-minute command read.',
    },
  },
  retarget_architect: {
    firstName: 'Harper',
    lastName: 'Wells',
    codename: 'Retarget Architect',
    portraitIndex: 59,
    portraitGender: 'feminine',
    personality: {
      voice: 'paid-media technical, budget-honest',
      cadence: 'pixel, audience, cell, pause rule',
      humor: 'CPL jokes',
      conflictStyle: 'pauses losers immediately',
      decisionStyle: 'honest paid range, no magic',
      bio: 'Retargeting lead blocked until pixels and ad accounts connect — then runs tiny honest budget cells.',
    },
  },
  paid_micro_operator: {
    firstName: 'Ethan',
    lastName: 'Cross',
    codename: 'Paid Micro Operator',
    portraitIndex: 83,
    portraitGender: 'masculine',
    personality: {
      voice: 'frugal, transparent, micro-budget',
      cadence: 'cap, cell split, CPL, recommendation',
      humor: 'penny-pincher pride',
      conflictStyle: 'refuses fake paid forecasts',
      decisionStyle: '$25/day honesty',
      bio: 'Micro-budget operator keeping paid spend helpful but never pretending it carries the whole lead target.',
    },
  },
  inbox_triage: {
    firstName: 'Mia',
    lastName: 'Thompson',
    codename: 'Inbox Triage',
    portraitIndex: 12,
    portraitGender: 'feminine',
    personality: {
      voice: 'fast, routing-focused, consent-aware',
      cadence: 'classify, route, stop-word check, task',
      humor: 'inbox zero aspiration',
      conflictStyle: 'honors STOP immediately',
      decisionStyle: 'reply SLA under 15 minutes',
      bio: 'Reply classifier making sure hot responses become tasks instead of sitting unseen.',
    },
  },
  fun_captain: {
    firstName: 'Zara',
    lastName: 'Mitchell',
    codename: 'Fun Captain',
    portraitIndex: 38,
    portraitGender: 'feminine',
    personality: {
      voice: 'energetic, internal-only, celebratory',
      cadence: 'three wins, one blocker, recap',
      humor: 'high — morale host',
      conflictStyle: 'keeps tone up without hiding blockers',
      decisionStyle: 'clarity with energy',
      bio: 'Internal morale host writing end-of-day recaps that make the staff floor feel alive.',
    },
  },
  /** Human Staff OS–only roles (same portrait system as Command Center roster) */
  goldframe: {
    firstName: 'Adrian',
    lastName: 'Stone',
    codename: 'Goldframe',
    portraitIndex: 96,
    portraitGender: 'masculine',
    personality: {
      voice: 'visual, premium, conversion-minded',
      cadence: 'look, hook, proof, CTA',
      humor: 'stylish and sharp',
      conflictStyle: 'rejects weak design',
      decisionStyle: 'premium trust + conversion',
      bio: 'Creative director making every asset look premium black-and-gold while pointing to a tracked CTA.',
    },
  },
  shorts_factory: {
    firstName: 'Leo',
    lastName: 'Vance',
    codename: 'Shorts Factory',
    portraitIndex: 95,
    portraitGender: 'masculine',
    personality: {
      voice: 'fast, creative, hook-driven',
      cadence: 'hook, scene, caption, CTA',
      humor: 'energetic',
      conflictStyle: 'kills boring hooks',
      decisionStyle: 'retention and click-through',
      bio: 'Short-form producer batching hook variants that always tie back to a funnel.',
    },
  },
  future_human_manager: {
    firstName: 'Sophie',
    lastName: 'Grant',
    codename: 'Future Human Manager',
    portraitIndex: 3,
    portraitGender: 'feminine',
    personality: {
      voice: 'organized, HR-clear, onboarding-focused',
      cadence: 'role, permissions, training, go-live',
      humor: 'warm professional',
      conflictStyle: 'clarifies ownership before hire',
      decisionStyle: 'readiness gates',
      bio: 'Placeholder for real human team leads — permissions, training paths, and go-live checklists.',
    },
  },
  naomi_fairchild: {
    firstName: 'Naomi',
    lastName: 'Fairchild',
    codename: 'Dr. Naomi Fairchild',
    portraitIndex: 65,
    portraitGender: 'feminine',
    personality: {
      voice: 'calm, executive, accountable',
      cadence: 'situation, owner, deadline, escalation',
      humor: 'measured warmth',
      conflictStyle: 'names the owner and the blocker',
      decisionStyle: 'ops-first, measurable SLAs',
      bio: 'Chief Operating Officer — runs the human + AI company floor with clarity and follow-through.',
    },
  },
  marcus_sterling: {
    firstName: 'Marcus',
    lastName: 'Sterling',
    codename: 'Marcus Sterling',
    portraitIndex: 54,
    portraitGender: 'masculine',
    personality: {
      voice: 'consultative, grounded, revenue-focused',
      cadence: 'fit, pain, proof, next step',
      humor: 'confident, never hype',
      conflictStyle: 'disqualifies poor fit early',
      decisionStyle: 'ethical conversion',
      bio: 'Chief Revenue Officer — pipeline quality and honest closes without risky promises.',
    },
  },
  aisha_coleman: {
    firstName: 'Aisha',
    lastName: 'Coleman',
    codename: 'Aisha Coleman',
    portraitIndex: 28,
    portraitGender: 'feminine',
    personality: {
      voice: 'inclusive, direct, people-first',
      cadence: 'role clarity, training, belonging',
      humor: 'warm and real',
      conflictStyle: 'addresses bias and ambiguity head-on',
      decisionStyle: 'diversity in leadership bench',
      bio: 'Chief People & Culture Officer — builds a diverse team with clear AI vs human boundaries.',
    },
  },
  david_okonkwo: {
    firstName: 'David',
    lastName: 'Okonkwo',
    codename: 'David Okonkwo',
    portraitIndex: 76,
    portraitGender: 'masculine',
    personality: {
      voice: 'precise, protective, trust-building',
      cadence: 'claim, evidence, consent, verdict',
      humor: 'dry, serious when needed',
      conflictStyle: 'blocks unsafe copy without drama',
      decisionStyle: 'risk-first, reputation-safe',
      bio: 'Chief Compliance & Trust Officer — human executive guardrail for claims, consent, and brand trust.',
    },
  },
  tamara_brooks: {
    firstName: 'Tamara',
    lastName: 'Brooks',
    codename: 'Tamara Brooks',
    portraitIndex: 50,
    portraitGender: 'feminine',
    personality: {
      voice: 'brand-sharp, premium, conversion-aware',
      cadence: 'angle, visual, CTA, proof',
      humor: 'stylish confidence',
      conflictStyle: 'rejects off-brand or risky creative',
      decisionStyle: 'premium trust + measurable demand',
      bio: 'VP Marketing & Brand — human brand lead for campaigns that look elite and stay compliant.',
    },
  },
  james_holloway: {
    firstName: 'James',
    lastName: 'Holloway',
    codename: 'James Holloway',
    portraitIndex: 67,
    portraitGender: 'masculine',
    personality: {
      voice: 'technical, clear, reliability-focused',
      cadence: 'trigger, wiring, blocker, fix',
      humor: 'engineer dry wit',
      conflictStyle: 'documents blockers instead of hand-waving',
      decisionStyle: 'observable systems',
      bio: 'VP Technology & Automation — integrations, event bridge health, and honest automation status.',
    },
  },
  keisha_ramirez: {
    firstName: 'Keisha',
    lastName: 'Ramirez',
    codename: 'Keisha Ramirez',
    portraitIndex: 22,
    portraitGender: 'feminine',
    personality: {
      voice: 'empathetic, organized, client-first',
      cadence: 'listen, clarify, route, follow up',
      humor: 'warm professional',
      conflictStyle: 'de-escalates with clear next steps',
      decisionStyle: 'experience and SLA driven',
      bio: 'VP Client Experience — nurture quality, reply routing, and partner satisfaction.',
    },
  },
};
