import React from 'react';
import { useNavigate } from 'react-router-dom';
import { PageShell } from '../../components/layout/PageShell';
import { usePublicSeoMeta } from '../../hooks/usePublicSeoMeta';
import { FinelyOsPageFooter } from '../../features/os/FinelyOsPageFooter';
import { FinelyUnifiedHubLayout } from '../../features/unified/FinelyUnifiedHubLayout';
import {
  FINELY_OS_BACK_LINK,
  FINELY_OS_ENTITY_BODY,
  FINELY_OS_ENTITY_SUBLABEL,
  FINELY_OS_ENTITY_VALUE,
  FINELY_OS_NOTICE_WARN,
  FINELY_OS_PAGE,
} from '../../features/os/finelyOsLightUi';
import { MarketingStaffChatStrip } from '../../components/marketing/MarketingStaffChatStrip';

const LAST_UPDATED_ISO = '2026-02-05';

export default function DisclaimerPage() {
  const navigate = useNavigate();
  usePublicSeoMeta({
    title: 'Disclaimer',
    description: 'Educational services disclaimer — not legal advice or credit repair guarantees.',
    path: '/disclaimer',
  });
  return (
    <PageShell
      badge="Legal"
      title="Disclaimer"
      subtitle="Important information about the nature of our services and limitations."
    >
      <div className={FINELY_OS_PAGE}>
        <FinelyUnifiedHubLayout
          eyebrow="Legal"
          title="Disclaimer"
          subtitle={`Last updated: ${new Date(LAST_UPDATED_ISO).toLocaleDateString()}`}
          accent="fuchsia"
          tabs={[{ id: 'disclaimer', label: 'Disclaimer' }]}
          activeTab="disclaimer"
          secondaryAction={{ label: 'Terms of service', onClick: () => navigate('/terms') }}
        >
        <div className={`${FINELY_OS_NOTICE_WARN} md:p-8 space-y-6`}>
          <section className={`space-y-3 ${FINELY_OS_ENTITY_BODY}`}>
            <h2 className={`${FINELY_OS_ENTITY_VALUE} text-base`}>Not Legal or Financial Advice</h2>
            <p>
              Finely Cred provides educational content and tools for credit awareness and dispute workflows. We do not provide
              legal advice, financial advice, or credit repair services in the sense of acting as your attorney or financial
              advisor. For legal or tax matters, please consult a licensed professional.
            </p>
          </section>

          <section className={`space-y-3 ${FINELY_OS_ENTITY_BODY}`}>
            <h2 className={`${FINELY_OS_ENTITY_VALUE} text-base`}>Educational Tools & Templates</h2>
            <p>
              Any templates, letters, scripts, or “intelligence” outputs generated by the platform are provided for educational and
              workflow purposes only. You are responsible for reviewing, verifying, and deciding whether to use any output. If you
              need legal representation or advice for your jurisdiction and facts, consult a licensed attorney.
            </p>
          </section>

          <section className={`space-y-3 ${FINELY_OS_ENTITY_BODY}`}>
            <h2 className={`${FINELY_OS_ENTITY_VALUE} text-base`}>No Guarantee of Results</h2>
            <p>
              Credit outcomes depend on many factors, including bureau and furnisher response, your individual situation, and
              applicable law. We do not guarantee specific score changes, removals, or approval for any product or funding.
            </p>
          </section>

          <section className={`space-y-3 ${FINELY_OS_ENTITY_BODY}`}>
            <h2 className={`${FINELY_OS_ENTITY_VALUE} text-base`}>Third-Party Services</h2>
            <p>
              The platform may link to or integrate with third-party services (for example: payment processors, financing providers,
              or credit monitoring providers). Those third parties operate under their own terms and privacy policies, and we do not
              control their services.
            </p>
          </section>

          <section className={`space-y-3 ${FINELY_OS_ENTITY_BODY}`}>
            <h2 className={`${FINELY_OS_ENTITY_VALUE} text-base`}>Accuracy of Information</h2>
            <p>
              We strive to keep our platform and content accurate but do not warrant that all information is complete or
              current. You are responsible for verifying important details with bureaus, creditors, or advisors.
            </p>
          </section>

          <section className={`space-y-3 ${FINELY_OS_ENTITY_BODY}`}>
            <h2 className={`${FINELY_OS_ENTITY_VALUE} text-base`}>Contact</h2>
            <p>
              Questions about this disclaimer may be directed to the contact information on our Contact page or in the
              platform footer.
            </p>
          </section>
        </div>
        </FinelyUnifiedHubLayout>

        <MarketingStaffChatStrip
          roleId="support_specialist"
          goal="not_sure"
          roleLabel="partner success specialist"
          subline="Need clarification on compliance or educational scope? Chat with our on-duty specialist."
          buttonTone="secondary"
        />

        <FinelyOsPageFooter />
      </div>
    </PageShell>
  );
}
