import React from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowLeft, AlertCircle } from 'lucide-react';
import { PageShell } from '../../components/layout/PageShell';

const LAST_UPDATED_ISO = '2026-02-05';

export default function DisclaimerPage() {
  const navigate = useNavigate();
  return (
    <PageShell
      badge="Legal"
      title="Disclaimer"
      subtitle="Important information about the nature of our services and limitations."
    >
      <div className="space-y-6">
        <div className="flex flex-wrap items-center gap-4">
          <button
            onClick={() => navigate(-1)}
            className="inline-flex items-center gap-2 text-white/60 hover:text-white transition-colors text-sm"
          >
            <ArrowLeft size={16} /> Back
          </button>
          <a
            href="/"
            className="inline-flex items-center gap-2 text-white/60 hover:text-white transition-colors text-sm"
          >
            <ArrowLeft size={16} /> Home
          </a>
        </div>

        <div className="rounded-2xl border border-amber-500/20 bg-amber-500/5 backdrop-blur-xl p-6 md:p-8 space-y-6 text-white/80 text-sm leading-relaxed">
          <div className="flex items-center gap-2 text-amber-400">
            <AlertCircle size={18} />
            <span className="text-xs font-semibold uppercase tracking-wider">Disclaimer</span>
          </div>
          <p className="text-white/50 text-xs uppercase tracking-wider">
            Last updated: {new Date(LAST_UPDATED_ISO).toLocaleDateString()}
          </p>

          <section className="space-y-3">
            <h2 className="text-white font-semibold text-base">Not Legal or Financial Advice</h2>
            <p>
              Finely Cred provides educational content and tools for credit awareness and dispute workflows. We do not provide
              legal advice, financial advice, or credit repair services in the sense of acting as your attorney or financial
              advisor. For legal or tax matters, please consult a licensed professional.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-white font-semibold text-base">Educational Tools & Templates</h2>
            <p>
              Any templates, letters, scripts, or “intelligence” outputs generated by the platform are provided for educational and
              workflow purposes only. You are responsible for reviewing, verifying, and deciding whether to use any output. If you
              need legal representation or advice for your jurisdiction and facts, consult a licensed attorney.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-white font-semibold text-base">No Guarantee of Results</h2>
            <p>
              Credit outcomes depend on many factors, including bureau and furnisher response, your individual situation, and
              applicable law. We do not guarantee specific score changes, removals, or approval for any product or funding.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-white font-semibold text-base">Third-Party Services</h2>
            <p>
              The platform may link to or integrate with third-party services (for example: payment processors, financing providers,
              or credit monitoring providers). Those third parties operate under their own terms and privacy policies, and we do not
              control their services.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-white font-semibold text-base">Accuracy of Information</h2>
            <p>
              We strive to keep our platform and content accurate but do not warrant that all information is complete or
              current. You are responsible for verifying important details with bureaus, creditors, or advisors.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-white font-semibold text-base">Contact</h2>
            <p>
              Questions about this disclaimer may be directed to the contact information on our Contact page or in the
              platform footer.
            </p>
          </section>
        </div>
      </div>
    </PageShell>
  );
}
