import type { LeadIntelSourceAdapter, LeadIntelSourceId } from './types';

export const LEAD_INTEL_SOURCE_ADAPTERS: LeadIntelSourceAdapter[] = [

  { id: 'serper_web' as LeadIntelSourceId, label: 'Serper Web', method: 'official_api', requiresEnv: ['VITE_SERPER_ENABLED'], defaultDailyCap: 30, defaultCadenceMinutes: 15, supportsContinuous: true, notes: 'Queues gracefully when credentials are missing; uses public or official sources only.' },
  { id: 'serper_news' as LeadIntelSourceId, label: 'Serper News', method: 'official_api', requiresEnv: ['VITE_SERPER_ENABLED'], defaultDailyCap: 40, defaultCadenceMinutes: 25, supportsContinuous: true, notes: 'Queues gracefully when credentials are missing; uses public or official sources only.' },
  { id: 'serper_places' as LeadIntelSourceId, label: 'Serper Places', method: 'official_api', requiresEnv: ['VITE_SERPER_ENABLED'], defaultDailyCap: 50, defaultCadenceMinutes: 35, supportsContinuous: true, notes: 'Queues gracefully when credentials are missing; uses public or official sources only.' },
  { id: 'google_maps_leads' as LeadIntelSourceId, label: 'Google Maps Leads', method: 'public_directory', requiresEnv: [], defaultDailyCap: 60, defaultCadenceMinutes: 45, supportsContinuous: true, notes: 'Queues gracefully when credentials are missing; uses public or official sources only.' },
  { id: 'reddit_geo' as LeadIntelSourceId, label: 'Reddit Geo', method: 'official_api', requiresEnv: [], defaultDailyCap: 70, defaultCadenceMinutes: 55, supportsContinuous: true, notes: 'Queues gracefully when credentials are missing; uses public or official sources only.' },
  { id: 'facebook_groups_manual_queue' as LeadIntelSourceId, label: 'Facebook Groups Manual Queue', method: 'manual_queue', requiresEnv: [], defaultDailyCap: 80, defaultCadenceMinutes: 15, supportsContinuous: true, notes: 'Queues gracefully when credentials are missing; uses public or official sources only.' },
  { id: 'nextdoor_manual_queue' as LeadIntelSourceId, label: 'Nextdoor Manual Queue', method: 'manual_queue', requiresEnv: [], defaultDailyCap: 90, defaultCadenceMinutes: 25, supportsContinuous: true, notes: 'Queues gracefully when credentials are missing; uses public or official sources only.' },
  { id: 'craigslist_services' as LeadIntelSourceId, label: 'Craigslist Services', method: 'rss', requiresEnv: [], defaultDailyCap: 30, defaultCadenceMinutes: 35, supportsContinuous: true, notes: 'Queues gracefully when credentials are missing; uses public or official sources only.' },
  { id: 'youtube_comments' as LeadIntelSourceId, label: 'Youtube Comments', method: 'official_api', requiresEnv: [], defaultDailyCap: 40, defaultCadenceMinutes: 45, supportsContinuous: true, notes: 'Queues gracefully when credentials are missing; uses public or official sources only.' },
  { id: 'tiktok_hashtag_watch' as LeadIntelSourceId, label: 'Tiktok Hashtag Watch', method: 'official_api', requiresEnv: [], defaultDailyCap: 50, defaultCadenceMinutes: 55, supportsContinuous: true, notes: 'Queues gracefully when credentials are missing; uses public or official sources only.' },
  { id: 'instagram_geo_hashtags' as LeadIntelSourceId, label: 'Instagram Geo Hashtags', method: 'official_api', requiresEnv: [], defaultDailyCap: 60, defaultCadenceMinutes: 15, supportsContinuous: true, notes: 'Queues gracefully when credentials are missing; uses public or official sources only.' },
  { id: 'linkedin_search' as LeadIntelSourceId, label: 'Linkedin Search', method: 'official_api', requiresEnv: [], defaultDailyCap: 70, defaultCadenceMinutes: 25, supportsContinuous: true, notes: 'Queues gracefully when credentials are missing; uses public or official sources only.' },
  { id: 'x_search' as LeadIntelSourceId, label: 'X Search', method: 'official_api', requiresEnv: [], defaultDailyCap: 80, defaultCadenceMinutes: 35, supportsContinuous: true, notes: 'Queues gracefully when credentials are missing; uses public or official sources only.' },
  { id: 'quora_credit' as LeadIntelSourceId, label: 'Quora Credit', method: 'public_directory', requiresEnv: [], defaultDailyCap: 90, defaultCadenceMinutes: 45, supportsContinuous: true, notes: 'Queues gracefully when credentials are missing; uses public or official sources only.' },
  { id: 'bbb_complaints' as LeadIntelSourceId, label: 'Bbb Complaints', method: 'public_directory', requiresEnv: [], defaultDailyCap: 30, defaultCadenceMinutes: 55, supportsContinuous: true, notes: 'Queues gracefully when credentials are missing; uses public or official sources only.' },
  { id: 'chamber_of_commerce' as LeadIntelSourceId, label: 'Chamber Of Commerce', method: 'public_directory', requiresEnv: [], defaultDailyCap: 40, defaultCadenceMinutes: 15, supportsContinuous: true, notes: 'Queues gracefully when credentials are missing; uses public or official sources only.' },
  { id: 'local_event_calendars' as LeadIntelSourceId, label: 'Local Event Calendars', method: 'rss', requiresEnv: [], defaultDailyCap: 50, defaultCadenceMinutes: 25, supportsContinuous: true, notes: 'Queues gracefully when credentials are missing; uses public or official sources only.' },
  { id: 'indeed_role_watch' as LeadIntelSourceId, label: 'Indeed Role Watch', method: 'public_directory', requiresEnv: [], defaultDailyCap: 60, defaultCadenceMinutes: 35, supportsContinuous: true, notes: 'Queues gracefully when credentials are missing; uses public or official sources only.' },
  { id: 'google_alerts_ingest' as LeadIntelSourceId, label: 'Google Alerts Ingest', method: 'rss', requiresEnv: [], defaultDailyCap: 70, defaultCadenceMinutes: 45, supportsContinuous: true, notes: 'Queues gracefully when credentials are missing; uses public or official sources only.' },
  { id: 'indiehackers_hn' as LeadIntelSourceId, label: 'Indiehackers Hn', method: 'public_directory', requiresEnv: [], defaultDailyCap: 80, defaultCadenceMinutes: 55, supportsContinuous: true, notes: 'Queues gracefully when credentials are missing; uses public or official sources only.' },
  { id: 'domain_expiry_lists' as LeadIntelSourceId, label: 'Domain Expiry Lists', method: 'public_directory', requiresEnv: [], defaultDailyCap: 90, defaultCadenceMinutes: 15, supportsContinuous: true, notes: 'Queues gracefully when credentials are missing; uses public or official sources only.' },
  { id: 'review_sites' as LeadIntelSourceId, label: 'Review Sites', method: 'public_directory', requiresEnv: [], defaultDailyCap: 30, defaultCadenceMinutes: 25, supportsContinuous: true, notes: 'Queues gracefully when credentials are missing; uses public or official sources only.' },
  { id: 'competitor_review_complaints' as LeadIntelSourceId, label: 'Competitor Review Complaints', method: 'public_directory', requiresEnv: [], defaultDailyCap: 40, defaultCadenceMinutes: 35, supportsContinuous: true, notes: 'Queues gracefully when credentials are missing; uses public or official sources only.' },
  { id: 'webhook_meta_leads' as LeadIntelSourceId, label: 'Webhook Meta Leads', method: 'webhook', requiresEnv: [], defaultDailyCap: 50, defaultCadenceMinutes: 45, supportsContinuous: true, notes: 'Queues gracefully when credentials are missing; uses public or official sources only.' },
  { id: 'webhook_google_lsa' as LeadIntelSourceId, label: 'Webhook Google Lsa', method: 'webhook', requiresEnv: [], defaultDailyCap: 60, defaultCadenceMinutes: 55, supportsContinuous: true, notes: 'Queues gracefully when credentials are missing; uses public or official sources only.' },
  { id: 'csv_seed_expansion' as LeadIntelSourceId, label: 'Csv Seed Expansion', method: 'public_directory', requiresEnv: [], defaultDailyCap: 70, defaultCadenceMinutes: 15, supportsContinuous: true, notes: 'Queues gracefully when credentials are missing; uses public or official sources only.' },
  { id: 'dead_lead_revival' as LeadIntelSourceId, label: 'Dead Lead Revival', method: 'internal', requiresEnv: [], defaultDailyCap: 80, defaultCadenceMinutes: 25, supportsContinuous: true, notes: 'Queues gracefully when credentials are missing; uses public or official sources only.' },
  { id: 'affiliate_referral_loop' as LeadIntelSourceId, label: 'Affiliate Referral Loop', method: 'internal', requiresEnv: [], defaultDailyCap: 90, defaultCadenceMinutes: 35, supportsContinuous: true, notes: 'Queues gracefully when credentials are missing; uses public or official sources only.' },
  { id: 'seo_inbound_forms' as LeadIntelSourceId, label: 'Seo Inbound Forms', method: 'internal', requiresEnv: [], defaultDailyCap: 30, defaultCadenceMinutes: 45, supportsContinuous: true, notes: 'Queues gracefully when credentials are missing; uses public or official sources only.' },
  { id: 'sms_reply_capture' as LeadIntelSourceId, label: 'Sms Reply Capture', method: 'internal', requiresEnv: [], defaultDailyCap: 40, defaultCadenceMinutes: 55, supportsContinuous: true, notes: 'Queues gracefully when credentials are missing; uses public or official sources only.' },
  { id: 'email_reply_capture' as LeadIntelSourceId, label: 'Email Reply Capture', method: 'internal', requiresEnv: [], defaultDailyCap: 50, defaultCadenceMinutes: 15, supportsContinuous: true, notes: 'Queues gracefully when credentials are missing; uses public or official sources only.' },
  { id: 'local_news_radar' as LeadIntelSourceId, label: 'Local News Radar', method: 'rss', requiresEnv: [], defaultDailyCap: 60, defaultCadenceMinutes: 25, supportsContinuous: true, notes: 'Queues gracefully when credentials are missing; uses public or official sources only.' },
  { id: 'podcast_guest_watch' as LeadIntelSourceId, label: 'Podcast Guest Watch', method: 'public_directory', requiresEnv: [], defaultDailyCap: 70, defaultCadenceMinutes: 35, supportsContinuous: true, notes: 'Queues gracefully when credentials are missing; uses public or official sources only.' },
  { id: 'meetup_event_watch' as LeadIntelSourceId, label: 'Meetup Event Watch', method: 'rss', requiresEnv: [], defaultDailyCap: 80, defaultCadenceMinutes: 45, supportsContinuous: true, notes: 'Queues gracefully when credentials are missing; uses public or official sources only.' },
  { id: 'merchant_directory_watch' as LeadIntelSourceId, label: 'Merchant Directory Watch', method: 'public_directory', requiresEnv: [], defaultDailyCap: 90, defaultCadenceMinutes: 55, supportsContinuous: true, notes: 'Queues gracefully when credentials are missing; uses public or official sources only.' },
  { id: 'realtor_lender_partner_watch' as LeadIntelSourceId, label: 'Realtor Lender Partner Watch', method: 'public_directory', requiresEnv: [], defaultDailyCap: 30, defaultCadenceMinutes: 15, supportsContinuous: true, notes: 'Queues gracefully when credentials are missing; uses public or official sources only.' },
  { id: 'college_entrepreneur_watch' as LeadIntelSourceId, label: 'College Entrepreneur Watch', method: 'public_directory', requiresEnv: [], defaultDailyCap: 40, defaultCadenceMinutes: 25, supportsContinuous: true, notes: 'Queues gracefully when credentials are missing; uses public or official sources only.' },
  { id: 'veteran_business_watch' as LeadIntelSourceId, label: 'Veteran Business Watch', method: 'public_directory', requiresEnv: [], defaultDailyCap: 50, defaultCadenceMinutes: 35, supportsContinuous: true, notes: 'Queues gracefully when credentials are missing; uses public or official sources only.' },
  { id: 'minority_business_directory' as LeadIntelSourceId, label: 'Minority Business Directory', method: 'public_directory', requiresEnv: [], defaultDailyCap: 60, defaultCadenceMinutes: 45, supportsContinuous: true, notes: 'Queues gracefully when credentials are missing; uses public or official sources only.' },
  { id: 'nonprofit_partner_watch' as LeadIntelSourceId, label: 'Nonprofit Partner Watch', method: 'public_directory', requiresEnv: [], defaultDailyCap: 70, defaultCadenceMinutes: 55, supportsContinuous: true, notes: 'Queues gracefully when credentials are missing; uses public or official sources only.' },
  { id: 'small_claims_public_calendar' as LeadIntelSourceId, label: 'Small Claims Public Calendar', method: 'public_directory', requiresEnv: [], defaultDailyCap: 80, defaultCadenceMinutes: 15, supportsContinuous: true, notes: 'Queues gracefully when credentials are missing; uses public or official sources only.' },
  { id: 'ucc_public_record_watch' as LeadIntelSourceId, label: 'Ucc Public Record Watch', method: 'public_directory', requiresEnv: [], defaultDailyCap: 90, defaultCadenceMinutes: 25, supportsContinuous: true, notes: 'Queues gracefully when credentials are missing; uses public or official sources only.' },
];

export function getLeadIntelSourceAdapter(id: LeadIntelSourceId): LeadIntelSourceAdapter | null {
  return LEAD_INTEL_SOURCE_ADAPTERS.find((a) => a.id === id) ?? null;
}

export function sourceRequiresManualReview(id: LeadIntelSourceId): boolean {
  const a = getLeadIntelSourceAdapter(id);
  return a?.method === 'manual_queue';
}
