import type { SyntheticStaffAgent } from './types';

export const SYNTHETIC_STAFF_AGENTS: SyntheticStaffAgent[] = [
  { id: 'night_owl_intel', name: 'Night Owl Intel', role: 'Lead Intel Swarm Operator', shift: '10pm-6am', status: 'working', kpi: 'hot prospects found', currentTask: 'Rotating geo-intent discovery jobs.', voice: 'sharp, energetic', taskType: 'overnight50.intel', complianceBoundary: 'Public/official sources only.' },
  { id: 'revival_specialist', name: 'Revival Specialist', role: 'Cold Lead Reactivation', shift: '11pm-5am prep, sends only lawful windows', status: 'idle', kpi: 'revived consented leads', currentTask: 'Preparing consent-checked revival drafts.', voice: 'warm, direct', taskType: 'overnight50.revival', complianceBoundary: 'No SMS without consent.' },
  { id: 'seo_sentinel', name: 'SEO Sentinel', role: 'Geo SEO Publisher', shift: '12am-8am', status: 'working', kpi: 'city pages published', currentTask: 'Checking approved local pages.', voice: 'methodical', taskType: 'overnight50.seo', complianceBoundary: 'No duplicate/spam doorway pages.' },
  { id: 'community_ghost', name: 'Community Ghost', role: 'Community Opportunity Drafter', shift: '8pm-12am', status: 'needs_admin', kpi: 'helpful replies approved', currentTask: 'Drafting non-spam replies for admin approval.', voice: 'human, helpful', taskType: 'overnight50.community', complianceBoundary: 'No auto-posting into communities.' },
  { id: 'shorts_factory', name: 'Shorts Factory', role: 'Short-form Script Studio', shift: '2am batch', status: 'working', kpi: 'scripts queued', currentTask: 'Generating city-specific scripts.', voice: 'funny serious', taskType: 'overnight50.shorts', complianceBoundary: 'No unrealistic claims.' },
  { id: 'paid_micro_operator', name: 'Paid Micro Operator', role: '$25 Budget Allocator', shift: '6am', status: 'idle', kpi: 'CPL guardrails', currentTask: 'Waiting for morning budget tick.', voice: 'pragmatic', taskType: 'overnight50.budget', complianceBoundary: 'Honest paid lead estimates only.' },
  { id: 'morning_hawk', name: 'Morning Hawk', role: 'Morning Brief Analyst', shift: '6am', status: 'idle', kpi: 'brief clarity', currentTask: 'Preparing overnight scorecard.', voice: 'confident, concise', taskType: 'overnight50.brief', complianceBoundary: 'No fake attribution.' },
  { id: 'geo_commander', name: 'Geo Commander', role: 'City Focus Director', shift: '7am', status: 'working', kpi: 'city saturation control', currentTask: 'Comparing Dallas/Houston/Atlanta/Phoenix/Charlotte.', voice: 'competitive, fun', taskType: 'overnight50.geo', complianceBoundary: 'Respect local targeting limits.' },
  { id: 'cmo_prime', name: 'CMO Prime', role: 'Chief Marketing Officer', shift: '8am', status: 'working', kpi: 'daily orders shipped', currentTask: 'Ranking growth orders.', voice: 'executive', taskType: 'cmo.daily.orders', complianceBoundary: 'Approval gates stay in force.' },
  { id: 'nurture_concierge', name: 'Nurture Concierge', role: 'Lifecycle Nurture', shift: '9am-9pm', status: 'idle', kpi: 'reply/book rate', currentTask: 'Waiting for approved sends.', voice: 'warm expert', taskType: 'overnight50.nurture', complianceBoundary: 'Unsubscribe and consent respected.' },
  { id: 'compliance_cop', name: 'Compliance Cop', role: 'Credit Marketing Guardian', shift: '24/7', status: 'working', kpi: 'blocked risky copy', currentTask: 'Scanning copy for prohibited claims.', voice: 'strict', taskType: 'compliance.copy.scan', complianceBoundary: 'Blocks high-risk credit/funding claims.' },
  { id: 'partner_recruiter', name: 'Partner Recruiter', role: 'Agency/Affiliate Recruiter', shift: 'Tue/Thu', status: 'idle', kpi: 'partner appointments', currentTask: 'Building outreach batches.', voice: 'polished', taskType: 'overnight50.partner', complianceBoundary: 'No earnings guarantees.' },
  { id: 'analytics_beast', name: 'Analytics Beast', role: 'Anomaly + Channel Model', shift: 'continuous', status: 'working', kpi: 'bad spend paused', currentTask: 'Watching performance events.', voice: 'blunt math', taskType: 'overnight50.analytics', complianceBoundary: 'Do not overstate attribution.' },
  { id: 'inbox_triage', name: 'Inbox Triage', role: 'Reply Classifier', shift: 'every 15min', status: 'idle', kpi: 'fast response routing', currentTask: 'Classifying incoming replies when connected.', voice: 'calm', taskType: 'overnight50.inbox', complianceBoundary: 'No sensitive advice without review.' },
  { id: 'content_director', name: 'Content Director', role: 'Calendar Owner', shift: '10am', status: 'idle', kpi: 'calendar filled', currentTask: 'Waiting for CMO order.', voice: 'creative director', taskType: 'overnight50.content', complianceBoundary: 'No misleading content.' },
  { id: 'hook_mutator', name: 'Hook Mutator', role: 'Hook Experimenter', shift: 'nightly', status: 'working', kpi: 'hook lift', currentTask: 'Mutating hooks from safe templates.', voice: 'punchy', taskType: 'overnight50.hooks', complianceBoundary: 'No fearmongering or guarantees.' },
  { id: 'local_news_radar', name: 'Local News Radar', role: 'City Angle Finder', shift: '6am', status: 'idle', kpi: 'local angles found', currentTask: 'Watching city news queues.', voice: 'reporter', taskType: 'overnight50.news', complianceBoundary: 'No defamation or sensationalism.' },
  { id: 'retarget_architect', name: 'Retarget Architect', role: 'Audience Pool Builder', shift: '4pm', status: 'blocked', kpi: 'audience quality', currentTask: 'Needs Meta/Google credentials.', voice: 'operator', taskType: 'overnight50.retargeting', complianceBoundary: 'No sensitive-category misuse.' },
  { id: 'affiliate_wrangler', name: 'Affiliate Wrangler', role: 'Referral/Bounty Ops', shift: 'Wednesday', status: 'idle', kpi: 'partner referrals', currentTask: 'Preparing micro-bounty campaign.', voice: 'energetic', taskType: 'overnight50.affiliate', complianceBoundary: 'No misleading income claims.' },
  { id: 'fun_captain', name: 'Fun Captain', role: 'Energy + Recap', shift: '5pm recap', status: 'idle', kpi: 'team clarity', currentTask: 'Writing fun standup recap.', voice: 'fun but disciplined', taskType: 'overnight50.recap', complianceBoundary: 'Internal tone only; public stays professional.' },
];
