import type { CmoCampaignPlaybook, CmoExecutionStep, CmoGrowthChannel } from '../../domain/cmoPhase3';
import { makeCmoId } from '../../data/cmoPhase3Repo';

const stamp = () => new Date().toISOString();

function step(title: string, actionType: CmoExecutionStep['actionType'], channel: CmoGrowthChannel | undefined, estimatedLeadImpact: number, riskLevel: CmoExecutionStep['riskLevel'] = 'low'): CmoExecutionStep {
  return {
    id: makeCmoId('step'),
    title,
    description: title,
    actionType,
    status: riskLevel === 'blocked' ? 'blocked' : 'queued',
    channel,
    requiresApproval: actionType === 'external_publish_adapter' || riskLevel !== 'low',
    riskLevel,
    estimatedLeadImpact,
    inputRefs: [],
    outputRefs: [],
    notes: [],
  };
}

function playbook(input: Omit<CmoCampaignPlaybook, 'id' | 'status' | 'createdAt' | 'updatedAt'>): CmoCampaignPlaybook {
  const createdAt = stamp();
  return { ...input, id: makeCmoId('playbook'), status: 'ready', createdAt, updatedAt: createdAt };
}

export function buildDefaultCmoPlaybooks(): CmoCampaignPlaybook[] {
  return [
    playbook({
      name: 'Authority Interview Blitz',
      season: 'month_1_authority',
      objective: 'Book interviews, podcasts, and expert features that make Finely Cred look unavoidable.',
      channels: ['press_pr', 'interviews_podcasts', 'linkedin', 'email'],
      targetAudience: 'Podcast hosts, financial educators, business communities, and local media.',
      offer: 'Expert guest segment on credit, business funding readiness, and financial comeback stories.',
      promise: 'Give their audience practical, compliant insight without boring them into the furniture.',
      proofNeeded: ['founder story', 'client-safe outcomes', 'press kit', 'topics list', 'headshots'],
      assetsToCreate: ['press pitch', 'media kit copy', 'LinkedIn authority posts', 'interview topic sheet', 'follow-up email'],
      automationSteps: [
        step('Build media target segment from Lead Intel', 'create_campaign', 'lead_intel', 12),
        step('Create interview pitch sequence in Comms Studio', 'create_comms_sequence', 'email', 18),
        step('Create LinkedIn authority post set', 'create_scheduler_posts', 'linkedin', 10),
        step('Create follow-up CRM tasks for interested hosts', 'create_crm_tasks', 'crm_reactivation', 8),
      ],
      leadTargetPerDay: 18,
      conversionHypothesis: 'Authority creates trust faster than cold offer pushes.',
      complianceNotes: ['Avoid guaranteed outcomes; position as education and readiness.'],
      ownerRole: 'Press + PR Director',
      priorityScore: 96,
    }),
    playbook({
      name: 'Shorts to Consultation Machine',
      season: 'evergreen',
      objective: 'Turn short-form videos into booked calls through strong hooks, pinned CTAs, and fast reply triage.',
      channels: ['youtube_shorts', 'instagram_reels', 'tiktok', 'sms'],
      targetAudience: 'Consumers and business owners who need credit/funding readiness help.',
      offer: 'Free or low-friction credit/funding readiness consultation.',
      promise: 'Stop guessing. Get a roadmap.',
      proofNeeded: ['safe testimonials', 'before-after story without score claims', 'expert credibility', 'FAQ answers'],
      assetsToCreate: ['30 hooks', '15 scripts', 'visual prompts', 'pinned comments', 'reply bank', 'SMS follow-up'],
      automationSteps: [
        step('Generate 15 short-form scripts and storyboard prompts', 'create_media_project', 'youtube_shorts', 24),
        step('Create scheduler posts for Shorts/Reels/TikTok', 'create_scheduler_posts', 'instagram_reels', 22),
        step('Classify comments and draft replies', 'classify_inbox', 'youtube_shorts', 20),
        step('Create SMS follow-up for interested commenters', 'create_comms_sequence', 'sms', 14, 'medium'),
      ],
      leadTargetPerDay: 35,
      conversionHypothesis: 'High-frequency educational/proof content with reply capture can create daily lead flow.',
      complianceNotes: ['No guaranteed score lift, no guaranteed approvals, label AI content when required.'],
      ownerRole: 'Social Channel Director',
      priorityScore: 99,
    }),
    playbook({
      name: 'Affiliate Army Activation',
      season: 'month_3_affiliate',
      objective: 'Recruit and activate affiliates who can send qualified prospects repeatedly.',
      channels: ['affiliate', 'partner_outreach', 'email', 'linkedin'],
      targetAudience: 'Credit educators, business coaches, real estate communities, trucking groups, finance influencers.',
      offer: 'Affiliate/referral partnership with approved materials and clear payout path.',
      promise: 'Give partners a clean way to monetize their audience while helping them look smart.',
      proofNeeded: ['affiliate one-sheet', 'approved claims guide', 'tracking links', 'payout rules', 'sample posts'],
      assetsToCreate: ['affiliate landing page copy', 'outreach sequence', 'partner kit', 'social swipe pack', 'onboarding email'],
      automationSteps: [
        step('Build affiliate prospect segment from Lead Intel', 'create_campaign', 'lead_intel', 25),
        step('Create affiliate outreach sequence', 'create_comms_sequence', 'email', 20),
        step('Create partner kit media assets', 'create_media_project', 'affiliate', 15),
        step('Create CRM follow-up tasks for warm partners', 'create_crm_tasks', 'partner_outreach', 18),
      ],
      leadTargetPerDay: 24,
      conversionHypothesis: 'A small group of active partners can outperform scattered content.',
      complianceNotes: ['Affiliates must use approved wording and disclosures.'],
      ownerRole: 'Affiliate Manager',
      priorityScore: 98,
    }),
    playbook({
      name: 'Product Month Launch Sprint',
      season: 'month_2_product',
      objective: 'Promote product/book/course offers with a full funnel instead of random posts.',
      channels: ['email', 'sms', 'youtube_shorts', 'instagram_reels', 'seo_content', 'webinar'],
      targetAudience: 'People who need structure, education, and a clear next step.',
      offer: 'Book, course, or digital product connected to higher-ticket services.',
      promise: 'Turn confusion into a practical financial growth roadmap.',
      proofNeeded: ['product screenshots', 'lesson outcomes', 'creator authority', 'bonuses', 'FAQ'],
      assetsToCreate: ['launch emails', 'SMS reminders', 'sales page sections', 'webinar script', 'reels scripts'],
      automationSteps: [
        step('Create launch campaign and content calendar', 'create_campaign', 'email', 18),
        step('Create email and SMS sequence drafts', 'create_comms_sequence', 'email', 20),
        step('Create webinar/replay media project', 'create_media_project', 'webinar', 16),
        step('Create scheduler posts for launch window', 'create_scheduler_posts', 'instagram_reels', 18),
      ],
      leadTargetPerDay: 28,
      conversionHypothesis: 'Education products build trust and create ascension into consultations.',
      complianceNotes: ['Keep product claims educational; do not promise financial outcomes.'],
      ownerRole: 'Product Marketing Lead',
      priorityScore: 92,
    }),
    playbook({
      name: 'Business Funding Readiness Funnel',
      season: 'evergreen',
      objective: 'Attract business owners who want funding but need readiness review first.',
      channels: ['lead_intel', 'linkedin', 'email', 'sms', 'webinar', 'partner_outreach'],
      targetAudience: 'Business owners, trucking operators, real estate investors, startups.',
      offer: 'Funding readiness review and business credit roadmap.',
      promise: 'Know what lenders may look at before you chase funding blindfolded.',
      proofNeeded: ['readiness checklist', 'safe case studies', 'lender criteria education', 'FAQ'],
      assetsToCreate: ['lead magnet', 'landing page copy', 'webinar deck outline', 'email sequence', 'LinkedIn posts'],
      automationSteps: [
        step('Create business owner audience snapshot', 'create_campaign', 'lead_intel', 24),
        step('Create readiness checklist funnel copy', 'create_copy', 'seo_content', 18),
        step('Create outreach and nurture sequence', 'create_comms_sequence', 'email', 22),
        step('Create webinar scheduler posts', 'create_scheduler_posts', 'linkedin', 14),
      ],
      leadTargetPerDay: 32,
      conversionHypothesis: 'Readiness positioning is safer and more credible than funding promises.',
      complianceNotes: ['No guaranteed funding, no guaranteed approvals, no deceptive lender language.'],
      ownerRole: 'Growth Operator',
      priorityScore: 97,
    }),
    playbook({
      name: 'Cold Lead Resurrection',
      season: 'evergreen',
      objective: 'Reactivate old leads with relevance, humor, and a clear next move.',
      channels: ['crm_reactivation', 'email', 'sms'],
      targetAudience: 'Past inquiries, no-shows, old applicants, abandoned booking leads.',
      offer: 'Updated review, restart plan, or limited-time consultation window.',
      promise: 'You are not starting over; we are picking the lock with a better key.',
      proofNeeded: ['new offer notes', 'updated service page links', 'FAQ', 'booking link'],
      assetsToCreate: ['reactivation email set', 'SMS set', 'reply scripts', 'CRM note templates'],
      automationSteps: [
        step('Create cold lead segment', 'create_campaign', 'crm_reactivation', 18),
        step('Create email/SMS reactivation sequence', 'create_comms_sequence', 'sms', 20, 'medium'),
        step('Create CRM follow-up tasks for replies', 'create_crm_tasks', 'crm_reactivation', 12),
      ],
      leadTargetPerDay: 20,
      conversionHypothesis: 'Warm history beats cold traffic when the message is fresh and respectful.',
      complianceNotes: ['Respect consent, opt-outs, and message frequency.'],
      ownerRole: 'Lead Gen Manager',
      priorityScore: 91,
    }),
    playbook({
      name: 'Proof Without Reckless Claims',
      season: 'evergreen',
      objective: 'Turn testimonials, stories, and FAQs into compliant trust-building content.',
      channels: ['youtube_shorts', 'instagram_reels', 'linkedin', 'seo_content', 'email'],
      targetAudience: 'Skeptical prospects who need proof before booking.',
      offer: 'Consultation, readiness plan, or education product.',
      promise: 'Real stories, useful education, no circus tricks.',
      proofNeeded: ['testimonial permissions', 'story summaries', 'disclaimers', 'before/after context without guaranteed score claims'],
      assetsToCreate: ['story posts', 'FAQ reels', 'objection emails', 'landing page proof blocks'],
      automationSteps: [
        step('Create proof asset library', 'create_media_project', 'instagram_reels', 14),
        step('Score all proof copy through compliance gate', 'score_assets', 'email', 10, 'medium'),
        step('Schedule proof-and-objection content', 'create_scheduler_posts', 'linkedin', 12),
      ],
      leadTargetPerDay: 16,
      conversionHypothesis: 'Skeptical leads convert when proof feels real and not overcooked.',
      complianceNotes: ['Use disclaimers, avoid guaranteed outcomes, get permission.'],
      ownerRole: 'Compliance Guardian',
      priorityScore: 89,
    }),
  ];
}
